import {model} from './cosmos-math.js';
import {makeStudio,control as s,clock,number as f} from './studio-core.js';
export const COSMOS_LABS={};
function add(id,title,modes,description,defaults,controls,label,unit,key,target,rule,correct,wrong,read,timeline=false){COSMOS_LABS[id]=makeStudio({id,title,modes,description,defaults,controls,label,unit,key,target,rule,correct,wrong,read,timeline},model);}
add('cosmological-equation-of-state','Cambia el contenido de un universo',['Dilución','Explorar','Presión y aceleración'],'Fluido homogéneo FLRW con w constante. La conservación relaciona densidad, presión y expansión; la gravedad depende de ρ+3p/c².',{w:0,a:2},[s('w','Parámetro w',-1,1,.1),s('a','Escala a/a0',.5,4,.1)],'Densidad ρ/ρ0','','w',-1,'ρ/ρ0=a^(−3(1+w)); p=wρc².','w<−1/3 aporta aceleración positiva en la ecuación de aceleración','Toda presión positiva acelera la expansión',(p,q)=>`ρ/ρ0=${f(q.ratio)}; p/(ρ0c²)=${f(q.pressure)}; factor gravitatorio 1+3w=${f(q.accelerationFactor)}.`);
add('friedmann-equations','Explora materia, curvatura y vacío',['Historia futura','Explorar','Componentes'],'Expansión FLRW futura desde a=1, con materia sin presión, curvatura y constante cosmológica positiva. La integración sigue la rama expansiva y se detiene en un retorno.',{H0:70,matter:.3,vacuum:.7,t:0},[s('H0','H0',50,90,1,'km/s/Mpc'),s('matter','Ωm,0',0,2,.05),s('vacuum','ΩΛ,0',0,2,.05),clock()],'Hubble instantáneo','km/s/Mpc','H0',80,'H²=H0²(Ωm/a³+Ωk/a²+ΩΛ), Ωk=1−Ωm−ΩΛ.','La curvatura es una contribución geométrica, no una densidad ordinaria de partículas','Ωm+ΩΛ puede elegirse libremente sin cambiar Ωk',(p,q)=>`a=${f(q.a)}; q=${f(q.q)}; Ωk,0=${f(q.curvature)}. Tiempo=${f(q.time)} Gyr${q.turnaround?'; retorno alcanzado: rama expansiva detenida':''}. Se omite radiación.`,true);
add('critical-density-parameter','Compara densidad con una referencia dinámica',['Densidad crítica','Explorar','Ω'],'Densidad crítica de una época, calculada con su Hubble. Ω compara densidad total de masa-equivalente con esa referencia; no se deduce geometría usando únicamente materia.',{H0:70,density:.3},[s('density','Densidad total',.1,2,.05,'10⁻²⁶ kg/m³'),s('H0','Hubble',50,90,1,'km/s/Mpc')],'Parámetro Ω','','density',1,'ρcrit=3H²/(8πG); Ω=ρtotal/ρcrit.','Ω exige incluir todos los componentes relevantes en esa época','Ω de materia por sí sola fija siempre la curvatura',(p,q)=>`ρcrit=${f(q.critical/1e-26)} ×10⁻²⁶ kg/m³; Ω=${f(q.omega)}; se convierten km y Mpc a SI.`);
add('cosmological-redshift','Estira una onda con el espacio',['Onda estirada','Explorar','Escalas'],'Una onda libre entre dos épocas FLRW cumple λobs/λemit=aobs/aemit. El desplazamiento cosmológico no se identifica automáticamente con Doppler local.',{emit:.5,now:1,lambda:500},[s('emit','Escala de emisión',.1,2,.05),s('now','Escala de observación',.5,2,.05),s('lambda','Longitud emitida',200,800,10,'nm')],'Longitud observada','nm','emit',.25,'1+z=aobs/aemit; λobs=(1+z)λemit.','Un universo en contracción puede producir z negativo','Todo corrimiento cosmológico es una velocidad Doppler local',(p,q)=>`z=${f(q.z)}; λobs=${f(q.lambda)} nm. Las escalas relativas son adimensionales y positivas.`);
add('hubble-law','Separa distancia y velocidad de recesión',['Red de galaxias 3D','Explorar','Ley lineal'],'Relación instantánea vrec=H·D entre observadores comóviles y distancia propia a la misma época. A gran distancia una velocidad de recesión puede superar c sin movimiento local superlumínico.',{H0:70,distance:100},[s('distance','Distancia propia',10,6000,10,'Mpc'),s('H0','Hubble',50,90,1,'km/s/Mpc')],'Recesión','km/s','distance',300,'vrec=H·D; H0 no es una constante universal del tiempo.','La velocidad de recesión usa distancias entre puntos separados en una foliación cosmológica','vrec>c obliga a una galaxia a cruzar localmente el espacio más rápido que la luz',(p,q)=>`vrec/c=${f(q.ratio)}; 1/H=${f(q.time)} Gyr. Tiempo de Hubble no equivale siempre a edad; no se convierte z grande mediante v=cz.`);
