import * as M from './frontier-math.js';
import {fmt} from './learning-math.js';
const s=(key,label,min,max,step=1,unit='')=>({key,label,min,max,step,unit});
const menu=(key,label,options)=>({key,label,options});
const q=(title,story,params,answer,explanation,hint,extra={})=>({title,story,params,answer,explanation,hint,...extra});
const tune=(editable,get,solution,tolerance=.02)=>({kind:'tune',editable,get,solution,tolerance});
const choice=choices=>({kind:'choice',choices});
const time=(unit='s')=>s('t','Tiempo',0,20,.01,unit);
const functionMenu=menu('fn','Función',[['exp','eˣ'],['sin','sin x'],['log','ln(1+x)']]);
const lab=(title,modes,description,demoDescription,defaults,controls,read,missions,extra={})=>({title,modes,description,demoDescription,defaults,controls,read,missions,accent:'#387d8f',animate:false,...extra});
const budgetRead=p=>{const v=M.capital(p);return `Capital = ${fmt(v.A)} € · intereses = ${fmt(v.interest)} € · tasa anual efectiva = ${fmt(v.effective)} %. Sin aportaciones, comisiones ni impuestos.`;};
const seriesRead=p=>{const v=M.series(p);return `P${p.n}(${fmt(p.x)}) = ${fmt(v.polynomial,5)} · ${v.actual===null?'La función no está definida en x.':`f(x) = ${fmt(v.actual,5)} · error firmado = ${fmt(v.error,5)} · cota de Lagrange ≤ ${fmt(v.bound,5)}.`} ${v.inside?'Dentro del intervalo de convergencia garantizado.':'Fuera del intervalo abierto de convergencia: el polinomio sigue existiendo; la igualdad con la serie no está garantizada.'}`;};
const flowControls=[s('A1','Sección de entrada',.002,.02,.001,'m²'),s('A2','Sección de salida',.002,.02,.001,'m²'),s('Q','Caudal',.002,.03,.001,'m³/s'),s('p1','Presión de entrada (manométrica)',10,100,1,'kPa'),s('z1','Altura de entrada',0,5,.1,'m'),s('z2','Altura de salida',0,5,.1,'m')];
const flowDefaults={A1:.01,A2:.005,Q:.01,p1:30,z1:0,z2:0,rho:1000,K:0,pump:0,t:0};
const flowRead=p=>{const v=M.flow(p);return `v₁ = ${fmt(v.v1)} m/s · v₂ = ${fmt(v.v2)} m/s · p₂ = ${fmt(v.p2)} kPa · pérdida = ${fmt(v.loss)} m · H₁ + bomba − pérdida = H₂. Presiones manométricas; no se calcula cavitación.`;};
export const FRONTIER_LABS={
 'compound-interest-exponential-capital-growth':lab('El interés también produce intereses',['Metas','Explorar','Poder adquisitivo'],'Cambia el capital, la tasa nominal y la frecuencia. Compara interés simple, compuesto y el límite continuo.','La curva de poder adquisitivo descuenta una inflación constante. Mantén separados euros nominales y euros del momento inicial.',{P:1000,r:10,n:1,t:2,inflation:3},[s('P','Capital inicial',100,10000,100,'€'),s('r','Tasa nominal anual',0,15,.1,'%'),menu('n','Capitalizaciones al año',[['1','Anual'],['4','Trimestral'],['12','Mensual'],['365','Diaria']]),s('t','Plazo',0,20,1,'años'),s('inflation','Inflación anual',0,10,.1,'%')],budgetRead,[
 q('Dos años de crecimiento','Depositas 1000 € al 10 % nominal anual, capitalización anual y sin aportaciones. ¿Cuánto hay al final de dos años?',{},1210,'1000·1,1² = 1210 €. El segundo año genera intereses sobre 1100 €.','Multiplica por 1,1 dos veces.',{unit:'€'}),
 q('Ajusta el plazo','Busca un plazo entero que transforme 1000 € en 1331 €, al 10 % anual.',{t:1},1331,'Tres años: 1000·1,1³ = 1331 €.','El capital no aumenta una cantidad fija cada año.',tune(['t'],p=>M.capital(p).A,{t:3},.1)),
 q('Cuando crece la inflación','Si el capital nominal no cambia y aumenta la inflación positiva, ¿qué ocurre con el poder adquisitivo?',{},'falls','Dividir entre (1+inflación)ᵗ reduce el valor en euros iniciales.','Una misma cantidad compra menos.',choice([['falls','Disminuye'],['same','Permanece igual'],['rises','Aumenta']])),
 q('Frecuencia trimestral','Con 1000 €, r = 8 % y n = 4, ¿cuánto hay al terminar un año?',{r:8,n:'4',t:1},1082.43216,'Cada trimestre aplica 2 %: 1000·1,02⁴ ≈ 1082,43 €.','La tasa por periodo es r/n.',{unit:'€'})],{demoRead:p=>{const v=M.capital(p);return `Valor nominal = ${fmt(v.A)} € · poder adquisitivo = ${fmt(v.real)} € iniciales · inflación = ${fmt(p.inflation)} % anual.`;}}),
 'derivative-as-limit':lab('Acerca dos puntos sin hacerlos coincidir',['Pendientes','Explorar','Dos lados'],'Arrastra el segundo punto de la secante y compara su pendiente con la tangente. h nunca vale cero.','Las aproximaciones izquierda y derecha deben coincidir. En |x|, el vértice tiene dos pendientes laterales distintas.',{fn:'square',x:2,h:1,side:'right'},[menu('fn','Curva',[['square','x²'],['sin','sin x'],['abs','|x|']]),s('x','Punto x',-3,3,.1),s('h','Distancia |h|',.001,2,.001),menu('side','Lado',[['right','Derecha'],['left','Izquierda']])],p=>{const v=M.derivative(p);return `Secante = ${fmt(v.secant,5)} · ${v.tangent===null?'Derivada inexistente: izquierda −1, derecha +1.':`derivada = ${fmt(v.tangent,5)}`}. h firmado = ${fmt(v.dx,4)}.`;},[
 q('Una secante todavía larga','f(x)=x², x=2 y h=1. ¿Cuál es la pendiente de la secante?',{},5,'(9−4)/1 = 5. La derivada en x=2 será 4 al acercar h a cero.','Evalúa f(3) y f(2).'),
 q('Busca la pendiente local','Para x², ajusta x hasta que la derivada sea 6.',{x:1},6,'f′(x)=2x: el punto buscado es x=3.','La respuesta es una pendiente; el control cambia x.',tune(['x'],p=>M.derivative(p).tangent,{x:3})),
 q('Un vértice no es una tangente','¿Existe la derivada de |x| en x=0?',{fn:'abs',x:0},'no','Los límites laterales −1 y +1 no coinciden. Tener continuidad no basta.','Compara ambos lados.',choice([['no','No existe'],['zero','Vale cero'],['one','Vale uno']])),
 q('Una tangente a una señal','¿Cuál es la derivada de sin x en x=0, con x en radianes?',{fn:'sin',x:0,h:.01},1,'La derivada es cos0 = 1. Las secantes convergen a ella.','La derivada del seno es el coseno.')]),
 'linear-momentum-conservation':lab('Dos carritos, un balance',['Choques','Explorar','Energía'],'Reproduce el encuentro de dos carritos ideales. El parámetro e elige cuánto se separan después del choque.','La cantidad de movimiento se conserva en todos estos choques aislados. La energía cinética solo se conserva cuando e=1.',{m1:2,m2:1,v1:3,v2:-1,e:1,t:0},[s('m1','Masa del carro azul',.5,5,.5,'kg'),s('m2','Masa del carro coral',.5,5,.5,'kg'),s('v1','Velocidad inicial azul',-4,4,.1,'m/s'),s('v2','Velocidad inicial coral',-4,4,.1,'m/s'),s('e','Restitución',0,1,.05),time()],p=>{const v=M.collision(p);return `p antes = ${fmt(v.momentum)} kg·m/s · p después = ${fmt(v.pAfter)} kg·m/s · v₁ final = ${fmt(v.u1)} m/s · v₂ final = ${fmt(v.u2)} m/s · energía perdida = ${fmt(v.lost)} J. ${Number.isFinite(v.tc)?'Choque en t = '+fmt(v.tc)+' s.':'No se acercan: no hay choque en el futuro.'}`;},[
 q('El balance antes del choque','m₁=2 kg, v₁=3 m/s, m₂=1 kg, v₂=−1 m/s. Calcula el momento total.',{},5,'2·3+1·(−1)=5 kg·m/s. El sentido de la velocidad cuenta.','Suma los productos conservando el signo.',{unit:'kg·m/s'}),
 q('Detén el centro de masas','Con m₁=2, m₂=1 y v₂=−1, ajusta v₁ para que el momento total sea cero.',{v1:3},0,'v₁=0,5 m/s hace 2·0,5−1=0.','El producto de la masa azul por su velocidad debe compensar al otro.',tune(['v1'],p=>M.collision(p).momentum,{v1:.5})),
 q('Se quedan unidos','Si e=0, ¿se conserva la energía cinética de un choque con velocidades iniciales distintas?',{e:0},'no','El momento se conserva, pero parte de la energía cinética pasa a energía interna.','Conservación del momento no implica conservación de K.',choice([['no','No; disminuye'],['yes','Sí, siempre'],['gain','Aumenta']])),
 q('Un encuentro simétrico','Dos masas de 1 kg viajan a +2 y −2 m/s y se pegan. ¿Cuál es la velocidad final?',{m1:1,m2:1,v1:2,v2:-2,e:0},0,'El momento total es cero y la masa conjunta es 2 kg: velocidad final cero.','Divide el momento inicial entre la masa total.',{unit:'m/s'})],{timeline:true}),
 'gravitational-potential-energy':lab('La altura se transforma en movimiento',['Elevadores','Explorar','Caída'],'Reproduce una caída ideal desde H. Las barras muestran cómo la energía potencial se transforma en cinética.','Hasta el primer contacto con el suelo, U+K permanece constante. La animación se congela justo antes del impacto; no modela rebotes.',{m:2,g:10,H:5,t:0},[s('m','Masa',.5,10,.5,'kg'),s('g','Gravedad uniforme',1,20,.1,'m/s²'),s('H','Altura inicial',0,20,.5,'m'),time()],p=>{const v=M.potential(p);return `Altura = ${fmt(v.height)} m · U = ${fmt(v.U)} J · K = ${fmt(v.K)} J · total = ${fmt(v.total)} J. ${v.landed?'Estado límite inmediatamente anterior al impacto; caída terminada.':'Caída sin rozamiento.'}`;},[
 q('Sube una caja','Una caja de 2 kg se eleva 5 m con g=10 m/s². ¿Cuánta energía potencial gana?',{},100,'ΔU=mgΔh=2·10·5=100 J.','Multiplica masa, gravedad y cambio de altura.',{unit:'J'}),
 q('Una altura objetivo','Con m=2 y g=10, ajusta H para almacenar 200 J.',{H:5},200,'H=200/(2·10)=10 m.','La altura se mide desde el nivel de referencia.',tune(['H'],p=>M.potential({...p,t:0}).U,{H:10},.1)),
 q('Cambia el nivel cero','Si cambias el nivel donde U=0, ¿cambia el trabajo entre dos alturas?',{},'no','El trabajo depende de diferencias de energía, no de una constante añadida a U.','Compara ΔU antes y después de cambiar la referencia.',choice([['no','No'],['yes','Sí, siempre'],['zero','Todo trabajo se anula']])),
 q('Cae sin rozamiento','Desde 5 m, con g=10, una masa de 2 kg alcanza el suelo. ¿Qué K tiene justo antes del impacto?',{t:1},100,'Los 100 J de energía potencial inicial se han convertido en cinética.','Usa conservación de U+K hasta el impacto.',{unit:'J'})],{timeline:true}),
 'gravitational-law':lab('Una órbita guiada por la gravedad',['Órbitas','Explorar','Energía orbital'],'Reproduce una órbita kepleriana elíptica y arrastra para girar el plano. La estrella ocupa un foco, no el centro.','La rapidez aumenta cerca de la estrella, pero la energía mecánica específica sigue constante. Masas planetarias despreciables frente a la estrella.',{M:1,a:1,e:.3,t:0},[s('M','Masa estelar',.5,3,.1,'M☉'),s('a','Semieje mayor',.3,3,.1,'ua'),s('e','Excentricidad',0,.8,.05),time('años')],p=>{const v=M.orbit(p);return `Distancia = ${fmt(v.r)} ua · aceleración = ${fmt(v.acceleration,5)} m/s² · rapidez = ${fmt(v.speed/1000)} km/s · periodo = ${fmt(v.period)} años · energía específica = ${fmt(v.energy/1e6)} MJ/kg. Un segundo de reproducción representa un año.`;},[
 q('Aleja dos masas','Sin cambiar las masas, duplicas la distancia. Si la fuerza inicial era 80 N, ¿cuál es ahora?',{},20,'F varía como 1/r²: 80/4=20 N.','El factor de distancia se eleva al cuadrado.',{unit:'N'}),
 q('Una órbita circular','Ajusta la excentricidad hasta que la distancia a la estrella sea constante.',{e:.5},0,'e=0 da una circunferencia; los dos focos coinciden.','Una órbita circular no tiene excentricidad.',tune(['e'],p=>p.e,{e:0},.001)),
 q('Aceleración de un planeta','Con la masa estelar y la distancia fijas, ¿depende la aceleración del planeta de su masa?',{},'no','F=GMm/r² y a=F/m eliminan m, en el modelo de masa de prueba.','Distingue fuerza de aceleración.',choice([['no','No, en este modelo'],['yes','Sí; es proporcional'],['inverse','Sí; es inversa']])),
 q('Cambia la fuente','Si duplicas la masa fuente manteniendo r, una fuerza de 12 N pasa a valer…',{M:2},24,'F es proporcional a la masa fuente.','El factor de masa no se eleva al cuadrado.',{unit:'N'})],{timeline:true}),
 'newton-second-law':lab('Diseña el impulso de una nave',['Rutas','Explorar','Trayectoria'],'Cambia una fuerza neta constante y sigue la trayectoria de una nave con velocidad inicial horizontal.','La fuerza fija la aceleración. La velocidad puede apuntar en otra dirección; fuerza nula conserva la velocidad inicial.',{m:2,F:4,angle:0,v0:1,t:0},[s('m','Masa',1,10,.5,'kg'),s('F','Fuerza neta',0,10,.1,'N'),s('angle','Dirección de fuerza',-180,180,1,'°'),s('v0','Velocidad inicial horizontal',-3,3,.1,'m/s'),time()],p=>{const v=M.newton(p);return `a = ${fmt(v.a)} m/s² · posición (${fmt(v.x)}, ${fmt(v.y)}) m · velocidad (${fmt(v.vx)}, ${fmt(v.vy)}) m/s. Fuerza neta constante, masa constante.`;},[
 q('La aceleración de salida','Una fuerza neta de 4 N actúa sobre 2 kg. Calcula la aceleración.',{},2,'a=F/m=4/2=2 m/s².','Divide la fuerza neta entre la masa.',{unit:'m/s²'}),
 q('Limita la aceleración','Con m=2 kg, ajusta F para obtener a=3 m/s².',{F:2},3,'F=ma=2·3=6 N.','La masa queda fija.',tune(['F'],p=>M.newton(p).a,{F:6})),
 q('Apaga el motor','Sin fuerza neta, una nave que ya se mueve en este modelo…',{F:0},'keeps','a=0 conserva v; no obliga a v=0.','La primera ley es el caso de fuerza neta nula.',choice([['keeps','Mantiene su velocidad'],['stops','Se detiene de inmediato'],['faster','Acelera sola']])),
 q('Un segundo de viaje','Desde reposo, a=2 m/s² y t=1 s. ¿Qué desplazamiento hay?',{v0:0,t:1},1,'Δx=½at²=1 m.','No confundas desplazamiento con velocidad.',{unit:'m'})],{timeline:true}),
 'polar-coordinates':lab('Encuentra la baliza del radar',['Balizas','Explorar','Cuadrantes'],'Arrastra la baliza. El radio mide distancia y el ángulo marca dirección desde el eje x positivo.','Compara la coordenada angular elegida con atan2(y,x), que conserva el cuadrante. En el origen la dirección no está definida.',{r:5,theta:0},[s('r','Radio',0,8,.1,'u'),s('theta','Ángulo',-180,360,1,'°')],p=>{const v=M.polar(p);return `x = ${fmt(v.x)} u · y = ${fmt(v.y)} u · r = ${fmt(p.r)} u · ${v.angle===null?'Origen: ángulo geométrico indefinido.':`atan2 = ${fmt(v.angle)}°`}. Los ángulos equivalentes difieren en vueltas completas.`;},[
 q('La baliza del este','Una baliza tiene r=5 y θ=0°. ¿Cuál es x?',{},5,'x=5·cos0°=5. Su coordenada y es cero.','El eje x positivo corresponde a cero grados.',{unit:'u'}),
 q('Gira al norte','Ajusta θ entre 0° y 180° hasta que y=5, con r=5.',{theta:30},90,'θ=90° coloca la baliza en (0,5).','Busca un seno igual a uno.',tune(['theta'],p=>p.theta,{theta:90},.5)),
 q('Una baliza en el centro','¿Tiene el origen una dirección polar única?',{r:0},'no','Todos los ángulos con r=0 representan (0,0). atan2 no aporta una dirección geométrica única.','La distancia cero no señala ningún rumbo.',choice([['no','No'],['north','Siempre norte'],['east','Siempre este']])),
 q('El oeste del radar','Con r=5 y θ=180°, calcula x.',{theta:180},-5,'cos180°=−1, luego x=−5.','Conserva el signo de la proyección.',{unit:'u'})]),
 'integration-by-parts':lab('Intercambia una integral por otra',['Intercambios','Explorar','Balance firmado'],'Elige una pareja u y v′ y mueve el límite superior. Comprueba integral original = término de borde − integral restante.','El área es firmada. Invertir los límites cambia el signo de las tres contribuciones, incluso cuando la curva no cambia.',{fn:'exp',a:0,b:1},[menu('fn','Integrando',[['exp','x·eˣ'],['cos','x·cos x'],['log','ln x']]),s('a','Límite inferior',0,3,.1),s('b','Límite superior',0,3,.1)],p=>{try{const v=M.parts(p);return `Borde = ${fmt(v.boundary,5)} · integral restante = ${fmt(v.remainder,5)} · integral original = ${fmt(v.value,5)}. El signo de la resta y los límites se conservan.`;}catch(e){return e.message;}},[
 q('Un producto exponencial','Calcula ∫ de 0 a 1 de x·eˣ dx. Usa u=x y v=eˣ.',{},1,'[xeˣ]₀¹−[eˣ]₀¹=e−(e−1)=1.','El término de borde y la integral restante comparten un e.'),
 q('Un intervalo vacío','Ajusta b para que el intervalo [a,b] con a=1 tenga integral cero.',{a:1,b:2},0,'Con b=a=1, los términos evaluados en ambos extremos se cancelan.','Haz coincidir los límites.',tune(['b'],p=>M.parts(p).value,{b:1})),
 q('Qué conviene derivar','Para ∫x·eˣ dx, ¿qué elección simplifica u al derivarlo?',{},'x','u=x tiene u′=1; v′=eˣ tiene una primitiva sencilla.','Busca un factor que se haga más simple al derivar.',choice([['x','u=x'],['exp','u=eˣ'],['both','Derivar ambos y omitir v']])),
 q('Límites al revés','Si ∫₀¹x·eˣ dx=1, ¿cuánto vale ∫₁⁰x·eˣ dx?',{a:1,b:0},-1,'Invertir los límites multiplica la integral por −1.','La región geométrica es la misma; cambia la orientación.')]),
 'newton-law-of-cooling-convection':lab('Controla la temperatura de una pieza',['Temperaturas','Explorar','Balance térmico'],'Reproduce enfriamiento o calentamiento en un ambiente fijo. Un segundo de reproducción representa un minuto del experimento.','El flujo positivo sale de la pieza. Si la pieza está más fría que el ambiente, la potencia es negativa y la pieza se calienta. Comprueba Biot antes de tratarla como uniforme.',{h:10,A:.2,C:1200,T0:80,ambient:20,t:0,L:.01,k:200},[s('h','Coeficiente convectivo',5,100,5,'W/(m²·K)'),s('A','Superficie',.1,1,.1,'m²'),s('C','Capacidad térmica',300,6000,300,'J/K'),s('T0','Temperatura inicial',0,100,1,'°C'),s('ambient','Temperatura ambiente',0,100,1,'°C'),time('min'),s('L','Longitud característica V/A',.001,.05,.001,'m'),s('k','Conductividad interna',.1,200,.1,'W/(m·K)')],p=>{const v=M.cooling(p);return `T = ${fmt(v.T)} °C · potencia saliente = ${fmt(v.power)} W · τ = ${fmt(v.tau/60)} min · Bi = ${fmt(v.Bi,4)}. ${v.Bi<.1?'Modelo uniforme compatible con Bi<0,1.':'Bi≥0,1: la temperatura uniforme no es una aproximación validada.'}`;},[
 q('La potencia de salida','h=10 W/(m²·K), A=0,2 m², Ts=80 °C y ambiente=20 °C. Calcula la potencia saliente.',{},120,'hAΔT=10·0,2·60=120 W. No es una cantidad de calor en julios.','Usa la diferencia de temperaturas.',{unit:'W'}),
 q('Duplica el intercambio','Ajusta h para que la potencia inicial sea 240 W con A y ΔT fijos.',{h:10},240,'h=20 W/(m²·K) duplica la potencia inicial.','La potencia es lineal en h.',tune(['h'],p=>M.cooling({...p,t:0}).power,{h:20},.1)),
 q('Una pieza fría','Con T0=10 °C y ambiente=20 °C, ¿qué signo tiene la potencia saliente?',{T0:10},'negative','T−T∞<0: el calor entra en la pieza y la potencia saliente es negativa.','El signo indica el sentido del calor.',choice([['negative','Negativo'],['zero','Cero'],['positive','Positivo']])),
 q('Un reloj térmico','Con C=1200 J/K, h=10 y A=0,2, calcula τ en segundos.',{},600,'τ=C/(hA)=1200/2=600 s, es decir 10 min.','La capacidad térmica divide a la conductancia térmica.',{unit:'s'})],{timeline:true}),
 'taylor-series':lab('Construye una curva desde un punto',['Aproximaciones','Explorar','Error'],'Cambia el centro y el grado. El polinomio comparte derivadas con la función en a; eso no garantiza precisión lejos de a.','Compara el error firmado y una cota de Lagrange. En ln(1+x), la singularidad x=−1 limita el intervalo abierto de convergencia.',{fn:'exp',a:1,n:1,x:1},[functionMenu,s('a','Centro a',-.5,2,.1),s('n','Grado N',0,12,1),s('x','Punto x',-.9,3,.1)],seriesRead,[
 q('Valor en el centro','El polinomio de Taylor de eˣ se centra en a=1. ¿Cuánto vale en x=1, con cualquier grado?',{},Math.E,'Todos los términos con x−a se anulan salvo f(a)=e.','Un polinomio de Taylor siempre coincide con f en el centro.'),
 q('Recupera el centro','Para eˣ centrada en a=1 y grado 1, ajusta x hasta que P(x)=e.',{x:2},Math.E,'P₁(x)=e+e(x−1); vuelve a valer e en x=1.','El factor x−a debe anularse.',tune(['x'],p=>M.series(p).polynomial,{x:1})),
 q('Una serie no es cualquier función lisa','¿Ser infinitamente derivable basta para igualar una función a su serie de Taylor?',{},'no','Hay funciones suaves no analíticas; debe comprobarse que el resto tiende a cero.','Distingue derivabilidad y analiticidad.',choice([['no','No'],['yes','Sí, siempre'],['finite','Solo hacen falta dos derivadas']])),
 q('Una tangente en cero','Para eˣ en a=0 y grado 1, calcula P₁(0,5).',{a:0,n:1,x:.5},1.5,'P₁(x)=1+x; P₁(0,5)=1,5. Es una aproximación, no e^0,5 exacto.','Usa valor y primera derivada en cero.')]),
 'maclaurin-series':lab('Empieza en cero y añade potencias',['Potencias','Explorar','Convergencia'],'Maclaurin fija a=0. Añade términos a eˣ, sin x o ln(1+x) y compara con la curva exacta.','Las barras muestran el signo y tamaño de cada término. Fuera del intervalo de convergencia, añadir grados no garantiza acercarse a la función.',{fn:'exp',a:0,n:2,x:1},[functionMenu,s('n','Grado N',0,12,1),s('x','Punto x',-.9,3,.1)],seriesRead,[
 q('Tres términos de eˣ','Con grado 2, P₂(x)=1+x+x²/2. Calcula P₂(1).',{},2.5,'1+1+1/2=2,5. e no se ha redondeado a ese valor: hay un resto.','Incluye el término constante.'),
 q('Un grado para tres términos','Ajusta N para que el polinomio de eˣ en x=1 valga 2,5.',{n:1},2.5,'Grado 2 usa los términos de orden 0, 1 y 2.','Grado y número de términos no son lo mismo.',tune(['n'],p=>M.series(p).polynomial,{n:2})),
 q('Un logaritmo fuera del círculo','Para ln(1+x) centrada en cero, ¿x=2 está dentro del intervalo abierto de convergencia?',{fn:'log',x:2},'no','La singularidad x=−1 fija radio 1. La función existe en 2, pero esta serie no converge allí.','Existencia de f y convergencia de su serie son preguntas distintas.',choice([['no','No'],['yes','Sí'],['undefined','La función no existe en 2']])),
 q('Una señal impar','Con sin x y grado 3, calcula P₃(1).',{fn:'sin',n:3,x:1},5/6,'P₃(x)=x−x³/6; en 1 da 5/6≈0,83.','Los términos pares del seno centrado en cero se anulan.')]),
 'euler-maclaurin-summation':lab('Corrige el borde de una suma',['Correcciones','Explorar','Residuos'],'Compara una suma discreta con su integral, los extremos y las correcciones B₂ y B₄.','Las correcciones usan derivadas en los extremos. El residuo tiene signo; más términos no garantizan una mejor aproximación para cualquier función e intervalo.',{fn:'square',a:1,b:4,order:0},[menu('fn','Sumandos',[['square','x²'],['exp','e⁻ˣ'],['log','ln x']]),s('a','Primer entero',1,10,1),s('b','Último entero',1,20,1),s('order','Correcciones derivadas',0,2,1)],p=>{try{const v=M.eulerMaclaurin(p);return `Suma exacta = ${fmt(v.sum,5)} · aproximación = ${fmt(v.approx,5)} · residuo = ${fmt(v.error,5)}. B₂/2! = 1/12; B₄/4! = −1/720.`;}catch(e){return e.message;}},[
 q('La suma de cuatro cuadrados','Calcula la suma de k² para k=1,2,3,4.',{},30,'1+4+9+16=30. La integral sola tiene un valor diferente.','Suma valores discretos; no áreas.'),
 q('Completa los bordes','Para esta suma de cuadrados, elige el mínimo número de correcciones derivadas que vuelve exacta la aproximación.',{order:0},1,'Con B₂ se obtiene 21+8,5+0,5=30. Las derivadas impares de orden ≥3 de x² son cero.','La primera corrección usa f′(4)−f′(1).',tune(['order'],p=>p.order,{order:1},.001)),
 q('Siempre más preciso','¿Añadir indefinidamente correcciones garantiza precisión creciente en toda aplicación?',{},'no','Euler–Maclaurin se usa también como desarrollo asintótico: el resto debe controlarse.','La fórmula con resto es la que justifica la aproximación.',choice([['no','No'],['yes','Sí, sin condiciones'],['none','Ninguna corrección puede ayudar']])),
 q('La primera corrección','Para f=x² entre 1 y 4, calcula [f′(4)−f′(1)]/12.',{},.5,'(8−2)/12=0,5.','La corrección no usa f(4)−f(1).')]),
 'bernoulli-equation':lab('Presión, velocidad y altura',['Conductos','Explorar','Cargas'],'Compara dos secciones de una conducción ideal. Los colores separan presión, energía cinética y altura.','Las barras expresan todas las energías por unidad de peso, en metros de carga. Una misma línea de corriente conserva la carga total.',flowDefaults,[...flowControls,time()],flowRead,[
 q('Una salida más estrecha','Q=0,01 m³/s y A₂=0,005 m². Calcula v₂.',{},2,'v₂=Q/A₂=2 m/s. La conservación de caudal acompaña a Bernoulli.','Divide caudal entre sección.',{unit:'m/s'}),
 q('Iguala las velocidades','Con A₁=0,01 m², ajusta A₂ para tener v₂=v₁.',{A2:.005},1,'A₂=0,01 m² conserva la misma velocidad en ambas secciones.','El caudal es el mismo.',tune(['A2'],p=>M.flow(p).v2,{A2:.01},.002)),
 q('Un estrechamiento horizontal ideal','Si aumenta la rapidez y no cambia la altura, la presión…',{},'falls','Para mantener p+½ρv² constante, p debe disminuir.','El término cinético gana energía por unidad de volumen.',choice([['falls','Disminuye'],['same','Permanece igual'],['rises','Aumenta']])),
 q('Carga de velocidad','Para v=2 m/s y g=9,81 m/s², calcula v²/(2g).',{},4/19.62,'La carga cinética es 4/19,62≈0,20 m.','El resultado es una longitud, no una presión.',{unit:'m'})],{timeline:true}),
 'bernoulli-equation-real-fluid':lab('Una conducción también disipa energía',['Bombas','Explorar','Balance de cargas'],'Añade una pérdida K·v₂²/(2g) y una bomba. Observa qué presión queda disponible aguas abajo.','Todas las alturas de carga están en metros. La bomba aporta energía y la pérdida la resta; ninguna se suma directamente a una presión en pascales.',{...flowDefaults,K:2,pump:0},[...flowControls,s('K','Coeficiente agregado de pérdida',0,10,.1),s('pump','Carga añadida por la bomba',0,10,.1,'m'),time()],flowRead,[
 q('Una pérdida con dimensiones','Con K=2 y v₂=2 m/s, calcula hL=Kv₂²/(2g), usando g=9,81.',{},8/19.62,'hL=8/19,62≈0,41 m de carga. Para convertir a Pa, multiplica por ρg.','K es adimensional; v²/g tiene unidad de longitud.',{unit:'m'}),
 q('Recupera el fluido ideal','Ajusta K para eliminar la pérdida, sin añadir carga de bomba.',{K:2},0,'K=0 recupera Bernoulli ideal, con los mismos datos y α=1.','La pérdida no puede ser negativa en este modelo pasivo.',tune(['K'],p=>M.flow(p).loss,{K:0},.0001)),
 q('Qué hace una bomba','Una bomba que aporta carga positiva al mismo caudal…',{},'adds','La bomba entrega energía mecánica al fluido. No elimina físicamente la fricción.','Distingue aporte y disipación.',choice([['adds','Aumenta la energía disponible'],['removes','Quita energía'],['mass','Crea masa de fluido']])),
 q('Carga a presión','Con ρ=1000 kg/m³ y g=9,81, convierte una pérdida de 1 m a kPa.',{},9.81,'ρghL=9810 Pa=9,81 kPa.','Un kPa contiene mil pascales.',{unit:'kPa'})],{timeline:true}),
 'continuity-equation':lab('La masa que entra debe salir',['Caudales','Explorar','Densidad'],'Reduce la sección y sigue dos estaciones de flujo estacionario. Conserva el caudal másico.','Con densidades distintas, se conserva ρAv, pero el caudal volumétrico Av puede cambiar. Es un balance de dos estados; no una ecuación de estado del gas.',{A1:.01,A2:.005,v1:1,rho1:1000,rho2:1000,t:0},[s('A1','Sección de entrada',.002,.02,.001,'m²'),s('A2','Sección de salida',.002,.02,.001,'m²'),s('v1','Velocidad de entrada',.2,3,.1,'m/s'),s('rho1','Densidad de entrada',100,1200,100,'kg/m³'),s('rho2','Densidad de salida',100,1200,100,'kg/m³'),time()],p=>{const v=M.continuity(p);return `v₂ = ${fmt(v.v2)} m/s · caudal másico = ${fmt(v.mass)} kg/s · Q₁ = ${fmt(v.Q1*1000)} L/s · Q₂ = ${fmt(v.Q2*1000)} L/s. ${p.rho1===p.rho2?'Densidad constante: Q₁=Q₂.':'Densidades distintas: se conserva masa, no necesariamente volumen.'}`;},[
 q('El agua acelera','A₁=0,01 m², A₂=0,005 m² y v₁=1 m/s, con densidad constante. Calcula v₂.',{},2,'A₁v₁=A₂v₂ da v₂=2 m/s.','El área de salida es la mitad.',{unit:'m/s'}),
 q('Iguala el flujo local','Ajusta A₂ para que v₂=1 m/s, manteniendo densidades iguales.',{},1,'A₂=A₁=0,01 m² permite igual velocidad.','El caudal debe atravesar ambas estaciones.',tune(['A2'],p=>M.continuity(p).v2,{A2:.01},.002)),
 q('Un fluido menos denso','A sección fija y flujo másico fijo, si la densidad de salida baja, su velocidad…',{rho2:500},'rises','v=ṁ/(ρA): una densidad menor exige más velocidad para transportar la misma masa.','El producto ρAv debe seguir igual.',choice([['rises','Aumenta'],['same','No cambia'],['falls','Disminuye']])),
 q('Masa por segundo','Con ρ=1000, A=0,01 y v=1, calcula ṁ.',{},10,'ṁ=ρAv=10 kg/s. No son 10 m³/s.','Multiplica densidad por caudal volumétrico.',{unit:'kg/s'})],{timeline:true}),
 'capacitor-stored-energy':lab('Carga, guarda y descarga',['Cargas','Explorar','Circuito RC'],'Reproduce la carga de un condensador ideal a través de una resistencia. Un segundo de reproducción representa un milisegundo del circuito.','En carga, separa energía suministrada, almacenada y disipada. En descarga, la energía inicial se transforma en calor de la resistencia.',{C:10,V:4,R:1,t:0,kind:'charge'},[s('C','Capacitancia',1,20,1,'µF'),s('V','Tensión de la fuente o inicial',0,10,.1,'V'),s('R','Resistencia',.1,2,.1,'kΩ'),menu('kind','Proceso',[['charge','Carga desde cero'],['discharge','Descarga desde V inicial']]),time('ms')],p=>{const v=M.capacitor(p);return `Vcond = ${fmt(v.voltage)} V · Q = ${fmt(v.Q)} µC · U = ${fmt(v.U)} µJ · calor = ${fmt(v.heat)} µJ · energía suministrada = ${fmt(v.source)} µJ · τ = ${fmt(v.tau)} ms.`;},[
 q('La energía de un condensador','C=10 µF y V=4 V. Calcula la energía cuando está cargado a esa tensión.',{},80,'U=½·10·4²=80 µJ. La conversión de µF conserva el prefijo µ en julios.','La tensión está al cuadrado.',{unit:'µJ'}),
 q('Una reserva de energía','Con C=10 µF, ajusta V para almacenar 125 µJ al alcanzar esa tensión.',{V:2},125,'½·10·V²=125 da V=5 V.','Despeja la raíz positiva de la tensión.',tune(['V'],p=>.5*p.C*p.V*p.V,{V:5},.1)),
 q('Carga con una resistencia','Al completar una carga ideal desde cero a tensión fija, ¿toda la energía suministrada queda almacenada?',{},'no','La mitad queda en el condensador y la otra mitad se disipa en R, en este circuito RC ideal.','Compara energía de la fuente y U final.',choice([['no','No; hay calor en R'],['yes','Sí, toda'],['none','No se almacena energía']])),
 q('Duplica la tensión','Un condensador guarda 80 µJ a 4 V. ¿Cuánto guarda a 8 V?',{V:8},320,'Duplicar V multiplica U por cuatro.','C se mantiene constante.',{unit:'µJ'})],{timeline:true}),
 'one-dimensional-wave-equation':lab('Una señal viaja; el medio oscila',['Señales','Explorar','Interferencia'],'Reproduce una onda viajera. La marca azul es un punto fijo del medio: sube y baja sin viajar con la cresta.','Compara una onda viajera con una onda estacionaria, resultado de dos ondas opuestas de igual amplitud A/2.',{A:1,c:2,lambda:4,t:0,kind:'travel'},[s('A','Amplitud máxima',0,2,.1,'u'),s('c','Rapidez de propagación',.5,4,.1,'m/s'),s('lambda','Longitud de onda',1,8,.1,'m'),menu('kind','Señal',[['travel','Viajera'],['standing','Estacionaria']]),time()],p=>{const v=M.wave1D(p,1);return `A = ${fmt(p.A)} u · f = ${fmt(v.frequency)} Hz · periodo = ${fmt(v.period)} s · velocidad vertical en x=1 m = ${fmt(Math.abs(v.velocity)<1e-10?0:v.velocity)} u/s. La rapidez c describe propagación, no el movimiento vertical del medio.`;},[
 q('Cuántas crestas por segundo','c=2 m/s y λ=4 m. Calcula la frecuencia.',{},.5,'f=c/λ=0,5 Hz.','Divide rapidez entre longitud de onda.',{unit:'Hz'}),
 q('Sintoniza un hercio','Con c=2 m/s, ajusta λ para producir f=1 Hz.',{lambda:4},1,'λ=c/f=2 m.','Una longitud menor produce más oscilaciones por segundo.',tune(['lambda'],p=>M.wave1D(p,0).frequency,{lambda:2},.005)),
 q('Qué viaja con la cresta','En esta onda transversal ideal, una partícula del medio…',{},'vertical','La partícula oscila verticalmente alrededor de una posición fija; la forma se propaga.','Distingue el medio y la señal.',choice([['vertical','Oscila sin viajar con la cresta'],['travels','Viaja a c con la cresta'],['still','Nunca se mueve']])),
 q('El reloj de una onda','Con f=0,5 Hz, calcula el periodo.',{},2,'T=1/f=2 s.','El periodo es tiempo por oscilación.',{unit:'s'})],{timeline:true,demoParams:p=>({...p,kind:'standing'})}),
 'wave-equation':lab('Explora una membrana en tres dimensiones',['Resonancias','Explorar','Membrana 3D'],'Gira la membrana con ratón, tacto o flechas. Cambia m y n para descubrir líneas nodales y frecuencias propias.','Los bordes permanecen fijos. La altura es un desplazamiento amplificado para verlo; el modelo es lineal y describe pequeñas oscilaciones.',{A:.1,c:2,Lx:2,Ly:2,m:1,n:1,t:0},[s('A','Amplitud',0,.2,.01,'m'),s('c','Rapidez de onda',.5,4,.1,'m/s'),s('Lx','Lado Lx',1,4,.1,'m'),s('Ly','Lado Ly',1,4,.1,'m'),s('m','Modo horizontal m',1,5,1),s('n','Modo vertical n',1,5,1),time()],p=>{const v=M.membrane(p);return `A = ${fmt(p.A)} m · frecuencia = ${fmt(v.frequency)} Hz · líneas nodales interiores = ${v.nodes} · modo (${p.m}, ${p.n}). Bordes fijos. Gira el dibujo; amplificación vertical ×4.`;},[
 q('La frecuencia fundamental','Lx=Ly=2 m, c=2 m/s y m=n=1. Calcula f=(c/2)√[(m/Lx)²+(n/Ly)²].',{},Math.SQRT1_2,'f=√(1/4+1/4)=√0,5≈0,71 Hz.','Calcula los dos cocientes antes de la raíz.',{unit:'Hz'}),
 q('Una línea interior','Con n=1, ajusta m para obtener exactamente una línea nodal interior.',{m:1},1,'m=2 genera una línea x=Lx/2. Los bordes no cuentan como líneas interiores.','El número total es (m−1)+(n−1).',tune(['m'],p=>M.membrane(p).nodes,{m:2},.001)),
 q('Los bordes de la membrana','En este modelo sujeto al marco, el desplazamiento del borde…',{},'zero','Los factores seno se anulan en x=0,Lx y y=0,Ly.','Las condiciones de contorno forman parte del problema.',choice([['zero','Siempre es cero'],['free','Es libre'],['max','Siempre es máximo']])),
 q('Cuenta las líneas quietas','En el modo (m,n)=(3,2), ¿cuántas líneas nodales interiores hay?',{m:3,n:2},3,'Hay 2 líneas en x y 1 en y: en total 3.','No cuentes los bordes fijos.')],{timeline:true}),
 'euler-identity':lab('Una exponencial dibuja una vuelta',['Giros','Explorar','Componentes'],'Arrastra el punto sobre el círculo unitario. La coordenada horizontal es cos θ y la vertical es sin θ.','Las componentes de e^(iθ) también son señales periódicas. θ se convierte a radianes antes de evaluarse; el módulo siempre es uno.',{theta:180},[s('theta','Fase',-360,720,1,'°')],p=>{const v=M.complex(p);return `θ = ${fmt(v.angle,5)} rad · parte real = ${fmt(v.re,5)} · parte imaginaria = ${fmt(v.im,5)} · |e^(iθ)| = 1. ${p.theta%360===180||p.theta%360===-180?'Media vuelta: e^(iπ)+1=0.':''}`;},[
 q('La media vuelta de Euler','¿Cuál es la parte real de e^(iπ)?',{},-1,'cosπ=−1 y sinπ=0, luego e^(iπ)=−1.','Busca el punto opuesto a 1.'),
 q('Un cuarto de vuelta','Ajusta θ entre 0° y 180° para llegar al punto i.',{theta:30},90,'θ=90° corresponde a π/2 rad: real 0, imaginaria 1.','El punto i está arriba.',tune(['theta'],p=>p.theta,{theta:90},.5)),
 q('La unidad imaginaria','¿Cuánto vale i²?',{},'minus','i²=−1 define la unidad imaginaria. No es un número real de módulo negativo.','Multiplicar dos veces por i gira media vuelta.',choice([['minus','−1'],['one','1'],['zero','0']])),
 q('Una vuelta completa','¿Cuál es la parte real de e^(i2π)?',{theta:360},1,'cos2π=1 y sin2π=0: el punto vuelve al inicio.','Una vuelta no cambia el módulo.')]),
 'euler-bernoulli-beam-bending':lab('Diseña una ménsula que flexione menos',['Ménsulas','Explorar','Momento y pendiente'],'Compara una carga en el extremo con una carga distribuida uniforme. La curva amplifica el desplazamiento y conserva el empotramiento.','La rigidez EI controla la curvatura. Lee la flecha real en milímetros y separa esa medida de la amplificación gráfica. No se comprueba resistencia ni pandeo.',{P:100,L:2,E:200,I:100,kind:'tip'},[s('P','Carga P (extremo) o q (uniforme)',0,500,10,'N o N/m'),s('L','Longitud',.5,4,.1,'m'),s('E','Módulo de Young',20,250,10,'GPa'),s('I','Segundo momento de área',10,500,10,'cm⁴'),menu('kind','Carga',[['tip','P en el extremo [N]'],['uniform','q uniforme [N/m]']])],p=>{const v=M.beam(p);return `Flecha = ${fmt(v.tip*1000)} mm · EI = ${fmt(v.rigidity)} N·m² · carga total = ${fmt(v.load)} N. ${v.small?'Desplazamiento pequeño frente a L.':'δ/L≥0,05: la hipótesis de pequeña deformación merece revisión.'} Amplificación gráfica indicada en el dibujo.`;},[
 q('La flecha de una ménsula','P=100 N, L=2 m, E=200 GPa e I=100 cm⁴. Calcula δ en mm.',{},4/3,'EI=200000 N·m²; δ=100·8/(3·200000) m≈1,33 mm.','1 cm⁴=10⁻⁸ m⁴; convierte al final a mm.',{unit:'mm'}),
 q('Refuerza la sección','Ajusta I para reducir a la mitad la flecha inicial, manteniendo P,L,E.',{I:100},2/3,'Duplicar I a 200 cm⁴ reduce δ a unos 0,67 mm.','La flecha es inversa a I.',tune(['I'],p=>M.beam(p).tip*1000,{I:200},.005)),
 q('Alarga la ménsula','Para la misma carga en el extremo, si duplicas L, la flecha…',{},'eight','δ=PL³/(3EI): duplicar L multiplica la flecha por 8. La carga uniforme tiene otra ley.','Fíjate en la potencia de L del caso elegido.',choice([['eight','Se multiplica por 8'],['two','Se duplica'],['four','Se multiplica por 4']])),
 q('El momento en el apoyo','Con P=100 N y L=2 m, calcula la magnitud del momento en el empotramiento.',{},200,'La magnitud es PL=200 N·m. El extremo libre tiene momento cero.','Multiplica fuerza por brazo.',{unit:'N·m'})])
};
const beamLab=FRONTIER_LABS['euler-bernoulli-beam-bending'];
beamLab.defaults.station=.5;
beamLab.demoControls=[...beamLab.controls,s('station','Sección x/L',0,1,.01)];
beamLab.demoRead=p=>{const x=p.station*p.L,z=M.beam(p,x);return `Sección x = ${fmt(x)} m · momento = ${fmt(z.moment)} N·m · pendiente w′ = ${fmt(z.slope,5)} · flecha del extremo = ${fmt(z.tip*1000)} mm. La tangente usa la escala amplificada de la elástica; el momento tiene escala propia.`;};
