import * as M from './horizon-math.js';
import {fmt} from './learning-math.js';
export function drawHorizon(ctx,w,h,id,p,v){
 const blue=v.accent,coral='#ca6c51',green='#558b69',ink=v.ink,muted=v.muted,line=v.line,mode=v.mode;
 ctx.fillStyle=v.background;ctx.fillRect(0,0,w,h);
 const path=(pts,color=blue,width=2,fill=false)=>{ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(fill){ctx.closePath();ctx.fillStyle=color;ctx.fill();}else{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}};
 const text=(s,x,y,color=ink,size=12)=>{ctx.fillStyle=color;ctx.font=`${size}px system-ui`;ctx.textAlign='center';ctx.fillText(s,x,y);};
 const dot=(q,color=blue,r=5)=>{ctx.beginPath();ctx.arc(q[0],q[1],r,0,2*Math.PI);ctx.fillStyle=color;ctx.fill();};
 const arrow=(a,b,color=blue)=>{if(Math.hypot(b[0]-a[0],b[1]-a[1])<1)return;path([a,b],color);const t=Math.atan2(b[1]-a[1],b[0]-a[0]);path([[b[0]-7*Math.cos(t-.5),b[1]-7*Math.sin(t-.5)],b,[b[0]-7*Math.cos(t+.5),b[1]-7*Math.sin(t+.5)]],color);};
 const heading=(a,b)=>{text(a,w/2,22,blue,w<500?11:14);text(b,w/2,h-12,muted,w<500?10:12);};
 const plot=(xmin,xmax,ymin,ymax)=>{const left=38,right=w-25,top=42,bottom=h-37,point=(x,y)=>[left+(x-xmin)/(xmax-xmin)*(right-left),bottom-(y-ymin)/(ymax-ymin)*(bottom-top)];path([[left,top],[left,bottom],[right,bottom]],line,1);if(ymin<0&&ymax>0)path([point(xmin,0),point(xmax,0)],line,1);text(fmt(xmin),left,bottom+14,muted,10);text(fmt(xmax),right,bottom+14,muted,10);text(fmt(ymax),left,top-8,muted,10);text(fmt(ymin),left,bottom-5,muted,10);const curve=(f,color=blue)=>{let pts=[];for(let i=0;i<=180;i++){const x=xmin+(xmax-xmin)*i/180,y=f(x);if(Number.isFinite(y)&&y>=ymin&&y<=ymax)pts.push(point(x,y));else{if(pts.length>1)path(pts,color);pts=[];}}if(pts.length>1)path(pts,color);};return {point,curve,unpoint:q=>[xmin+(q[0]-left)/(right-left)*(xmax-xmin),ymin+(bottom-q[1])/(bottom-top)*(ymax-ymin)],layout:{xmin,xmax,ymin,ymax,left,right,top,bottom}};};
 const bars=(vals,labels,colors=[blue,coral,green])=>{const max=Math.max(1e-6,...vals.map(Math.abs)),bottom=h-44,top=48,zero=vals.some(x=>x<0)?(bottom+top)/2:bottom,scale=(bottom-top)/(vals.some(x=>x<0)?2:1)/max;path([[25,zero],[w-25,zero]],line,1);vals.forEach((x,j)=>{const cx=(j+.5)*w/vals.length,bw=Math.min(55,w/vals.length*.55),y=zero-x*scale;ctx.fillStyle=colors[j%colors.length]+'55';ctx.fillRect(cx-bw/2,Math.min(y,zero),bw,Math.abs(zero-y));path([[cx-bw/2,y],[cx+bw/2,y]],colors[j%colors.length]);text(labels[j],cx,bottom+14,muted,10);if(!v.hide&&vals.length<10)text(fmt(x),cx,top-10,colors[j%colors.length],11);});};
 const project=points=>{const cy=Math.cos(v.yaw),sy=Math.sin(v.yaw),sp=Math.sin(v.pitch),cp=Math.cos(v.pitch),raw=([x,y,z])=>[cy*x-sy*y,sp*(sy*x+cy*y)-cp*z],rs=points.map(raw),dx=Math.max(.1,...rs.map(q=>Math.abs(q[0]))),dy=Math.max(.1,...rs.map(q=>Math.abs(q[1]))),scale=Math.min((w-85)/2/dx,(h-110)/2/dy);return q=>{const [x,y]=raw(q);return [w/2+x*scale,h/2+y*scale];};};
 const surface=(f,limit=1)=>{const n=20,rows=Array.from({length:n+1},(_,i)=>Array.from({length:n+1},(_,j)=>{const x=-limit+2*limit*i/n,y=-limit+2*limit*j/n;return [x,y,f(x,y)];})),flat=rows.flat(),P=project(flat);for(const row of rows)path(row.map(P),blue,1);for(let j=0;j<=n;j++)path(rows.map(row=>P(row[j])),coral,1);return {rotate:true};};
 if(id==='cramers-rule'){const c=M.cramer(p);if(mode===2){const g=plot(-4,4,-4,4),O=g.point(0,0),A=g.point(p.a,p.b),B=g.point(1,1),sum=g.point(p.a+1,p.b+1);path([O,A,sum,B],(c.D>=0?blue:coral)+'33',1,true);arrow(O,A,blue);arrow(O,B,coral);heading('Columnas de la matriz · área orientada',Math.abs(c.D)<1e-10?'Área cero: columnas dependientes':'El signo de a−b fija la orientación');return {};}const g=plot(-5,5,-8,8);g.curve(x=>p.c-p.a*x,blue);g.curve(x=>p.d-p.b*x,coral);if(c.x!==null&&Math.abs(c.x)<=5&&Math.abs(c.y)<=8)dot(g.point(c.x,c.y),green);heading(mode===2?`D = ${v.hide?'?':fmt(c.D)} · orientación y cruce`:'a·x+y=c azul · b·x+y=d coral',c.kind==='única'?'Mueve los términos y sigue la intersección':`Rectas ${c.kind}; Cramer no divide por cero`);return {};}
 if(id==='continuity-equation-fluid'){const m=M.mass(p);if(mode===2){const g=plot(-2,2,-2,2);for(let x=-1.5;x<=1.5;x+=.5)for(let y=-1.5;y<=1.5;y+=.5)arrow(g.point(x,y),g.point(x+p.ax*x*.14,y+p.ay*y*.14));heading('Campo lineal de velocidad · flechas a escala','Expansión + contracción: suma las dos derivadas');}else{const g=plot(0,20,0,Math.max(200,p.initial+20*Math.max(0,m.rate)));g.curve(t=>p.initial+m.rate*t);dot(g.point(p.t,m.value),coral);heading('Masa del depósito · kg frente a segundos','Azul: balance integrado · coral: instante elegido');}return {};}
 if(id==='euler-lagrange'){const a=M.action(p);if(mode===2){const g=plot(-2,2,-12,30);g.curve(x=>M.action({...p,a:x}).S);dot(g.point(p.a,a.S),coral);heading('Acción S frente a amplitud a','El signo de mπ²−k determina la curvatura');}else{const g=plot(0,1,-2.1,2.1);g.curve(a.path);g.curve(()=>0,green);heading('Trayectoria variada azul · solución q=0 verde','Extremos fijos · duración 1 s · acción T−V');}return {};}
 if(id==='euler-fluid-equation'){if(mode===2){const q=M.euler(p);bars([q.local,q.convective,q.acc],['Local','Convectiva','Material']);heading('Dos contribuciones a Du/Dt en x=1 m','Las aceleraciones usan m/s²');}else{const g=plot(-2,2,-5,5);g.curve(x=>p.a*x,blue);g.curve(x=>M.euler(p,x).acc,coral);heading('Azul: u(x,0) · coral: aceleración material','Escala numérica compartida · unidades distintas indicadas');}return {};}
 if(id==='bayes-theorem'){const b=M.bayes(p);if(mode===1){bars([b.tp,b.fp,1-b.evidence],['Aviso correcto','Aviso falso','Sin aviso']);heading('Fracciones esperadas de toda la población','La posterior compara solo los dos grupos de aviso');}else{const columns=w<500?25:40,rows=1000/columns,spacing=Math.min((w-50)/columns,(h-85)/rows),ox=(w-columns*spacing)/2,oy=43;for(let j=0;j<1000;j++){const color=j<1000*b.tp?blue:j<1000*b.evidence?coral:line;ctx.fillStyle=color;ctx.fillRect(ox+j%columns*spacing,oy+Math.floor(j/columns)*spacing,Math.max(1,spacing-1.5),Math.max(1,spacing-1.5));}heading('1000 piezas · azul: aviso correcto · coral: falso','Frecuencias esperadas, redondeadas al dibujar; no son ensayos reales');}return {};}
 if(id==='multiclass-bayes-theorem'){const b=M.multiclass(p);if(!b.posterior){heading('No se puede condicionar una evidencia imposible','Da peso a una clase y probabilidad positiva a la evidencia');return {};}bars(mode===1?b.weights:mode===2?b.prior:b.posterior,['Máquina A','Máquina B','Máquina C']);heading(mode===1?'Pesos conjuntos P(clase)·P(marca|clase)':mode===2?'Probabilidades previas':'Probabilidades después de observar la marca','Las alturas se reescalan; los valores exactos figuran debajo');return {};}
 if(id==='cross-product'){const q=M.vector(p),opposite=q.C.map(x=>-x),points=[[0,0,0],q.A,q.B,q.A.map((x,i)=>x+q.B[i]),q.C],P=project([...points,opposite,[-1,-1,-1],[1,1,1]]);path([P(points[0]),P(q.A),P(points[3]),P(q.B)],blue+'22',1,true);for(let i=0;i<3;i++){const axis=[0,0,0];axis[i]=2;arrow(P([0,0,0]),P(axis),line);text(['x','y','z'][i],...P(axis),muted,10);}arrow(P(points[0]),P(q.A),blue);arrow(P(points[0]),P(q.B),coral);arrow(P(points[0]),P(q.C),green);if(mode===2)arrow(P(points[0]),P(opposite),muted);heading(mode===2?'a×b verde · b×a gris: dos orientaciones':'a azul · b coral · a×b verde','Arrastra para girar · área = longitud de la normal');return {rotate:true};}
 if(id==='spherical-heron-formula'){const s=M.sphere(p);if(!s.valid){heading('Lados incompatibles con este triángulo','Ajusta las tres longitudes angulares');return {};}if(mode===2){const sides=[p.a,p.b,p.c].map(x=>x*Math.PI/180),angles=sides.map((a,i)=>{const b=sides[(i+1)%3],c=sides[(i+2)%3];return Math.acos(M.clamp((Math.cos(a)-Math.cos(b)*Math.cos(c))/(Math.sin(b)*Math.sin(c)),-1,1))*180/Math.PI;});bars(angles,['Ángulo α','Ángulo β','Ángulo γ']);heading('Ángulos interiores en grados','Suma = 180° + exceso · no son los ángulos centrales de los lados');return {};}const grid=[];for(let j=0;j<=12;j++){const lat=-Math.PI/2+j*Math.PI/12;grid.push(Array.from({length:65},(_,i)=>{const a=2*Math.PI*i/64;return [Math.cos(lat)*Math.cos(a),Math.cos(lat)*Math.sin(a),Math.sin(lat)];}));}const P=project(grid.flat());grid.forEach(q=>path(q.map(P),line,1));for(let i=0;i<3;i++){const a=s.vertices[i],b=s.vertices[(i+1)%3],angle=Math.acos(M.clamp(M.dot(a,b),-1,1)),arc=Array.from({length:41},(_,j)=>a.map((x,k)=>(Math.sin((1-j/40)*angle)*x+Math.sin(j/40*angle)*b[k])/Math.sin(angle)));path(arc.map(P),[blue,coral,green][i],3);dot(P(a),blue);}heading('Arcos de círculos máximos · esfera de radio R','Gira para ver los tres lados · área física en m²');return {rotate:true};}
 if(id==='laplace-transform'){const a=M.laplace(p),ymax=Math.max(1,Math.exp(Math.min(8,Math.max(0,p.a-p.s)*p.T))),g=plot(0,p.T,0,ymax*1.05);g.curve(a.weighted);if(mode===2){const pts=[g.point(0,0),...Array.from({length:100},(_,j)=>g.point(p.T*j/99,a.weighted(p.T*j/99))),g.point(p.T,0)];path(pts,blue+'22',1,true);}heading('Integrando e^(−st)·f(t) frente al tiempo',a.valid?'Cola decreciente: s>a':'s≤a: divergente; altura gráfica recortada si supera exp(8)');return {};}
 if(['coulomb-law','coulomb-point-charge-field','electric-scalar-potential'].includes(id)){const q=M.electric(p);if(id==='electric-scalar-potential'&&mode===2){heading('Potencial sobre el plano · centro excluido r<0,2 m','Altura V/10 y recorte ±3 para visualización; valor real abajo');return surface((x,y)=>Math.hypot(x,y)<.2?0:M.clamp(M.COULOMB*p.q*1e-9/Math.hypot(x,y)/10,-3,3),3);}const g=plot(-3,3,-3,3);for(let x=-2.5;x<=2.5;x+=.5)for(let y=-2.5;y<=2.5;y+=.5){const r=Math.hypot(x,y);if(r<.4||p.q===0)continue;const len=Math.min(.35,.3/r**2),sign=Math.sign(p.q);arrow(g.point(x,y),g.point(x+sign*x/r*len,y+sign*y/r*len),line);}dot(g.point(0,0),p.q>=0?coral:blue,7);dot(g.point(p.x,p.y),green,7);if(q.valid&&p.q!==0){const sign=Math.sign(id==='coulomb-law'?q.F:q.E);arrow(g.point(p.x,p.y),g.point(p.x+sign*p.x/q.r*.55,p.y+sign*p.y/q.r*.55),id==='coulomb-law'?coral:blue);}heading('Sonda verde · carga fuente en el origen','Arrastra la sonda · flechas de fondo comprimidas para ser legibles');return {layout:g.layout,drag:xy=>{const [x,y]=g.unpoint(xy);return {x,y};}};}
 if(id==='lagrange-interpolation'){const g=plot(-2,2,-6,6);if(mode===2)for(let i=0;i<3;i++)g.curve(x=>M.lagrange(p,x).basis[i],[blue,coral,green][i]);else g.curve(x=>M.lagrange(p,x).value);for(const [x,y] of M.lagrange(p).nodes)dot(g.point(x,y),coral,7);heading(mode===2?'Tres bases cardinales: una por nodo':'Polinomio interpolador · nodos móviles verticales','Abscisas fijas −1,0,1 · arrastra la altura del nodo más cercano');return {layout:g.layout,drag:xy=>{const [x,y]=g.unpoint(xy),i=Math.round(M.clamp(x,-1,1))+1;return {['y'+i]:y};}};}
 if(id==='parseval-theorem'){const q=M.parseval(p);if(mode===2){bars(q.spectrum,q.spectrum.map((_,k)=>k%4===0?String(k):''));heading('|X[k]|²/N · índices de la DFT','Incluye k>N/2: frecuencias negativas discretas');}else{const g=plot(0,2*Math.PI,-6,6);g.curve(x=>M.signal(p,x));q.samples.forEach((y,i)=>dot(g.point(i*2*Math.PI/32,y),coral,2));heading('Señal periódica · 32 muestras','El espectro conserva la suma de cuadrados con factor 1/N');}return {};}
 if(id==='convolution'){const q=M.convolution(p);if(mode===2){const g=plot(0,p.a+p.b,-Math.max(1,Math.abs(p.A*p.B)*Math.min(p.a,p.b)),Math.max(1,Math.abs(p.A*p.B)*Math.min(p.a,p.b)));g.curve(t=>M.convolution(p,t).value);if(p.t<=p.a+p.b)dot(g.point(p.t,q.value),coral);heading('Resultado de convolución frente al desplazamiento t','La duración total del soporte es a+b');}else{const g=plot(-4,8,-2.2,2.2);g.curve(q.f,blue);g.curve(x=>q.g(p.t-x),coral);if(q.overlap>0)path([g.point(q.low,0),g.point(q.low,p.A*p.B/2),g.point(q.high,p.A*p.B/2),g.point(q.high,0)],green+'33',1,true);heading('f(τ) azul · g(t−τ) coral · solape verde','Desliza t y acumula el producto en la zona común');}return {};}
 if(id==='linear-transport-advection-equation'){const a=M.advect(p),g=plot(0,10,0,1.1);g.curve(a.exact);if(mode===2)path(a.u.map((y,i)=>g.point(i*a.dx,y)),coral);heading(mode===2?'Exacta azul · upwind coral':'Solución exacta φ₀(x−ct)','Dominio periódico: al salir por un lado reaparece por el otro');return {};}
 if(id==='ruffini-rule'){const r=M.ruffini(p);if(mode===2){const g=plot(-3,4,-30,30);g.curve(r.P);dot(g.point(p.r,r.remainder),coral);heading('Polinomio y evaluación P(r)','Un resto cero identifica un factor lineal');}else{const gap=w/5,x=i=>(i+1)*gap;for(let i=0;i<4;i++){text(fmt(r.coefficients[i]),x(i),h*.3,blue,16);text(i?`× ${fmt(p.r)}`:'Baja',x(i),h*.5,muted,12);text(v.hide?'?':fmt(r.synthetic[i]),x(i),h*.7,i===3?coral:green,16);}path([[gap*.6,h*.6],[w-15,h*.6]],line,1);heading('Coeficientes → multiplica → suma','Última entrada: resto · las tres anteriores: cociente');}return {};}
 if(id==='mean-squared-error'||id==='least-squares-regression'){const q=M.fit(p);if(mode===2&&id==='mean-squared-error'){bars(q.residuals.map(x=>x*x),['1','2','3','4','5']);heading('Cuadrados de los cinco residuos','MSE es la media de estas contribuciones, no la suma');return {};}const g=plot(-2.5,2.5,-6,11);g.curve(q.predict,blue);if(mode===2)g.curve(q.optimal,coral);for(const [x,y] of q.data){dot(g.point(x,y),green);path([g.point(x,y),g.point(x,q.predict(x))],coral,1);}heading('Datos verdes · tu recta azul · residuos coral','Arrastra para ajustar la ordenada · pendiente con su control');return {layout:g.layout,drag:xy=>{const [x,y]=g.unpoint(xy);return {intercept:y-p.slope*x};}};}
 if(id==='normal-distribution'||id==='gaussian-integral'){if(mode===2&&id==='gaussian-integral'){heading('Integrando de I²: exp(−a(x²+y²))','Altura adimensional · x,y en unidades de longitud');return surface((x,y)=>2*Math.exp(-p.a*(x*x+y*y)),2);}const normal=id==='normal-distribution',q=normal?M.normal(p):M.gauss(p),f=normal?q.density:q.curve,xmin=normal?p.mu-4*p.sigma:-4,xmax=normal?p.mu+4*p.sigma:4,ymax=(normal?q.peak:1)*1.15,g=plot(xmin,xmax,0,ymax);g.curve(f);const a=normal?Math.min(p.a,p.b):-p.b,b=normal?Math.max(p.a,p.b):p.b,lo=Math.max(a,xmin),hi=Math.min(b,xmax);if(lo<hi)path([g.point(lo,0),...Array.from({length:100},(_,i)=>g.point(lo+(hi-lo)*i/99,f(lo+(hi-lo)*i/99))),g.point(hi,0)],blue+'33',1,true);if(normal&&p.x>=xmin&&p.x<=xmax)dot(g.point(p.x,f(p.x)),coral);heading(normal?'Densidad y área del intervalo':'Integrando gaussiano · área de ventana',normal?'La parte fuera de la ventana del gráfico también cuenta en el cálculo':'Azul: intervalo finito · área total incluye las dos colas');return {};}
 if(id==='central-limit-theorem'){const c=M.central(p),g=plot(-4,4,0,1);c.bars.forEach(([x,y])=>{const half=1/(2*c.sd),left=Math.max(-4,x-half),right=Math.min(4,x+half);if(left<right)path([g.point(left,0),g.point(left,y),g.point(right,y),g.point(right,0)],blue+'66',1,true);});if(mode===2)g.curve(x=>M.pdf(x),coral);heading('Suma estandarizada · barras exactas con área uno','Normal coral en Aproximación · colas fuera del gráfico no se eliminan');return {};}
 if(id==='hyperbolic-tangent-activation'){const g=plot(-5,5,-3.2,3.2);g.curve(x=>M.activation(p,x).y,blue);if(mode===2)g.curve(x=>M.activation(p,x).gradient,coral);const a=M.activation(p);dot(g.point(p.x,a.y),green);heading(mode===2?'Activación azul · gradiente respecto a x coral':'tanh(w·x+b)','Arrastra el punto para cambiar la entrada x');return {layout:g.layout,drag:xy=>({x:g.unpoint(xy)[0]})};}
 if(id==='poisson-equation'){if(mode===2){heading('φ sobre el cuadrado · bordes fijos a cero','Gira la cámara · altura = potencial; fuente calculada');return surface((x,y)=>M.poisson(p,x,y).u);}const g=plot(-1,1,-1,1);for(let i=0;i<24;i++)for(let j=0;j<24;j++){const x=-1+2*i/24,y=-1+2*j/24,q=M.poisson(p,x,y),a=g.point(x,y+2/24),b=g.point(x+2/24,y),value=mode===1?q.source:q.u;ctx.fillStyle=(value>=0?blue:coral)+Math.round(40+180*Math.min(1,Math.abs(value)/(Math.max(.1,Math.abs(p.A))*(mode===1?4:1)))).toString(16).padStart(2,'0');ctx.fillRect(a[0],a[1],b[0]-a[0]+1,b[1]-a[1]+1);}heading(mode===1?'Mapa de fuente f=∇²φ':'Mapa del potencial φ','Azul positivo · coral negativo · intensidad según magnitud');return {};}
 if(id==='fourier-heat-conduction-1d-steady'){if(mode===2){const max=Math.max(1,Math.abs(M.conduction({...p,L:.2}).power)),g=plot(.2,2,-max*1.1,max*1.1);g.curve(L=>M.conduction({...p,L}).power);dot(g.point(p.L,M.conduction(p).power),coral);heading('Potencia W frente a espesor m','La curva 1/L muestra el efecto de aumentar resistencia');return {};}const g=plot(0,p.L,0,105);g.curve(x=>M.conduction(p,x).T);for(let j=1;j<=5;j++){const x=p.L*j/6,T=M.conduction(p,x).T,sign=Math.sign(p.hot-p.cold);if(sign)arrow(g.point(x,T-8),g.point(x+sign*p.L*.07,T-8),coral);}heading(mode===2?'Pendiente térmica y resistencia':'Temperatura estacionaria frente a posición','La pendiente es constante · las flechas indican el sentido del calor');return {};}
 if(id==='incompressible-navier-stokes-equation'){if(mode===2){heading('Vorticidad ωz sobre el plano periódico','Altura = vorticidad · solución de flujo 2D, sin singularidad');return surface((x,y)=>M.vortex(p,x,y).omega,Math.PI);}const g=plot(-Math.PI,Math.PI,-Math.PI,Math.PI);for(let i=0;i<22;i++)for(let j=0;j<22;j++){const x=-Math.PI+2*Math.PI*i/22,y=-Math.PI+2*Math.PI*j/22,q=M.vortex(p,x,y);arrow(g.point(x,y),g.point(x+q.u*.22,y+q.v*.22),q.omega>=0?blue:coral);}heading('Taylor–Green · azul/coral: signo de vorticidad','Flechas a escala fija · observa la disipación al reproducir');return {};}
 if(id==='heat-equation'){if(mode===2){heading('Temperatura: posición × tiempo','Eje x posición · eje y tiempo 0–20 s · altura ΔT/20');return surface((x,y)=>(M.heat(p,(x+1)*p.L/2,(y+1)*10).T-p.base)/20);}const g=plot(0,p.L,p.base-50,p.base+50);g.curve(x=>M.heat(p,x).T,blue);g.curve(x=>M.heat(p,x,0).T,coral);heading('Azul: ahora · coral: temperatura inicial','Bordes fijos · los detalles espaciales finos desaparecen antes');return {};}
 throw new Error('No hay representación para '+id);
}
