import {model} from './insight-math.js';
import {fmt} from './learning-math.js';
export const INSIGHT_LABS={};
const s=(key,label,min,max,step=.1,unit='')=>({key,label,min,max,step,unit}),time=()=>s('t','Reloj de exploración',0,20,.01);
export const show=x=>x===null?'indefinido':!Number.isFinite(x)?'fuera de rango':x!==0&&(Math.abs(x)<.001||Math.abs(x)>=1e6)?x.toExponential(4):fmt(x,4);
function add(id,title,modes,description,defaults,controls,label,unit,key,target,rule,correct,wrong,extra={}){
 const calc=p=>model(id,p),first=calc(defaults).value,changed=calc({...defaults,[key]:target}).value,spec=controls.find(c=>c.key===key);
 INSIGHT_LABS[id]={title,modes,description,demoDescription:description,defaults,controls,accent:'#397d91',animate:false,timeline:!!extra.timeline,
 read:p=>`${controls.map(c=>`${c.label}=${show(p[c.key])}${c.unit?' '+c.unit:''}`).join(' · ')}. ${label} = ${show(calc(p).value)} ${unit}. ${details(id,p,calc(p))}`,
 missions:[
 {title:extra.firstTitle||'Predice el resultado',story:`${extra.task||description} Calcula ${label.toLowerCase()} con los datos iniciales, en ${unit||'unidades adimensionales'}.`,answer:first,tolerance:.002,hint:rule,explanation:`${label}=${show(first)} ${unit}. ${rule}`,params:{}},
 {title:extra.tuneTitle||'Construye el escenario',kind:'tune',editable:[key],solution:{[key]:target},get:p=>calc(p).value,answer:changed,tolerance:.006,story:`Ajusta ${spec.label.toLowerCase()} hasta conseguir ${label.toLowerCase()}=${show(changed)} ${unit}.`,hint:`${rule} Conserva los demás datos y modifica solo ${spec.label.toLowerCase()}.`,explanation:`${spec.label}=${target} ${spec.unit||''}; ${label}=${show(changed)} ${unit}. ${rule}`,params:{}},
 {title:'Distingue las hipótesis',kind:'choice',story:extra.question||'¿Qué afirmación explica correctamente el modelo?',choices:[['yes',correct],['no',wrong]],answer:'yes',hint:rule,explanation:correct,params:{}},
 {title:extra.lastTitle||'Comprueba una segunda predicción',story:`Ahora ${spec.label.toLowerCase()}=${target} ${spec.unit||''}. Calcula ${label.toLowerCase()}, en ${unit||'unidades adimensionales'}, y justifica el cambio.`,answer:changed,tolerance:.002,hint:rule,explanation:`Resultado=${show(changed)} ${unit}. ${rule}`,params:{[key]:target}}
 ]};
}
function details(id,p,q){switch(id){
 case 'eigenvalues-eigenvectors':return q.complex?`No hay direcciones propias reales: λ=${show(q.real)}±${show(q.imag)}i. La cifra anterior es parte real, no un máximo complejo.`:`λ=${q.values.map(show).join(', ')}. ${q.defective?'Un solo eje propio independiente: matriz defectiva.':'Vectores de norma uno; el signo de cada vector es convencional.'}`;
 case 'principal-component-analysis-pca':return `Varianzas muestrales=${q.values.map(show).join(', ')}; error de reconstrucción normalizado con divisor n−1=${show(q.error)}. Ocho puntos centrados en 3D; datos sin estandarizar.`;
 case 'canonical-ensemble-partition-function':return `Z=${show(q.Z)}; P por nivel=${q.prob.map(show).join(', ')}; U=${show(q.U)} meV, C/kB=${show(q.C)}, S/kB=${show(q.entropy)}. El tercer nivel tiene ${p.degeneracy} microestados.`;
 case 'lorentz-transformations':return `ct′=${show(q.ct)} L; γ=${show(q.gamma)}; intervalo original=${show(q.interval)}, transformado=${show(q.transformed)} L². S′ se mueve a +βc respecto de S.`;
 case 'relativistic-velocity-addition':return `u/c=${show(q.u)} frente a suma galileana=${show(q.classical)}. u′ se mide en S′; S′ se mueve a +βc respecto de S. |u′/c|≤1; |β|<1.`;
 case 'relativistic-length-contraction':return `L0=${p.L0} m, L=${show(q.L)} m; γ=${show(q.gamma)}. Los extremos se miden simultáneamente en el sistema donde la barra se mueve; dibujo, no fotografía.`;
 case 'relativistic-time-dilation':return `Δt=${show(q.elapsed)} s para Δτ=${p.tau} s. Reloj de exploración en S: ${show(p.t)} s; reloj móvil=${show(q.proper)} s. La reciprocidad no compara eventos distintos.`;
 case 'mass-energy-equivalence':return `E0=${show(q.joules)} J para masa de reposo ${p.mass} µg. No implica que toda la masa de una reacción sea liberable ni que la energía total móvil sea mc².`;
 case 'energy-momentum-relation':return `E=${show(q.E)} MeV, K=${show(q.kinetic)} MeV, v/c=${show(q.beta)}. Masa del control expresada como mc²; si m=p=0 no hay velocidad definida.`;
 case 'relativistic-energy-momentum-relation':return `pc=${show(q.momentum)} MeV; E′=${show(q.transformedE)} MeV, p′c=${show(q.transformedP)} MeV. E²−p²c²=${show(q.invariant)} MeV²; boost firmado de S a S′.`;
 case 'einstein-model-specific-heat':return `Cv/(3R)=${show(q.fraction)}; ocupación por oscilador=${show(q.n)}. U térmica=${show(q.U)} J/mol; energía de punto cero no afecta Cv. Un mol de átomos, frecuencia única.`;
 case 't-hypothesis-test':return `ν=${q.df}; p bilateral=${show(q.p)}; crítico |t|=${show(q.critical)}; ${q.reject?'rechaza':'no rechaza'} H0. Intervalo ${100-p.alpha}%: [${show(q.low)}, ${show(q.high)}]. σ desconocida; s muestral con n−1.`;
 case 'spacetime-interval':return `Separación ${q.type}; intervalo transformado=${show(q.transformed)} L². ${p.x===0&&p.ct===0?'Eventos coincidentes; no hay una trayectoria de luz entre puntos distintos.':q.type==='nulo'?'Separación nula: puede conectar eventos mediante luz.':q.proper===null?'No hay tiempo propio real para separación espacial.':'cΔτ='+show(q.proper)+' L.'} Firma −+++; ct y x tienen la misma unidad.`;
 case 'hardy-weinberg-equilibrium':return `q=${show(q.q)}; AA=${show(100*q.frequencies[0])}%, Aa=${show(100*q.frequencies[1])}%, aa=${show(100*q.frequencies[2])}%. Frecuencias esperadas; no conteos exactos de una población finita.`;
 case 'potential-of-hydrogen-ph':return `aH=${show(q.activity)}; actividad adimensional. Un cambio de una unidad multiplica/divide actividad por diez. pH puede salir de 0–14.`;
 case 'ionic-product-of-water':return `aH=${show(q.aH)}, aOH=${show(q.aOH)}, Kw=${show(q.Kw)}. Neutralidad pH=pKw/2=${show(q.neutral)}. pKw=14 corresponde aproximadamente a agua a 25 °C; no es universal.`;
 case 'hill-dose-response-equation':return `Respuesta relativa=${show(100*q.f)}%; EC50=${p.EC50} µM. n modifica pendiente; EC50 da media respuesta para cualquier n>0. Modelo hipotético, sin parámetros de un medicamento real.`;
 case 'michaelis-menten-kinetics':return `Ocupación cuasiestacionaria=${show(100*q.occupancy)}%. A ${show(p.t/20)} min: S=${show(q.remaining)}, producto=${show(q.product)} mM; v actual=${show(q.instant)} mM/min. 1 s del reloj visual equivale a 0,05 min del proceso.`;
 case 'hydrogen-ionization-energy':return `En=${show(q.energy)} eV; λ umbral=${show(q.threshold)} nm. ${q.kinetic===null?'Fotón insuficiente para ionizar este nivel; no se simula excitación ligada.':'Energía cinética fotoelectrón='+show(q.kinetic)+' eV.'} Aproximación de 13,6 eV.`;
 case 'bohr-radius':return `rn=${show(q.radius)} nm; En=${show(q.energy)} eV. Nube radial para l=n−1 promediada sobre orientaciones: máximo radial rn, media=${show(q.mean)} nm. La nube no es una trayectoria.`;
 case 'geodesic-equation-gr':return `r=${show(q.r)} GM/c²; φ=${show(q.phi)} rad; τ=${show(q.tau)} GM/c³; E específico=${show(q.energy)}. ${q.status}. Reloj visual avanza φ=0,3t, no tiempo de Schwarzschild; el horizonte está en r=2.`;
 case 'general-relativity':return `a=${show(q.a)}, ρ=${show(q.rho)} kg/m³, H=${show(q.H*3.085677581491367e19)} km/s/Mpc. Solución FLRW plana de polvo, Λ=0; a(0)=1, el cero no es el Big Bang. 1 s visual = 1 Gyr.`;
 case 'einstein-tensor':return `Gii=${show(q.gii*1e52)} y R=${show(q.scalar*1e52)} en 10⁻⁵² m⁻²; κT00=${show(q.source*1e52)}. Base ortonormal, firma −+++; Λ=0, fluido p=wρc². 1 s visual = 1 Gyr.`;
 case 'henderson-hasselbalch-equation':return `[HA]=${show(q.acid)}, [A−]=${show(q.base)} mM; cociente=${show(q.ratio)}. Se supone solución ideal y concentraciones de equilibrio; no se calcula la capacidad de neutralización.`;
 case 'schwarzschild-metric-time-dilation':return `rs=${show(q.rs)} km; r=${show(q.r)} km. τ=${show(q.proper)} s para t=${show(p.t)} s del reloj lejano; z=${show(q.redshift)}. Observador estático en r>rs, sostenido con aceleración.`;
 case 'schwarzschild-radius':return `rs=${show(q.rs)} km, R/rs=${show(q.ratio)}. ${q.outside?'Radio comparado exterior al horizonte.':'Dentro del horizonte: no representa una estrella estática.'} Solución esférica sin carga ni rotación; masa solar del control.`;
 case 'cosmological-constant':return `Λ=${show(q.lambda)} m⁻²; ρΛ=${show(q.rho)} kg/m³; a=${show(q.a)}, horizonte de de Sitter=${show(q.horizon)} Gly. Vacío puro con Λ>0, parámetros hipotéticos; 1 s visual = 1 Gyr.`;
 case 'variance':return `Desviación típica=${show(q.sd)}; estimador muestral=${show(q.sample)}. Aquí las cinco observaciones son la población completa: divisor 5; para estimar desde una muestra usar 4. Trasladar no cambia dispersión.`;
 default:throw new Error(id);
}}
add('eigenvalues-eigenvectors','Encuentra direcciones que sobreviven a una matriz',['Direcciones propias','Explorar','Potencias de A'],'Compara un vector con su imagen. Una dirección propia conserva su eje, aunque cambie longitud o sentido; una matriz real puede carecer de ejes propios reales.',{a:3,b:1,c:0,d:1,angle:35,k:3},[s('a','Entrada a',-3,3,.1),s('b','Entrada b',-3,3,.1),s('c','Entrada c',-3,3,.1),s('d','Entrada d',-3,3,.1),s('angle','Dirección de prueba',0,180,1,'°'),s('k','Potencia',1,5,1)],'Valor propio mayor inicial','','a',2,'Resuelve λ²−tr(A)λ+det(A)=0 y comprueba Av=λv con v≠0.','Una matriz real puede tener valores propios complejos','Todos los valores propios de una matriz real son reales');
add('principal-component-analysis-pca','Comprime una nube espacial conservando variación',['Nube 3D','Proyección 3D','Varianza retenida'],'Ocho puntos centrados en tres dimensiones. Gira la nube, proyecta sobre su primer eje principal y compara varianza retenida y error; la escala de variables importa.',{sx:2,sy:1,sz:.5,angle:25},[s('sx','Dispersión X',.2,4,.1),s('sy','Dispersión Y',.2,4,.1),s('sz','Dispersión Z',.2,4,.1),s('angle','Giro de los datos',-90,90,1,'°')],'Varianza retenida','%','sx',3,'Centra los datos y divide el autovalor mayor entre la suma de los tres.','PCA maximiza varianza y depende de la escala de las variables','Un eje principal demuestra causalidad o independencia estadística');
add('canonical-ensemble-partition-function','Reparte probabilidades entre niveles de energía',['Niveles','Explorar','Fluctuaciones'],'Tres niveles 0, Δ y 2Δ en contacto con un baño. Temperatura y degeneración cambian ocupación, energía y fluctuaciones; la distribución se normaliza con Z.',{T:300,gap:25,degeneracy:1},[s('T','Temperatura',100,1000,10,'K'),s('gap','Separación Δ',10,100,1,'meV'),s('degeneracy','Microestados del nivel 2Δ',1,5,1)],'Población excitada','%','T',600,'Calcula pesos gi exp(−Ei/kBT), suma Z y usa 100(1−P0).','La probabilidad de un nivel incluye todos sus microestados degenerados','Z es una probabilidad y siempre vale uno');
add('lorentz-transformations','Transforma el mismo evento entre dos observadores',['Evento','Explorar','Ejes de Minkowski'],'Las coordenadas de un evento cambian entre sistemas inerciales. La separación espaciotemporal se conserva; el tiempo transformado incluye simultaneidad relativa.',{beta:.6,x:1,ct:2},[s('beta','Velocidad β',-.9,.9,.05),s('x','Posición x',-3,3,.1,'L'),s('ct','Tiempo ct',-3,3,.1,'L')],'Posición x′','L','x',2,'Usa x′=γ(x−βct); S′ viaja a +βc respecto de S.','Un boost conserva x²−(ct)², no cada coordenada','Dos eventos simultáneos en S siempre son simultáneos en S′');
add('relativistic-velocity-addition','Lanza una señal desde una nave que se mueve',['Dos sistemas','Explorar','Frontera de la luz'],'Compón velocidades colineales firmadas. S′ se mueve a +βc; la señal tiene velocidad u′ en S′. El resultado u se mide en S.',{beta:.6,u:.6},[s('beta','Velocidad de S′/c',-.95,.95,.05),s('u','Velocidad u′/c',-1,1,.05)],'Velocidad u/c','','u',.2,'u/c=(u′/c+β)/(1+βu′/c); conserva signos y el sistema de cada dato.','Una señal luminosa sigue a ±c en ambos sistemas','Sumar dos velocidades sublumínicas permite superar c');
add('relativistic-length-contraction','Mide una barra con dos marcas simultáneas',['Regla móvil','Explorar','Simultaneidad'],'L0 es longitud en reposo. L se mide con eventos simultáneos en el sistema donde la barra se mueve; una fotografía mezcla tiempos de llegada de luz.',{beta:.6,L0:5},[s('beta','Velocidad β',-.95,.95,.05),s('L0','Longitud propia',1,10,.1,'m')],'Longitud medida','m','beta',.8,'L=L0√(1−β²); las mediciones de extremos deben tener el mismo t en S.','La contracción requiere simultaneidad en el sistema de medida','La barra se comprime mecánicamente en su propio sistema');
add('relativistic-time-dilation','Compara un reloj de luz y un reloj del laboratorio',['Reloj de luz','Explorar','Línea de universo'],'El tiempo propio une dos eventos en el mismo reloj. En el laboratorio móvil respecto del reloj, el intervalo coordinado es γ veces mayor.',{beta:.6,tau:4,t:0},[s('beta','Velocidad β',-.95,.95,.05),s('tau','Intervalo propio',1,10,.1,'s'),time()],'Intervalo coordinado','s','beta',.8,'Δt=γΔτ; para un reloj móvil τ=t/γ.','El tiempo propio pertenece a la línea de universo del reloj','γΔτ usa eventos simultáneos en lugares distintos como tiempo propio',{timeline:true});
add('mass-energy-equivalence','Convierte una pequeña masa de reposo en escala energética',['Balance','Explorar','Escala de energía'],'Calcula energía de reposo con masa en microgramos. Una variación de masa de un sistema cerrado corresponde a variación de energía; no fija la fracción liberable de una reacción.',{mass:1},[s('mass','Masa de reposo',.1,10,.1,'µg')],'Energía de reposo','MJ','mass',2,'Convierte µg a kg multiplicando por 10⁻⁹ y aplica E0=mc².','La masa del sistema incluye su energía interna','E0=mc² es siempre la energía cinética de una partícula');
add('energy-momentum-relation','Explora la curva de energía de partículas',['Dispersión','Explorar','Límite sin masa'],'La masa se introduce como energía de reposo mc² y el momento como pc. La curva contiene energía de reposo, energía cinética y el límite E=|pc|.',{mass:2,momentum:3},[s('mass','Energía mc²',0,5,.1,'MeV'),s('momentum','Momento pc',-5,5,.1,'MeV')],'Energía total','MeV','momentum',4,'E=√[(pc)²+(mc²)²]; el momento puede ser negativo, E física es no negativa.','Una partícula sin masa puede tener momento y energía','La energía total desaparece siempre cuando p=0');
add('relativistic-energy-momentum-relation','Cambia de observador sin cambiar la masa',['Cuadrimomento','Explorar','Boost de energía'],'Para una partícula masiva, E=γmc² y pc=βE. Un segundo observador transforma ambas magnitudes y conserva E²−(pc)².',{mass:1,beta:.6,boost:.3},[s('mass','Energía mc²',.2,5,.1,'MeV'),s('beta','Velocidad de partícula β',-.95,.95,.05),s('boost','Velocidad del observador',-.8,.8,.05)],'Energía en S','MeV','beta',.8,'Calcula γ con la velocidad de la partícula; para S′, E′=γb(E−bpc).','El invariante determina la masa, aunque E y p dependan del observador','La masa de reposo cambia al cambiar de sistema inercial');
add('einstein-model-specific-heat','Descongela grados de libertad cuánticos',['Osciladores','Explorar','Límite clásico'],'Un mol de átomos con tres osciladores por átomo y una frecuencia única. A baja T cuesta excitar niveles; a alta T Cv tiende a 3R.',{theta:300,T:300},[s('T','Temperatura',10,1000,10,'K'),s('theta','Temperatura de Einstein',100,600,10,'K')],'Capacidad molar Cv','J/(mol·K)','T',600,'Usa x=θE/T y Cv=3R x²e⁻ˣ/(1−e⁻ˣ)²; el cero energético no cambia la derivada.','El límite clásico es 3R; el modelo de Einstein no reproduce la ley T³ a muy baja T','Cv es igual a 3R incluso cuando casi no hay excitaciones');
add('t-hypothesis-test','Distingue efecto, ruido y tamaño de muestra',['Evidencia','Explorar','Región crítica'],'Contraste bilateral de una media con desviación poblacional desconocida. La muestra estima s, y sus grados de libertad determinan colas e intervalo de confianza.',{mean:1,nullMean:0,sd:2,n:16,alpha:5},[s('mean','Media observada',-3,3,.1),s('nullMean','Media de H0',-2,2,.1),s('sd','Desviación muestral s',.5,4,.1),s('n','Tamaño n',3,100,1),s('alpha','Nivel α',1,10,.5,'%')],'Estadístico t','','mean',2,'Divide x̄−μ0 entre s/√n; usa ν=n−1, no la tabla normal con σ conocida.','p no es la probabilidad de que H0 sea verdadera','No rechazar H0 prueba que el efecto es exactamente cero');
add('spacetime-interval','Clasifica eventos antes de cambiar de observador',['Cono causal','Explorar','Intervalo invariante'],'Con firma −+++, una separación temporal tiene ds²<0, una espacial ds²>0 y la luz ds²=0. El boost cambia coordenadas y conserva esta clasificación.',{x:1,ct:2,beta:.6},[s('x','Separación Δx',-3,3,.1,'L'),s('ct','Separación cΔt',0,3,.1,'L'),s('beta','Velocidad β',-.9,.9,.05)],'Intervalo ds²','L²','x',3,'ds²=Δx²−(cΔt)² en 1+1 dimensiones; el tiempo propio real exige ds²<0.','Una separación espacial no se conecta con una señal sublumínica','ds² es siempre positivo porque contiene cuadrados');
add('hardy-weinberg-equilibrium','Reparte alelos y predice genotipos',['Cruces','Explorar','Frecuencias esperadas'],'Dos alelos con frecuencias p y q=1−p. Apareamiento aleatorio y ausencia de fuerzas evolutivas producen p², 2pq y q² como frecuencias esperadas.',{p:.3},[s('p','Frecuencia del alelo A',0,1,.01)],'Heterocigotos esperados','%','p',.5,'Multiplica probabilidades de dos gametos: Aa ocurre en dos órdenes, por eso 2pq.','El máximo de 2pq es 1/2 cuando p=q','Hardy–Weinberg garantiza conteos exactos en cualquier muestra pequeña');
add('potential-of-hydrogen-ph','Explora una escala que comprime factores de diez',['Actividad','Explorar','Escala logarítmica'],'El pH usa la actividad adimensional del ion hidrógeno, no el logaritmo de una cantidad con unidad. La concentración es una aproximación en soluciones suficientemente ideales.',{loga:-3},[s('loga','log10 de actividad H',-16,1,.1)],'pH','','loga',-5,'pH=−log10 aH; invertir el signo de log aH recupera directamente pH.','Una unidad de pH representa un factor diez de actividad','pH=7 implica neutralidad a cualquier temperatura');
add('ionic-product-of-water','Mueve acidez y basicidad sin perder el producto',['Dos iones','Explorar','Neutralidad'],'Kw fija el producto de actividades de H y OH. La neutralidad ocurre en pH=pKw/2; el valor de pKw depende de temperatura y del estándar.',{pH:7,pKw:14},[s('pH','pH',-1,15,.1),s('pKw','pKw',12,16,.1)],'pOH','','pH',6,'pOH=pKw−pH; [H] y [OH] iguales implica pH=pOH=pKw/2 bajo idealidad.','Un agua neutra puede tener pH distinto de siete','pH+pOH vale catorce para cualquier temperatura');
add('hill-dose-response-equation','Ajusta una curva de respuesta cooperativa',['Respuesta','Explorar','Concentración logarítmica'],'Modelo hipotético de respuesta saturable. EC50 fija la media respuesta; n regula pendiente y Emax la escala de respuesta, sin identificar por sí solo un mecanismo.',{A:2,EC50:2,n:2,Emax:100},[s('A','Concentración A',0,10,.1,'µM'),s('EC50','EC50',.5,5,.1,'µM'),s('n','Coeficiente de Hill',.5,4,.1),s('Emax','Respuesta máxima',10,100,1,'u.a.')],'Respuesta','u.a.','A',6,'E/Emax=1/[1+(EC50/A)ⁿ]; en A=0 usa el límite cero y en A=EC50 vale 1/2.','EC50 da media respuesta para cualquier n positivo','El coeficiente n siempre cuenta exactamente sitios de unión');
add('michaelis-menten-kinetics','Satura enzimas y sigue el agotamiento de sustrato',['Velocidad inicial','Explorar','Producto acumulado'],'Una enzima, un sustrato y producto inicialmente nulo. Compara velocidad inicial con evolución integrada cuasiestacionaria, en la que el sustrato disminuye y el producto crece.',{S:2,Km:2,Vmax:10,t:0},[s('S','Sustrato inicial',0,10,.1,'mM'),s('Km','Km',.5,5,.1,'mM'),s('Vmax','Vmax',1,20,.1,'mM/min'),time()],'Velocidad inicial','mM/min','S',6,'v0=Vmax S0/(Km+S0); durante el proceso Vmax t=S0−S+Km ln(S0/S).','Km no es necesariamente una constante de disociación','Duplicar S siempre duplica la velocidad a cualquier concentración',{timeline:true});
add('hydrogen-ionization-energy','Supera el umbral de un electrón ligado',['Niveles','Explorar','Fotoionización'],'El cero de energía corresponde al electrón libre a distancia infinita. Desde un nivel n del hidrógeno se necesita 13,6/n² eV; el exceso del fotón se convierte en energía cinética.',{n:1,photon:15},[s('n','Nivel principal n',1,6,1),s('photon','Energía del fotón',0,20,.1,'eV')],'Energía de ionización','eV','n',2,'En=−13,6/n² eV; ionizar requiere 0−En. Por encima del umbral K=hν−Eion.','Un nivel excitado necesita menos energía para ionizar','Todo fotón, por débil que sea, ioniza el estado fundamental');
add('bohr-radius','Relaciona tamaño atómico y distribución radial',['Escala atómica','Nube radial 3D','Distribución radial'],'rn=n²a0/Z para un sistema de un electrón. La vista cuántica representa probabilidad radial de l=n−1 promediada sobre orientaciones; no muestra un electrón siguiendo órbitas.',{n:1,Z:1},[s('n','Nivel principal n',1,6,1),s('Z','Carga nuclear Z',1,5,1)],'Radio rn','nm','n',2,'a0=0,0529177 nm; multiplica por n² y divide entre Z. El radio no es la media radial.','Una nube de probabilidad no es una trayectoria clásica','El radio de Bohr es igual a la posición exacta del electrón');
add('geodesic-equation-gr','Compara una órbita relativista con su límite newtoniano',['Órbita','Geometría espacial 3D','Precesión'],'Geodésica temporal ecuatorial exterior de Schwarzschild. Integra la ecuación orbital u″+u=1/L²+3u² desde un punto de retorno; el dibujo 3D es una sección espacial de Flamm.',{radius:20,L:4.5,t:0},[s('radius','Radio de retorno',6,30,.2,'GM/c²'),s('L','Momento específico L',3.2,7,.1,'GM/c'),time()],'Energía específica E/(mc²)','','L',7,'En el retorno E/(mc²)=√[(1−2/r0)(1+L²/r0²)], con r0 y L reducidos. El término 3u² cambia la órbita. El reloj visual avanza ángulo, no tiempo propio.','La superficie de Flamm muestra geometría espacial, no una fuerza de embudo','La parábola dibujada es una foto real del espacio-tiempo',{timeline:true});
add('general-relativity','Relaciona expansión y densidad en una solución de Einstein',['Universo de polvo','Expansión 3D','Geometría y materia'],'Caso exacto FLRW plano con polvo y Λ=0. La expansión diluye materia y H cambia; no es un solucionador de cualquier distribución gravitatoria.',{rho:3,t:5},[s('rho','Densidad inicial',1,10,.1,'10⁻²⁶ kg/m³'),time()],'Factor de escala a','','rho',6,'H0²=8πGρ0/3 y a=[1+3H0 t/2]^(2/3), con a(0)=1 y t en segundos físicos.','El caso de polvo usa p=0 y ρ∝a⁻³','Una malla deformada cualquiera constituye solución de Einstein',{timeline:true});
add('einstein-tensor','Compara curvatura y energía componente a componente',['Tensor','Explorar','Traza y curvatura'],'Tensor de Einstein en una base ortonormal de FLRW plano, con fluido p=wρc² y Λ=0. Tiempo, densidad y presión cambian sus componentes coherentemente.',{rho:3,w:0,t:0},[s('rho','Densidad inicial',1,10,.1,'10⁻²⁶ kg/m³'),s('w','Razón p/(ρc²)',-1,1,.1),time()],'Componente G00','10⁻⁵² m⁻²','rho',6,'G00=3H²/c²=8πGρ/c²; Gii=wG00 y R=(1−3w)G00 en base ortonormal.','La traza depende de la firma de la métrica','El tensor de Einstein es una única cantidad escalar',{timeline:true});
add('henderson-hasselbalch-equation','Ajusta la proporción de un tampón ideal',['Par conjugado','Explorar','Relación logarítmica'],'Concentraciones de equilibrio de ácido débil HA y base A−. El cociente fija pH y la cantidad total cambia reserva química, aunque no cambie ese cociente.',{pKa:4.76,ratio:0,total:20},[s('pKa','pKa',2,10,.1),s('ratio','log10([A−]/[HA])',-2,2,.1),s('total','Concentración total',2,100,1,'mM')],'pH','','ratio',1,'pH=pKa+log10([A−]/[HA]); un cociente diez añade una unidad.','Las concentraciones usadas son de equilibrio bajo la aproximación ideal','La ecuación calcula por sí sola toda una titulación y la capacidad tampón');
add('schwarzschild-metric-time-dilation','Compara relojes sostenidos a distintas alturas',['Relojes','Explorar','Redshift'],'Observador estático exterior a una masa esférica no rotante. Su tiempo propio se compara con el tiempo de un observador estático lejano; la relación no vale para cualquier caída libre.',{radius:2,mass:1,t:0},[s('radius','Radio r/rs',1.05,10,.05),s('mass','Masa central',1,20,.5,'M☉'),time()],'Ritmo dτ/dt','','radius',4,'dτ/dt=√(1−rs/r); r>rs para un observador estático. t corresponde al reloj lejano.','Mantenerse estático cerca del horizonte exige aceleración','El reloj que cae libremente usa siempre esta misma relación',{timeline:true});
add('schwarzschild-radius','Compara un tamaño con el horizonte de una masa',['Umbral','Explorar 3D','Escala de masa'],'Radio areal de horizonte de Schwarzschild, rs=2GM/c². Es una escala de una solución esférica sin rotación ni carga; un objeto ordinario no es automáticamente un agujero negro por tener masa.',{mass:1,radius:10},[s('mass','Masa',1,30,.5,'M☉'),s('radius','Radio comparado',1,50,.5,'km')],'Radio de Schwarzschild','km','mass',2,'Convierte M☉ a kg y aplica 2GM/c²; rs crece linealmente con M.','El radio de horizonte no es una superficie material sólida','Toda estrella de una masa solar tiene un horizonte visible');
add('cosmological-constant','Explora expansión acelerada en vacío de de Sitter',['Vacío activo','Expansión 3D','Horizonte cosmológico'],'Caso exacto plano de vacío puro con Λ>0. H es constante y a crece exponencialmente; densidad equivalente del vacío permanece constante, con presión negativa.',{lambda:1,t:5},[s('lambda','Constante Λ',.1,4,.1,'10⁻⁵² m⁻²'),time()],'H de de Sitter','km/s/Mpc','lambda',2,'H=c√(Λ/3); a=e^(Ht), ρΛ=Λc²/(8πG) y pΛ=−ρΛc².','Presión negativa del vacío no significa densidad de energía negativa','La densidad del vacío cae como la de polvo al expandirse',{timeline:true});
add('variance','Construye dispersión a partir de distancias a la media',['Desviaciones','Explorar','Áreas cuadráticas'],'Cinco observaciones tratadas como población completa. Suma cuadrados de desviaciones y compara el divisor poblacional con el estimador de una muestra.',{mean:2,scale:1},[s('scale','Escala de dispersión',0,3,.1),s('mean','Media',-5,5,.1)],'Varianza poblacional','','scale',2,'Las desviaciones son −2s,−s,0,s,2s: suma 10s²; dividir entre cinco da 2s².','Reescalar por a multiplica varianza por a²','Trasladar todas las observaciones cambia la varianza');
