import * as M from './insight-math.js';
export function drawInsight(ctx,w,h,id,p,v){
 const rgb=/^#[\da-f]{6}$/i.test(v.background)?[1,3,5].map(i=>parseInt(v.background.slice(i,i+2),16)):(v.background.match(/[\d.]+/g)||[255,255,255]).slice(0,3).map(Number),dark=rgb.reduce((s,x)=>s+x,0)<384;
 const blue=dark?'#78b8cc':v.accent,red=dark?'#e2a58d':'#9c4d37',green=dark?'#87baa0':'#397458',ink=v.ink,line=v.line,muted=v.muted,mode=v.mode;
 ctx.fillStyle=v.background;ctx.fillRect(0,0,w,h);
 const path=(pts,c=blue,width=2,fill=false)=>{ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(fill){ctx.closePath();ctx.fillStyle=c;ctx.fill();}else{ctx.strokeStyle=c;ctx.lineWidth=width;ctx.stroke();}};
 const text=(s,x,y,c=ink,size=12)=>{ctx.fillStyle=c;ctx.font=`${size}px system-ui`;ctx.textAlign='center';ctx.fillText(String(s),x,y,w-18);};
 const dot=(a,c=blue,r=5)=>{ctx.beginPath();ctx.arc(a[0],a[1],r,0,2*Math.PI);ctx.fillStyle=c;ctx.fill();};
 const arrow=(a,b,c=blue)=>{path([a,b],c);const t=Math.atan2(b[1]-a[1],b[0]-a[0]);path([[b[0]-7*Math.cos(t-.4),b[1]-7*Math.sin(t-.4)],b,[b[0]-7*Math.cos(t+.4),b[1]-7*Math.sin(t+.4)]],c);};
 const heading=(a,b)=>{text(a,w/2,20,blue,w<500?11:14);const limit=Math.floor(w/5.7);if(b.length>limit){const at=b.lastIndexOf(' ',limit);text(b.slice(0,at),w/2,h-25,muted,w<500?9:11);text(b.slice(at+1),w/2,h-10,muted,w<500?9:11);}else text(b,w/2,h-12,muted,w<500?9:11);};
 const fmt=x=>Math.abs(x)>=10000?x.toExponential(1):Number(x.toFixed(3)).toLocaleString('es');
 const plot=(xmin,xmax,ymin,ymax,xlabel='',ylabel='',equal=false)=>{let l=40,r=w-20,t=52,b=h-78;if(equal){const s=Math.min((r-l)/(xmax-xmin),(b-t)/(ymax-ymin)),cx=(l+r)/2,cy=(t+b)/2;l=cx-s*(xmax-xmin)/2;r=cx+s*(xmax-xmin)/2;t=cy-s*(ymax-ymin)/2;b=cy+s*(ymax-ymin)/2;}const point=(x,y)=>[l+(x-xmin)/(xmax-xmin)*(r-l),b-(y-ymin)/(ymax-ymin)*(b-t)];path([[l,t],[l,b],[r,b]],line,1);if(ymin<0&&ymax>0)path([point(xmin,0),point(xmax,0)],line,1);if(xmin<0&&xmax>0)path([point(0,ymin),point(0,ymax)],line,1);text(fmt(xmin),l,b+14,muted,9);text(fmt(xmax),r,b+14,muted,9);text(fmt(ymax),l-4,t+12,muted,9);text(xlabel,(l+r)/2,b+29,muted,10);text(ylabel,(l+r)/2,t-12,muted,10);const curve=(f,c=blue)=>{let pts=[];for(let i=0;i<=180;i++){const x=xmin+(xmax-xmin)*i/180,y=f(x);if(Number.isFinite(y)&&y>=ymin&&y<=ymax)pts.push(point(x,y));else{if(pts.length>1)path(pts,c);pts=[];}}if(pts.length>1)path(pts,c);};return {point,curve,unpoint:([x,y])=>[xmin+(x-l)/(r-l)*(xmax-xmin),ymin+(b-y)/(b-t)*(ymax-ymin)]};};
 const samples=(f,n=80)=>Array.from({length:n+1},(_,i)=>f(i/n));
 const scene=points=>{const c=Math.cos(v.yaw),s=Math.sin(v.yaw),cp=Math.cos(v.pitch),sp=Math.sin(v.pitch),raw=([x,y,z])=>[c*x-s*y,sp*(s*x+c*y)-cp*z],a=points.map(raw),xs=a.map(q=>q[0]),ys=a.map(q=>q[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min((w-70)/Math.max(.2,xmax-xmin),(h-100)/Math.max(.2,ymax-ymin));return q=>{const[x,y]=raw(q);return [w/2+(x-(xmin+xmax)/2)*scale,h/2+(y-(ymin+ymax)/2)*scale];};};
 const bars=(values,labels)=>{const top=65,bottom=h-65,max=Math.max(.01,...values.map(Math.abs)),signed=values.some(x=>x<0),zero=signed?(bottom+top)/2:bottom,scale=(bottom-top)/(signed?2:1)/max;path([[18,zero],[w-18,zero]],line,1);values.forEach((x,i)=>{const X=(i+.5)*w/values.length,bw=Math.min(65,w/values.length*.55),Y=zero-x*scale,c=[blue,red,green][i%3];ctx.fillStyle=c+'44';ctx.fillRect(X-bw/2,Math.min(zero,Y),bw,Math.abs(Y-zero));path([[X-bw/2,Y],[X+bw/2,Y]],c);text(labels[i],X,bottom+16,muted,w<500?9:12);if(!v.hide)text(fmt(x),X,top-14,c,10);});};
 const q=M.model(id,p),clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
 if(id==='eigenvalues-eigenvectors'){
  const a=p.angle*Math.PI/180,v0=[Math.cos(a),Math.sin(a)],image=M.mul(q.A,v0),vectors=[v0,image];if(mode===2){for(let k=1;k<p.k;k++)vectors.push(M.mul(q.A,vectors.at(-1)));}
  const span=Math.max(1.4,...vectors.flat().map(Math.abs))*1.2,g=plot(-span,span,-span,span,'x','y',true);vectors.forEach((x,i)=>{arrow(g.point(0,0),g.point(...x),i===0?green:i===vectors.length-1?red:line);});if(mode!==2)q.vectors.forEach(x=>path([g.point(...x.map(t=>-span*t)),g.point(...x.map(t=>span*t))],blue,1));heading(mode===2?'Aplicaciones repetidas de la matriz':'Vector de prueba y su imagen',q.complex?'Sin ejes propios reales: el giro no conserva direcciones reales':q.defective?'Dos raíces iguales; un solo eje independiente':'Verde v · coral Av · azul ejes propios · arrastra la dirección');return {drag:xy=>{const[x,y]=g.unpoint(xy);return {angle:(Math.atan2(y,x)*180/Math.PI+180)%180};}};
 }
 if(id==='principal-component-analysis-pca'){
  if(mode===2){bars(q.values.map(x=>100*x/q.total),['PC1','PC2','PC3']);heading('Variación conservada por cada eje','Covarianza muestral; divisor n−1 · no estandarización automática');return {};}
  const ends=q.vectors.map((x,i)=>x.map(z=>z*Math.sqrt(q.values[i])*1.3)),P=scene([...q.points,...ends,...q.projected]);q.points.forEach((x,i)=>{if(mode===1)path([P(x),P(q.projected[i])],line,1);dot(P(x),blue);if(mode===1)dot(P(q.projected[i]),red,4);});ends.forEach((x,i)=>{arrow(P([0,0,0]),P(x),[red,green,line][i]);text('PC'+(i+1),P(x)[0]+12,P(x)[1]-5,[red,green,muted][i],10);});heading('Nube centrada y direcciones principales',mode===1?'Coral: reconstrucción de rango 1 · tenue: error descartado':'Girar cámara no cambia covarianza · cambiar escala sí');return {rotate:true};
 }
 if(id==='canonical-ensemble-partition-function'){
  if(mode===2){bars([q.U/p.gap,q.C,q.entropy],['U/Δ','C/kB','S/kB']);heading('Promedios y fluctuaciones del mismo conjunto','C/kB=Var(E)/(kBT)² · S incluye degeneración de los niveles');return {};}
  for(let i=0;i<3;i++){const y=h-68-i*(h-125)/2;path([[w*.12,y],[w*.42,y]],blue);text(i===0?'0':i===1?'Δ':'2Δ',w*.1,y-8,muted,11);ctx.fillStyle=[green,blue,red][i]+'66';ctx.fillRect(w*.5,y-17,w*.36*q.prob[i],17);for(let j=0;j<q.deg[i];j++)dot([w*.18+j*12,y-6],blue,3);if(!v.hide)text((q.prob[i]*100).toFixed(1)+' %',w*.82,y-5,ink,11);}heading('Energías discretas y ocupación normalizada','Longitud de barras: probabilidad del nivel · puntos: microestados');return {};
 }
 if(id==='lorentz-transformations'||id==='spacetime-interval'){
  if(mode===2&&id==='spacetime-interval'){bars([p.x*p.x,-p.ct*p.ct,q.s],['Δx²','−(cΔt)²','ds²']);heading('Cuadrados con signos distintos','Firma −+++; temporal negativo, espacial positivo, luz nulo');return {};}
  const g=plot(-3.6,3.6,-3.6,3.6,'x/L','ct/L',true);path([g.point(-3.5,-3.5),g.point(3.5,3.5)],line,1);path([g.point(-3.5,3.5),g.point(3.5,-3.5)],line,1);if(mode===2){path([g.point(-3,-3*p.beta),g.point(3,3*p.beta)],green);path([g.point(-3*p.beta,-3),g.point(3*p.beta,3)],blue);text('ct′',...g.point(2.7*p.beta,2.7),blue,10);text('x′',...g.point(2.7,2.7*p.beta),green,10);}arrow(g.point(0,0),g.point(p.x,p.ct),red);dot(g.point(p.x,p.ct),red);heading(id==='spacetime-interval'?'Un evento dentro o fuera del cono de luz':'Un evento, dos juegos de coordenadas',mode===2?'Ejes primados inclinados; evento dibujado en S, no trasladado':'Tenue: trayectorias de luz · coral: evento en S · arrastra el punto');return {drag:xy=>{const[x,ct]=g.unpoint(xy);return {x:clamp(x,-3,3),ct:clamp(ct,id==='spacetime-interval'?0:-3,3)};}};
 }
 if(id==='relativistic-velocity-addition'){
  if(mode===2){const g=plot(-1,1,-2,2,'u′/c','u/c');g.curve(x=>(x+p.beta)/(1+x*p.beta));g.curve(x=>x+p.beta,red);g.curve(()=>1,line);g.curve(()=>-1,line);dot(g.point(p.u,q.u),green);heading('La frontera luminosa se conserva','Azul: composición relativista · coral: suma galileana');return {};}
  const P=(x,y)=>[w/2+x*w*.21,y];for(const [u,y,label,c]of[[p.u,h*.38,'S′: u′',blue],[q.u,h*.65,'S: u',red]]){path([P(-1,y),P(1,y)],line,1);arrow(P(0,y),P(u,y),c);text(label,w*.18,y-20,c,12);text('−c',...P(-1,y+15),muted,10);text('+c',...P(1,y+15),muted,10);}heading('Velocidades firmadas en dos sistemas','Las flechas comparten escala · mueve u′ con el ratón o los controles');return {drag:([x])=>({u:clamp((x-w/2)/(w*.21),-1,1)})};
 }
 if(id==='relativistic-length-contraction'){
  if(mode===2){const span=p.L0+1,g=plot(-2*span,2*span,-span,span,'x (m)','ct (m)',true);for(const x0 of[0,q.L])path([g.point(x0-p.beta*span,-span),g.point(x0+p.beta*span,span)],blue);path([g.point(0,0),g.point(q.L,0)],red,4);dot(g.point(0,0),red);dot(g.point(q.L,0),red);heading('Medir extremos en una misma recta t=0','Azul: líneas de universo · coral: eventos simultáneos en S');return {};}
  const scale=(w-75)/10;path([[35,h*.38],[35+p.L0*scale,h*.38]],blue,7);path([[35,h*.65],[35+q.L*scale,h*.65]],red,7);text('L0: reposo',w/2,h*.38-18,blue,12);text('L: en movimiento',w/2,h*.65-18,red,12);heading('Una longitud propia y una medida en S','Misma escala espacial · contracción en la dirección del movimiento');return {};
 }
 if(id==='relativistic-time-dilation'){
  if(mode===2){const g=plot(-20,20,0,20,'x (ls)','ct (ls)',true);path([g.point(0,0),g.point(p.beta*20,20)],blue);for(let t=0;t<=20;t+=q.gamma*2)dot(g.point(p.beta*t,t),line,3);dot(g.point(p.beta*p.t,p.t),red);heading('Tics propios sobre una línea de universo','Tenue: cada 2 s propios · coordenadas en segundos-luz, c=1');return {};}
  const span=Math.max(1.5,2*Math.abs(p.beta)*q.gamma+.5),g=plot(-span,span,0,1.4,'x (ls)','altura (ls)',true),phase=(p.t/q.gamma)%2,y=phase<=1?phase:2-phase;path([g.point(0,0),g.point(p.beta*q.gamma,1),g.point(2*p.beta*q.gamma,0)],blue);dot(g.point(p.beta*q.gamma*phase,y),red,6);path([g.point(0,0),g.point(p.beta*q.gamma,0)],line,1);heading('Un ciclo de un reloj de luz visto en S','Dos espejos separados 1 ls; luz a c en diagonal · pulsa Reproducir');return {};
 }
 if(id==='energy-momentum-relation'||id==='relativistic-energy-momentum-relation'){
  if(mode===2&&id==='relativistic-energy-momentum-relation'){bars([q.E,q.transformedE,Math.sqrt(q.invariant)],['E en S','E en S′','mc²']);heading('Cambian energía y momento, queda la masa','E′=γb(E−bpc) · la masa es raíz del invariante, no energía móvil');return {};}
  const mass=p.mass,momentum=id==='energy-momentum-relation'?p.momentum:q.momentum,span=Math.max(5,Math.abs(momentum)*1.15),g=plot(-span,span,0,Math.hypot(span,mass)*1.15,'pc (MeV)','E (MeV)');g.curve(x=>Math.hypot(x,mass));if(mode===2)g.curve(x=>Math.abs(x),green);dot(g.point(momentum,q.E),red);heading('Energía total sobre la hipérbola de masa',mode===2?'Verde: límite sin masa E=|pc|':'E siempre positiva; signos del momento indican dirección');return {};
 }
 if(id==='hydrogen-ionization-energy'){
  if(mode===2){bars([p.photon,-q.ion,q.kinetic??0],['Fotón','−Eion',q.kinetic===null?'Sin ionizar':'K electrón']);heading('Balance al alcanzar el continuo',q.kinetic===null?'La energía del fotón no alcanza este umbral':'Exceso positivo: energía cinética del electrón libre');return {};}
  const g=plot(0,1,-14,1,'','E (eV)');g.curve(()=>0,line);for(let n=1;n<=6;n++){const y=-13.6/(n*n);path([g.point(.1,y),g.point(.8,y)],n===p.n?red:line,n===p.n?3:1);if(n===1||n===p.n)text('n='+n,...g.point(.92,y),muted,10);}arrow(g.point(.5,q.energy),g.point(.5,0),blue);heading('Niveles ligados y cero del continuo','Rojo: nivel seleccionado · azul: energía mínima para ionizar');return {};
 }
 if(id==='bohr-radius'){
  if(mode===1){const points=[];for(let j=1;j<=12;j++){const rho=j/5,weight=q.radial(rho),count=Math.max(1,Math.round(weight*18));for(let k=0;k<count;k++){const z=1-2*(k+.5)/count,a=k*2.3999632297,rad=Math.sqrt(1-z*z);points.push([rho*rad*Math.cos(a),rho*rad*Math.sin(a),rho*z]);}}const P=scene([...points,[0,0,0]]);points.sort((a,b)=>a[2]-b[2]).forEach(x=>dot(P(x),blue,2.7));dot(P([0,0,0]),red,4);heading('Distribución radial promediada sobre orientación','Densidad de puntos ilustrativa para l=n−1; no trayectorias · gira cámara');return {rotate:true};}
  const g=plot(0,3,0,Math.max(1,q.radial(1)*1.2),'r/rn','Pρ (adimensional)');g.curve(q.radial);dot(g.point(1,q.radial(1)),red);heading('Probabilidad por intervalo de radio','∫Pρ dρ=1 · máximo rn; media diferente · estados con l=n−1');return {};
 }
 if(id==='geodesic-equation-gr'){
  const full=M.orbit(p,true,6),newton=M.orbit(p,false,6);
  if(mode===1){const mesh=[];for(let j=0;j<8;j++){const r=2.05+j*3.5;mesh.push(samples(u=>[r*Math.cos(2*Math.PI*u),r*Math.sin(2*Math.PI*u),2*Math.sqrt(2*(r-2))]));}const spatial=q.path.map(([x,y])=>[x,y,2*Math.sqrt(2*(Math.hypot(x,y)-2))]),P=scene([...mesh.flat(),...spatial]);mesh.forEach(row=>path(row.map(P),line,1));path(spatial.map(P),blue,2.5);dot(P(spatial.at(-1)),red);heading('Sección espacial de Flamm y órbita exterior','Altura de inmersión geométrica; no potencial ni dirección de una fuerza');return {rotate:true};}
  const span=Math.min(205,Math.max(p.radius+1,...full.path.flatMap(([x,y])=>[Math.abs(x),Math.abs(y)]))),g=plot(-span,span,-span,span,'x (GM/c²)','y (GM/c²)',true);path(samples(u=>g.point(2*Math.cos(2*Math.PI*u),2*Math.sin(2*Math.PI*u))),ink,2);if(mode===2)path(newton.path.map(x=>g.point(x[0],x[1])),green,1);path(full.path.map(x=>g.point(x[0],x[1])),line,1);path(q.path.map(x=>g.point(x[0],x[1])),blue,2);dot(g.point(q.path.at(-1)[0],q.path.at(-1)[1]),red);heading('Una órbita calculada, no una elipse impuesta',mode===2?'Verde: Binet newtoniano · azul: Schwarzschild · negro r=2':'Reloj visual avanza φ; datos de energía y tiempo propio en la lectura');return {};
 }
 if((id==='general-relativity'||id==='cosmological-constant')&&mode===1||id==='schwarzschild-radius'&&mode===1){
  if(id==='schwarzschild-radius'){const R=p.radius/q.rs,mesh=[];for(const radius of [1,R])for(let j=1;j<6;j++)mesh.push({radius,pts:samples(u=>{const a=u*2*Math.PI,b=j*Math.PI/6;return [radius*Math.sin(b)*Math.cos(a),radius*Math.sin(b)*Math.sin(a),radius*Math.cos(b)];})});const P=scene(mesh.flatMap(x=>x.pts));mesh.forEach(row=>path(row.pts.map(P),row.radius===1?blue:line,1.5));heading('Dos superficies con radios físicos comparables','Azul: horizonte areal · tenue: tamaño comparado · no superficie sólida');return {rotate:true};}
  const points=[];for(const x of[-1,0,1])for(const y of[-1,0,1])for(const z of[-1,0,1])points.push([x*q.a,y*q.a,z*q.a]);const reference=points.map(x=>x.map(y=>y/q.a)),P=scene([...points,...reference]);points.forEach((x,i)=>{path([P(reference[i]),P(x)],line,1);dot(P(reference[i]),line,2);dot(P(x),blue,4);});heading('Separación de observadores comóviles','Tenue: a=1 · azul: a actual · cámara autoajusta; números conservan escala');return {rotate:true};
 }
 if(id==='einstein-tensor'){
  const values=mode===2?[-q.g00*1e52,3*q.gii*1e52,-q.scalar*1e52]:[q.g00*1e52,q.gii*1e52,q.gii*1e52,q.gii*1e52];bars(values,mode===2?['−G00','ΣGii','−R']:['G00','G11','G22','G33']);heading(mode===2?'La traza usa la firma de la métrica':'Componentes en una base ortonormal','10⁻⁵² m⁻² · firma −+++ · tensor covariante; Λ=0');return {};
 }
 if(id==='hardy-weinberg-equilibrium'){
  if(mode===2){bars(q.frequencies.map(x=>100*x),['AA','Aa','aa']);heading('Tres frecuencias que suman cien por cien','Predicción de población ideal, no resultado obligatorio en una muestra');return {};}
  const X=w*.22,Y=h*.32,size=Math.min(w*.55,h*.45),half=size/2;for(const [i,j,label,prob]of[[0,0,'AA',q.frequencies[0]],[1,0,'Aa',p.p*q.q],[0,1,'aA',p.p*q.q],[1,1,'aa',q.frequencies[2]]]){ctx.fillStyle=(i===j?blue:green)+'33';ctx.fillRect(X+i*half,Y+j*half,half-2,half-2);text(label,X+(i+.5)*half,Y+(j+.5)*half,ink,16);if(!v.hide)text((100*prob).toFixed(1)+'%',X+(i+.5)*half,Y+(j+.8)*half,muted,10);}heading('Dos gametos, cuatro combinaciones','Aa y aA son el mismo genotipo; sus probabilidades se suman');return {drag:([x])=>({p:clamp(x/w,0,1)})};
 }
 if(['potential-of-hydrogen-ph','ionic-product-of-water','henderson-hasselbalch-equation'].includes(id)&&mode!==2){
  const ph=id==='potential-of-hydrogen-ph'?q.pH:id==='ionic-product-of-water'?p.pH:q.pH,neutral=id==='ionic-product-of-water'?q.neutral:7,l=35,r=w-35,Y=h*.5;for(let i=0;i<17;i++){ctx.fillStyle=`hsl(${i*15} 50% 58%)`;ctx.fillRect(l+(r-l)*i/17,Y,(r-l)/17+1,15);}const x=l+clamp((ph+1)/17,0,1)*(r-l);arrow([x,Y-33],[x,Y-3],ink);text('pH '+(v.hide?'?':ph.toFixed(2)),clamp(x,55,w-55),Y-43,ink,12);for(const [a,label]of[[-1,'−1'],[neutral,'neutro*'],[16,'16']])text(label,l+(a+1)/17*(r-l),Y+35,muted,10);heading(id==='henderson-hasselbalch-equation'?'La proporción cambia el pH':'Escala logarítmica de actividad','Colores orientativos; *neutralidad 7 solo bajo pKw=14');return {};
 }
 if(id==='hill-dose-response-equation'&&mode===0){for(let i=0;i<24;i++){const c=i/24<q.f?blue:line;dot([w*.2+(i%8)*w*.08,h*.34+Math.floor(i/8)*24],c,7);}heading('Respuesta relativa de un modelo saturable','Puntos ilustrativos, no recuento molecular · modifica concentración');return {};}
 if(id==='michaelis-menten-kinetics'&&mode!==2){const g=plot(0,10,0,p.Vmax*1.1,'S (mM)','v0 (mM/min)');g.curve(S=>p.Vmax*S/(p.Km+S));dot(g.point(p.S,q.v),red);heading('Más sustrato tiene rendimiento decreciente','Vmax es la asíntota; Km marca media velocidad, no siempre afinidad');return {};}
 if(id==='variance'&&mode===2){const span=6,g=plot(-span,span,0,6,'desviaciones','longitud',true);for(let i=0;i<5;i++){const d=(i-2)*p.scale,a=Math.abs(d),x=-5+i*2.1;path([g.point(x,0),g.point(x+a*.28,0),g.point(x+a*.28,a*.28),g.point(x,a*.28),g.point(x,0)],[blue,red,green][i%3],2,true);}heading('Las contribuciones son áreas cuadráticas','Cuadrados reducidos a escala común 0,28; el signo no resta área');return {};}
 if(id==='variance'){const g=plot(-12,12,0,1.2,'valor observado','');q.x.forEach(x=>{path([g.point(x,.3),g.point(p.mean,.8)],line,1);dot(g.point(x,.3),blue);});dot(g.point(p.mean,.8),red);heading('Alejar datos de la media aumenta dispersión','Azul: cinco datos · coral: media · desplaza dispersión con el ratón');return {drag:([x])=>({scale:clamp(Math.abs((x-w/2)/(w*.15)),0,3)})};}
 if(id==='schwarzschild-metric-time-dilation'&&mode!==2){
  const radius=Math.min(w*.14,h*.19),y=h*.49;
  for(const [x,elapsed,label,c]of[[w*.27,p.t,'Reloj lejano',blue],[w*.73,q.proper,'Reloj sostenido en r',red]]){
   path(samples(u=>[x+radius*Math.cos(u*2*Math.PI),y+radius*Math.sin(u*2*Math.PI)]),line,1.5);
   for(let k=0;k<12;k++){const a=k*Math.PI/6;path([[x+.9*radius*Math.cos(a),y+.9*radius*Math.sin(a)],[x+radius*Math.cos(a),y+radius*Math.sin(a)]],line,1);}
   const a=elapsed*Math.PI/5-Math.PI/2;arrow([x,y],[x+.78*radius*Math.cos(a),y+.78*radius*Math.sin(a)],c);dot([x,y],c,3);
   text(label,x,y-radius-16,c,w<500?10:12);text(v.hide?'? s':elapsed.toFixed(2)+' s',x,y+radius+24,c,12);
  }
  heading('Dos relojes, un mismo intervalo lejano','Una vuelta representa 10 s propios · r>rs · pulsa Reproducir');return {};
 }
 let g,f,other,point,title,footer;
 switch(id){
 case 'mass-energy-equivalence':g=plot(0,10,0,900,'m (µg)','E0 (MJ)');f=mass=>M.model(id,{mass}).value;point=[p.mass,q.value];title='Masa de reposo y energía equivalente';footer='µg×10⁻⁹ → kg · MJ=10⁶ J · no energía cinética';break;
 case 'einstein-model-specific-heat':g=plot(10,1000,0,3*M.R*1.1,'T (K)','Cv (J/mol/K)');f=T=>M.model(id,{...p,T}).value;other=mode===2?()=>3*M.R:null;point=[p.T,q.value];title='Excitaciones cuánticas y límite clásico';footer='Verde: 3R · Einstein usa una frecuencia; no ley T³ de Debye';break;
 case 't-hypothesis-test':{g=plot(-5,5,0,.45,'t','densidad Student');f=x=>M.studentDensity(x,q.df);const critical=mode===2?q.critical:Math.abs(q.t);for(const [lo,hi]of[[-5,-critical],[critical,5]])if(lo<hi){const pts=samples(u=>{const x=lo+(hi-lo)*u;return g.point(x,f(x));});path([g.point(lo,0),...pts,g.point(hi,0)],red+'44',1,true);}if(Math.abs(q.t)<=5)point=[q.t,f(q.t)];title=mode===2?'Rechazo bilateral al nivel α':'Colas de Student y evidencia observada';footer=mode===2?'Coral: regiones más allá del crítico · p no es P(H0)':'Coral: valores al menos tan extremos como |t observado|';break;}
 case 'potential-of-hydrogen-ph':g=plot(-16,1,-1,16,'log10 aH','pH');f=x=>-x;point=[p.loga,q.pH];title='El logaritmo convierte factores en diferencias';footer='Actividad adimensional; un factor diez cambia pH en una unidad';break;
 case 'ionic-product-of-water':g=plot(-1,15,-3,18,'pH','pOH');f=x=>p.pKw-x;point=[p.pH,q.pOH];title='Producto constante, logaritmos complementarios';footer='Neutral cuando pH=pOH=pKw/2; pKw depende de temperatura';break;
 case 'hill-dose-response-equation':{const log=mode===2;g=plot(log?-2:0,log?2:10,0,p.Emax*1.1,log?'log10(A/µM)':'A (µM)','E (u.a.)');f=x=>M.model(id,{...p,A:log?10**x:x}).value;point=p.A>0?[log?Math.log10(p.A):p.A,q.response]:null;title='EC50 determina la media respuesta';footer='n cambia pendiente · efecto y concentración con unidades diferentes';break;}
 case 'michaelis-menten-kinetics':g=plot(0,1,0,Math.max(1,p.S)*1.1,'tiempo (min)','concentración (mM)');f=x=>M.substrate(p,20*x);other=x=>p.S-M.substrate(p,20*x);point=[p.t/20,q.product];title='Sustrato consumido y producto conservado';footer='Azul S(t) · verde P(t) · S+P=S0 · modelo cuasiestacionario';break;
 case 'general-relativity':g=plot(0,20,0,M.model(id,{...p,t:20}).a*1.1,'tiempo (Gyr)',mode===2?'G00/(8πGρ0/c²)':'a');f=t=>{const a=M.model(id,{...p,t});return mode===2?a.g00/M.model(id,{...p,t:0}).g00:a.a;};other=mode===2?t=>M.model(id,{...p,t}).source/M.model(id,{...p,t:0}).source:null;point=[p.t,f(p.t)];title=mode===2?'Curvatura y fuente evolucionan juntas':'Expansión exacta de un universo de polvo plano';footer=mode===2?'Azul G00 · verde κT00; curvas coinciden · Λ=0':'a(0)=1; origen del reloj elegido después del Big Bang';break;
 case 'cosmological-constant':g=plot(0,20,0,(mode===2?q.horizon:M.model(id,{...p,t:20}).a)*1.1,'tiempo (Gyr)',mode===2?'radio (Gly)':'a');f=t=>mode===2?q.horizon:M.model(id,{...p,t}).a;other=mode===2?t=>q.horizon/M.model(id,{...p,t}).a:null;point=[p.t,f(p.t)];title=mode===2?'Un horizonte físico constante, un alcance comóvil menor':'El vacío puro tiene H constante';footer=mode===2?'Azul: c/H físico · verde: c/(Ha) comóvil referido a a(0)=1':`Horizonte c/H=${q.horizon.toFixed(2)} Gly · Λ>0 · sin materia ordinaria`;break;
 case 'schwarzschild-radius':g=plot(1,30,0,90,'M (M☉)','rs (km)');f=mass=>M.model(id,{...p,mass}).rs;point=[p.mass,q.rs];title='El horizonte areal crece linealmente con masa';footer='Sin giro ni carga; radio comparado no implica una estrella estable';break;
 case 'schwarzschild-metric-time-dilation':g=plot(1.01,10,0,1,'r/rs','dτ/dt');f=x=>Math.sqrt(1-1/x);point=[p.radius,q.factor];title='Ritmo de un reloj estático respecto del infinito';footer='r>rs; no extrapolar a observadores estáticos en el horizonte';break;
 case 'henderson-hasselbalch-equation':g=plot(-2,2,p.pKa-2.2,p.pKa+2.2,'log10([A−]/[HA])','pH');f=x=>p.pKa+x;point=[p.ratio,q.pH];title='El cociente, no la cantidad total, fija este pH';footer='Solución ideal; concentraciones de equilibrio; no titulación completa';break;
 default:throw new Error('Dibujo desconocido '+id);
 }
 g.curve(f);if(other)g.curve(other,green);if(point&&point.every(Number.isFinite))dot(g.point(...point),red);heading(title,footer);return {};
}
