export const softmax=(z,T=1)=>{const m=Math.max(...z),a=z.map(x=>Math.exp((x-m)/T)),sum=a.reduce((s,x)=>s+x,0);return a.map(x=>x/sum);};
export const sigmoid=x=>1/(1+Math.exp(-x));
export const points=p=>[-1,1].flatMap(side=>[-1,0,1].map(y=>[side*p.separation,y*p.spread]));
export function kmeans(p){const data=points(p);let centers=[[-p.separation,0],[-p.separation/3,0],...(p.k===3?[[p.separation,0]]:[])];const assign=()=>data.map(x=>centers.reduce((best,c,j)=>{const d=(x[0]-c[0])**2+(x[1]-c[1])**2;return d<best.d?{d,j}:best;},{d:Infinity,j:0}).j);
 let labels=assign();const costs=[];const cost=()=>data.reduce((s,x,i)=>s+(x[0]-centers[labels[i]][0])**2+(x[1]-centers[labels[i]][1])**2,0);costs.push(cost());for(let n=0;n<p.iterations;n++){centers=centers.map((c,j)=>{const group=data.filter((_,i)=>labels[i]===j);return group.length?[0,1].map(k=>group.reduce((s,x)=>s+x[k],0)/group.length):c;});labels=assign();costs.push(cost());}return {data,centers,labels,costs,SSE:cost()};}
export function dbscan(p){const data=[[-2,-.4],[-2,.4],[-1.6,0],[-2.4,0],[2,-.4],[2,.4],[1.6,0],[2.4,0],[0,1.8],[0,-1.8]],near=i=>data.map((x,j)=>Math.hypot(x[0]-data[i][0],x[1]-data[i][1])<=p.epsilon+1e-12?j:-1).filter(j=>j>=0),neighbors=data.map((_,i)=>near(i)),core=neighbors.map(x=>x.length>=p.minPoints),labels=Array(data.length).fill(-1),visited=new Set();let clusters=0;
 for(let i=0;i<data.length;i++){if(visited.has(i))continue;visited.add(i);if(!core[i])continue;labels[i]=clusters;const queue=[...neighbors[i]],queued=new Set(queue);for(let n=0;n<queue.length;n++){const j=queue[n];if(!visited.has(j)){visited.add(j);if(core[j])for(const k of neighbors[j])if(!queued.has(k)){queued.add(k);queue.push(k);}}if(labels[j]===-1)labels[j]=clusters;}clusters++;}return {data,labels,core,clusters,noise:labels.filter(x=>x===-1).length};}
export function optimize(p,algorithm){let x=p.x0,y=p.y0,vx=0,vy=0,sx=0,sy=0;const path=[[x,y]],records=[];for(let t=1;t<=p.steps;t++){const gx=x,gy=p.curvature*y;let dx,dy;if(algorithm==='momentum'){vx=p.beta*vx+gx;vy=p.beta*vy+gy;dx=p.eta*vx;dy=p.eta*vy;}else{sx=p.beta2*sx+(1-p.beta2)*gx*gx;sy=p.beta2*sy+(1-p.beta2)*gy*gy;if(algorithm==='adam'){vx=p.beta*vx+(1-p.beta)*gx;vy=p.beta*vy+(1-p.beta)*gy;dx=p.eta*(vx/(1-p.beta**t))/(Math.sqrt(sx/(1-p.beta2**t))+1e-8);dy=p.eta*(vy/(1-p.beta**t))/(Math.sqrt(sy/(1-p.beta2**t))+1e-8);}else{dx=p.eta*gx/(Math.sqrt(sx)+1e-8);dy=p.eta*gy/(Math.sqrt(sy)+1e-8);}}
 x-=dx;y-=dy;path.push([x,y]);records.push({t,gx,gy,vx,vy,sx,sy,dx,dy});}
 return {x,y,path,records,loss:(x*x+p.curvature*y*y)/2};}
export function bellman(p){let V=[0,0,0,0],history=[V.slice()],policy=[0,0,0];for(let n=0;n<p.iterations;n++){const next=V.map((v,s)=>{if(s===3)return 0;const stay=-.5+p.gamma*v,advance=-1+(s===2?5*p.success:0)+p.gamma*(p.success*V[s+1]+(1-p.success)*v);policy[s]=advance>=stay?1:0;return Math.max(stay,advance);});V=next;history.push(V.slice());}return {V,history,policy};}
export function pagerank(p){const links=[[1,2],[2],[0],[]],N=4,transition=Array.from({length:N},(_,i)=>Array.from({length:N},(_,j)=>links[j].length?(links[j].includes(i)?1/links[j].length:0):1/N));let r=Array(N).fill(1/N),history=[r.slice()];for(let n=0;n<p.iterations;n++){r=r.map((_,i)=>(1-p.damping)/N+p.damping*transition[i].reduce((s,x,j)=>s+x*r[j],0));history.push(r.slice());}return {r,history,transition,links};}
export function model(id,p){switch(id){
 case 'k-means-clustering':{const r=kmeans(p);return {...r,value:r.SSE};}
 case 'dbscan-density-based-clustering':{const r=dbscan(p);return {...r,value:r.clusters};}
 case 'bellman-equation':{const r=bellman(p);return {...r,value:r.V[0]};}
 case 'q-learning-off-policy-td-control':case 'sarsa-temporal-difference-control':{const qnext=id.startsWith('q-learning')?Math.max(p.good,p.bad):p.action===0?p.good:p.bad,target=p.reward+(p.terminal?0:p.gamma*qnext),error=target-p.old,updated=p.old+p.alpha*error;return {value:updated,updated,target,error,qnext};}
 case 'policy-gradient-reinforce':{const probability=sigmoid(p.theta),score=p.action-probability,advantage=p.reward-p.baseline,gradient=advantage*score;return {value:gradient,probability,score,advantage,gradient};}
 case 'softmax-function':{const prob=softmax([p.a,p.b,p.c],p.temperature);return {value:100*prob[0],prob};}
 case 'gradient-descent-with-momentum':case 'rmsprop-optimizer':case 'adam-optimizer-adaptive-moment-estimation':{const algorithm=id.startsWith('gradient')?'momentum':id.startsWith('rms')?'rmsprop':'adam',r=optimize(p,algorithm);return {...r,value:r.loss,algorithm};}
 case 'regression-loss-functions-mse-mae-huber':{const e=p.prediction-p.target,abs=Math.abs(e),mse=e*e,mae=abs,huber=abs<=p.delta?e*e/2:p.delta*(abs-p.delta/2);return {value:huber,e,mse,mae,huber,derivative:Math.abs(e)<=p.delta?e:p.delta*Math.sign(e)};}
 case 'relu-activation-function':return {value:Math.max(0,p.x),derivative:p.x===0?null:p.x>0?1:0};
 case 'backpropagation':{const z=p.w*p.x+p.b,h=Math.tanh(z),output=p.v*h,loss=(output-p.target)**2/2,db=(output-p.target)*p.v*(1-h*h),dw=db*p.x,dv=(output-p.target)*h;return {value:dw,z,h,output,loss,dw,db,dv};}
 case 'rbf-kernel-radial-basis-function':{const distance=Math.hypot(p.x-p.cx,p.y-p.cy),kernel=Math.exp(-p.gamma*distance*distance);return {value:kernel,distance,kernel,f:(x,y)=>Math.exp(-p.gamma*((x-p.cx)**2+(y-p.cy)**2))};}
 case 'maximum-margin-support-vector-machine':{const norm=Math.hypot(p.wx,p.wy),data=[[-2,-1,-1],[-2,1,-1],[2,-1,1],[2,1,1]],margins=data.map(([x,y,label])=>label*(p.wx*x+p.wy*y+p.b)),slacks=margins.map(m=>Math.max(0,1-m)),objective=norm*norm/2+p.C*slacks.reduce((a,b)=>a+b,0);return {value:objective,norm,data,margins,slacks,objective,margin:norm===0?null:2/norm,feasible:margins.every(m=>m>=1-1e-12)};}
 case 'pagerank-network-authority-algorithm':{const r=pagerank(p);return {...r,value:100*r.r[2]};}
 default:throw new Error(id);
}}
