import {model,softmax} from './machine-math.js';
import {MACHINE_LABS} from './machine-configs.js';
import {studioScene} from './studio-scene.js';
export function drawMachine(ctx,w,h,id,p,v){const q=model(id,p),s=studioScene(ctx,w,h,v),{plot,path,dot,text,arrow,bars,heading,blue,red,green,line}=s;
 heading(MACHINE_LABS[id].title,`${v.mode===0?'Predice antes de revelar · ':''}${v.mode===2?'Compara mecanismos':'Ajusta un dato y observa su efecto'}`);
 if(id==='k-means-clustering'||id==='dbscan-density-based-clustering'){if(v.mode===2&&id==='k-means-clustering'){const a=plot(0,Math.max(1,p.iterations),0,Math.max(1,...q.costs)*1.1,'Iteración','SSE');path(q.costs.map((y,i)=>a.point(i,y)),blue);return {};}
  const a=plot(-5,5,-3,3,'x (unidad de referencia)','y',true),colors=[blue,red,green];q.data.forEach((x,i)=>{if(id.startsWith('dbscan')&&v.mode===2){const radius=p.epsilon;path(s.samples(t=>a.point(x[0]+radius*Math.cos(2*Math.PI*t),x[1]+radius*Math.sin(2*Math.PI*t))),line,1);}dot(a.point(...x),q.labels[i]<0?s.muted:colors[q.labels[i]%3],id.startsWith('dbscan')&&q.core[i]?6:4);});if(q.centers)q.centers.forEach((c,i)=>{const [x,y]=a.point(...c);path([[x-6,y-6],[x+6,y+6]],colors[i],3);path([[x-6,y+6],[x+6,y-6]],colors[i],3);q.data.filter((_,j)=>q.labels[j]===i).forEach(point=>path([a.point(...point),[x,y]],line,1));});return {};}
 if(/momentum|rmsprop|adam/.test(id)){if(v.mode===2){const r=q.records.at(-1);bars([r.gx,r.gy,r.dx,r.dy],['g x','g y','paso x','paso y']);return {};}const a=plot(-4,4,-3,3,'x','y',true);for(const level of [1,2,4,8,12])path(s.samples(t=>a.point(Math.sqrt(2*level)*Math.cos(2*Math.PI*t),Math.sqrt(2*level/p.curvature)*Math.sin(2*Math.PI*t))),line,1);path(q.path.map(x=>a.point(...x)),blue);q.path.forEach((x,i)=>dot(a.point(...x),i===q.path.length-1?red:blue,3));text('Curvas F=(x²+κy²)/2',w/2,40,s.muted,10);return {};}
 if(id==='softmax-function'){if(v.mode<2)bars(q.prob.map(x=>100*x),['A %','B %','C %']);else{const a=plot(.2,3,0,100,'Temperatura','Probabilidad %');[blue,red,green].forEach((c,i)=>a.curve(T=>100*softmax([p.a,p.b,p.c],T)[i],c));}return {};}
 if(id==='bellman-equation'){if(v.mode===2){const a=plot(0,p.iterations,-1,5,'Barrido','Valor');[blue,red,green].forEach((c,i)=>path(q.history.map((r,n)=>a.point(n,r[i])),c));}else{const pos=[0,1,2,3].map(i=>[(i+.5)*w/4,h/2]);pos.slice(0,3).forEach((x,i)=>arrow(x,pos[i+1]));pos.forEach((x,i)=>{dot(x,i===3?green:blue,7);text(i===3?'Meta':`s${i}`,x[0],x[1]-25);if(!v.hide)text(`V=${s.fmt(q.V[i])}`,x[0],x[1]+25);});}return {};}
 if(id.includes('learning-off')||id.startsWith('sarsa')){bars(v.mode===2?[p.reward+p.gamma*Math.max(p.good,p.bad),p.reward+p.gamma*(p.action===0?p.good:p.bad),q.target]:[p.old,q.target,q.updated],v.mode===2?['Objetivo Q sin terminal','Objetivo SARSA sin terminal','Objetivo efectivo']:['Q anterior','Objetivo TD','Q nuevo']);return {};}
 if(id==='policy-gradient-reinforce'){if(v.mode===2)bars([q.score,q.advantage,q.gradient],['score','G−baseline','gradiente']);else{const a=plot(-4,4,0,1,'θ','π(acción 1)');a.curve(x=>1/(1+Math.exp(-x)));dot(a.point(p.theta,q.probability),red);}return {};}
 if(id==='regression-loss-functions-mse-mae-huber'){const a=plot(-4,4,v.mode===2?-8:0,8,'Error e',v.mode===2?'Derivada':'Pérdida');a.curve(e=>v.mode===2?2*e:e*e,blue);a.curve(e=>v.mode===2?(e===0?NaN:Math.sign(e)):Math.abs(e),red);a.curve(e=>v.mode===2?Math.max(-p.delta,Math.min(p.delta,e)):Math.abs(e)<=p.delta?e*e/2:p.delta*(Math.abs(e)-p.delta/2),green);dot(a.point(q.e,v.mode===2?q.derivative:q.huber),green);text('Azul: cuadrática · rojo: absoluta · verde: Huber',w/2,40,s.muted,10);return {};}
 if(id==='relu-activation-function'){const a=plot(-3,3,-.2,3,'x',v.mode===2?'Derivada':'ReLU(x)');a.curve(x=>v.mode===2?(Math.abs(x)<.03?NaN:x>0?1:0):Math.max(0,x));if(v.mode===2){const at=a.point(0,0);ctx.beginPath();ctx.arc(...at,4,0,2*Math.PI);ctx.strokeStyle=red;ctx.stroke();text('En cero no hay derivada clásica',w/2,40,s.muted,10);}else dot(a.point(p.x,q.value),red);return {};}
 if(id==='backpropagation'){if(v.mode===2)bars([q.dw,q.db,q.dv],['∂L/∂w','∂L/∂b','∂L/∂v']);else{const values=[p.x,q.z,q.h,q.output],names=['x','wx+b','tanh(z)','v h'];values.forEach((x,i)=>{const X=(i+.5)*w/4;if(i<3)arrow([X+12,h/2],[(i+1.5)*w/4-12,h/2]);dot([X,h/2],i===3?red:blue,6);text(names[i],X,h/2-25);if(!v.hide)text(s.fmt(x),X,h/2+25);});}return {};}
 if(id==='rbf-kernel-radial-basis-function'){if(v.mode===2){const a=plot(0,4,0,1,'Distancia','K');a.curve(d=>Math.exp(-p.gamma*d*d));dot(a.point(q.distance,q.kernel),red);}else{const a=plot(-3,3,-3,3,'x','y',true);for(const level of [.1,.3,.6,.9]){const r=Math.sqrt(-Math.log(level)/p.gamma);path(s.samples(t=>a.point(p.cx+r*Math.cos(2*Math.PI*t),p.cy+r*Math.sin(2*Math.PI*t))),line,1);}dot(a.point(p.cx,p.cy),green);dot(a.point(p.x,p.y),red);path([a.point(p.cx,p.cy),a.point(p.x,p.y)],blue);}return {};}
 if(id==='maximum-margin-support-vector-machine'){if(v.mode===2){bars([q.norm*q.norm/2,...q.slacks.map(x=>p.C*x)],['norma²/2','Cξ1','Cξ2','Cξ3','Cξ4']);return {};}const a=plot(-3,3,-2,2,'x','y',true);q.data.forEach(([x,y,label])=>dot(a.point(x,y),label>0?blue:red,6));if(Math.abs(p.wy)>1e-9){for(const t of [-1,0,1])a.curve(x=>(t-p.b-p.wx*x)/p.wy,t===0?green:line);}else if(Math.abs(p.wx)>1e-9){for(const t of [-1,0,1]){const x=(t-p.b)/p.wx;if(x>=-3&&x<=3)path([a.point(x,-2),a.point(x,2)],t===0?green:line);}}else text('w=0: no existe frontera geométrica',w/2,40,red,11);return {};}
 if(id==='pagerank-network-authority-algorithm'){if(v.mode===2){const a=plot(0,p.iterations,0,1,'Iteración','Autoridad');[blue,red,green,s.muted].forEach((c,i)=>path(q.history.map((r,n)=>a.point(n,r[i])),c));}else{const pos=[[w*.25,h*.35],[w*.75,h*.35],[w*.5,h*.7],[w*.85,h*.7]];q.links.forEach((list,j)=>list.forEach(i=>arrow(pos[j],pos[i],line)));pos.forEach((x,i)=>{dot(x,[blue,red,green,s.muted][i],7+30*q.r[i]);text('ABCD'[i],x[0],x[1]-30);if(!v.hide)text(s.fmt(100*q.r[i])+'%',x[0],x[1]+35);});}return {};}
 throw new Error('Escena desconocida '+id);
}
