import {model,gelu,attention,pe} from './network-math.js';
import {NETWORK_LABS} from './network-configs.js';
import {studioScene} from './studio-scene.js';
export function drawNetwork(ctx,w,h,id,p,v){const q=model(id,p),s=studioScene(ctx,w,h,v),{plot,path,dot,bars,heading,blue,red,green,line,text}=s;heading(NETWORK_LABS[id].title,v.mode===0?'Predice antes de revelar':'Operaciones del modelo reducido · sin entrenamiento oculto');
 if(id==='batch-normalization'||id==='layer-normalization'){if(v.mode===2){bars([q.mean,q.variance,p.gamma,p.beta],['media','varianza','γ','β']);}else{const max=Math.max(3,...q.values.map(Math.abs),...q.output.map(Math.abs))*1.2,a=plot(0,q.values.length-1,-max,max,'Muestra (BN) / característica (LN)','Valor');path(q.values.map((x,i)=>a.point(i,x)),blue);path(q.output.map((x,i)=>a.point(i,x)),red);q.values.forEach((x,i)=>dot(a.point(i,x),blue));q.output.forEach((x,i)=>dot(a.point(i,x),red));text('Azul: entrada · rojo: salida',w/2,40,s.muted,11);}return {};}
 if(id==='gelu-activation-function'){const a=plot(-4,4,v.mode===2?-.2:-.4,v.mode===2?1.3:4,'x',v.mode===2?'Derivada GELU':'Activación');a.curve(x=>v.mode===2?model(id,{x}).derivative:gelu(x),blue);if(v.mode<2)a.curve(x=>Math.max(0,x),line);dot(a.point(p.x,v.mode===2?q.derivative:q.value),red);return {};}
 if(id==='scaled-dot-product-attention'||id==='cross-attention'){if(v.mode===2){bars(q.weights.map(x=>100*x),['Clave 1 %','Clave 2 %','Clave 3 %']);text('Scores: '+q.scores.map(s.fmt).join(' / '),w/2,h-38,s.muted,11);}else{const a=plot(-3,3,-3,3,id==='cross-attention'?'Memoria del codificador: eje 1':'Clave: eje 1','Eje 2',true);q.keys.forEach((x,i)=>{s.arrow(a.point(0,0),a.point(...x),p.mask&&i===2?line:blue);text(`K${i+1}: V=${q.values[i]}`,a.point(...x)[0],a.point(...x)[1]-12,s.muted,10);});s.arrow(a.point(0,0),a.point(...q.query),red);}return {};}
 if(id==='multi-head-attention'){if(v.mode===2)bars([q.heads[0].output,q.heads[1].output,q.output],['Cabeza 1','Cabeza 2','Proyección']);else{const a=plot(0,2,0,1,'Índice de clave','Peso');[blue,red].forEach((c,j)=>{path(q.heads[j].weights.map((x,i)=>a.point(i,x)),c);q.heads[j].weights.forEach((x,i)=>dot(a.point(i,x),c));});text('Azul: cabeza 1 · rojo: cabeza 2',w/2,40,s.muted,11);}return {};}
 if(id==='sinusoidal-positional-encoding'){if(v.mode===2){const a=plot(-1.2,1.2,-1.2,1.2,'Seno','Coseno',true);path(s.samples(t=>a.point(Math.sin(2*Math.PI*t),Math.cos(2*Math.PI*t))),line);dot(a.point(q.embedding[0],q.embedding[1]),blue);dot(a.point(q.embedding[2],q.embedding[3]),red);text('Azul: ω=1 · rojo: ω=0,01',w/2,40,s.muted,11);}else{const a=plot(0,50,-1.1,1.1,'Posición','Componente');[blue,red,green,s.muted].forEach((c,j)=>a.curve(x=>pe(x)[j],c));q.embedding.forEach((x,i)=>dot(a.point(p.position,x),[blue,red,green,s.muted][i]));}return {};}
 if(id==='rotary-position-embedding-rope'){if(v.mode===2){const a=plot(-12,12,-1.1,1.1,'n−m','Producto rotado');a.curve(d=>.6*Math.cos(d*p.frequency)-.8*Math.sin(d*p.frequency));dot(a.point(p.n-p.m,q.dot),red);}else{const a=plot(-1.3,1.3,-1.3,1.3,'x','y',true);path(s.samples(t=>a.point(Math.cos(2*Math.PI*t),Math.sin(2*Math.PI*t))),line);s.arrow(a.point(0,0),a.point(...q.q),blue);s.arrow(a.point(0,0),a.point(...q.k),red);text('Consulta azul · clave roja · norma uno',w/2,40,s.muted,10);}return {};}
 if(id==='ppo-clipped-objective'){const a=plot(.2,1.8,-6,6,'Razón r', 'Objetivo sustituto');a.curve(r=>r*p.advantage,line);a.curve(r=>model(id,{...p,ratio:r}).value,blue);dot(a.point(p.ratio,q.value),red);text(`A=${p.advantage}; se maximiza el objetivo`,w/2,40,s.muted,11);return {};}
 throw new Error('Escena desconocida '+id);
}
