import * as M from './spectrum-math.js';
import {fmt} from './learning-math.js';
export function drawSpectrum(ctx,w,h,id,p,v){
 const blue=v.accent,red='#c46c50',green='#4b8c70',ink=v.ink,line=v.line,muted=v.muted,mode=v.mode;
 ctx.fillStyle=v.background;ctx.fillRect(0,0,w,h);
 const path=(pts,color=blue,width=2,fill=false)=>{ctx.beginPath();pts.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(fill){ctx.closePath();ctx.fillStyle=color;ctx.fill();}else{ctx.lineWidth=width;ctx.strokeStyle=color;ctx.stroke();}};
 const text=(s,x,y,color=ink,size=12)=>{ctx.fillStyle=color;ctx.font=`${size}px system-ui`;ctx.textAlign='center';ctx.fillText(s,x,y,Math.max(40,w-20));};
 const dot=(q,color=blue,r=5)=>{ctx.beginPath();ctx.arc(q[0],q[1],r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();};
 const circle=(q,r,color=blue)=>{ctx.beginPath();ctx.arc(q[0],q[1],Math.max(0,r),0,Math.PI*2);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();};
 const arrow=(a,b,color=blue)=>{if(Math.hypot(b[0]-a[0],b[1]-a[1])<1)return;path([a,b],color);const t=Math.atan2(b[1]-a[1],b[0]-a[0]);path([[b[0]-7*Math.cos(t-.45),b[1]-7*Math.sin(t-.45)],b,[b[0]-7*Math.cos(t+.45),b[1]-7*Math.sin(t+.45)]],color);};
 const heading=(a,b)=>{text(a,w/2,21,blue,w<500?10:14);text(b,w/2,h-10,muted,w<500?9:11);};
 const plot=(xmin,xmax,ymin,ymax,xlabel='',ylabel='',equal=false)=>{let l=43,r=w-24,t=45,b=h-60;if(equal){const scale=Math.min((r-l)/(xmax-xmin),(b-t)/(ymax-ymin)),cx=(l+r)/2,cy=(t+b)/2;l=cx-scale*(xmax-xmin)/2;r=cx+scale*(xmax-xmin)/2;t=cy-scale*(ymax-ymin)/2;b=cy+scale*(ymax-ymin)/2;}const point=(x,y)=>[l+(x-xmin)/(xmax-xmin)*(r-l),b-(y-ymin)/(ymax-ymin)*(b-t)];path([[l,t],[l,b],[r,b]],line,1);if(ymin<0&&ymax>0)path([point(xmin,0),point(xmax,0)],line,1);text(fmt(xmin),l,b+14,muted,10);text(fmt(xmax),r,b+14,muted,10);text(Math.abs(ymax)>=10000?ymax.toExponential(1):fmt(ymax),l-5,t+12,muted,10);text(xlabel,(l+r)/2,b+27,muted,10);text(ylabel,(l+r)/2,t-8,muted,10);const curve=(f,color=blue)=>{let pts=[];for(let i=0;i<=200;i++){const x=xmin+(xmax-xmin)*i/200,y=f(x);if(Number.isFinite(y)&&y>=ymin&&y<=ymax)pts.push(point(x,y));else{if(pts.length>1)path(pts,color);pts=[];}}if(pts.length>1)path(pts,color);};return {point,curve,unpoint:q=>[xmin+(q[0]-l)/(r-l)*(xmax-xmin),ymin+(b-q[1])/(b-t)*(ymax-ymin)],layout:{xmin,xmax,ymin,ymax,l,r,t,b}};};
 const bars=(values,labels)=>{const max=Math.max(1e-8,...values.map(Math.abs)),bottom=h-55,top=65,negative=values.some(x=>x<0),zero=negative?(bottom+top)/2:bottom,scale=(bottom-top)/(negative?2:1)/max;path([[24,zero],[w-24,zero]],line,1);values.forEach((x,i)=>{const x0=(i+.5)*w/values.length,bw=Math.min(70,w/values.length*.55),y=zero-x*scale,c=[blue,red,green][i%3];ctx.fillStyle=c+'44';ctx.fillRect(x0-bw/2,Math.min(y,zero),bw,Math.abs(y-zero));path([[x0-bw/2,y],[x0+bw/2,y]],c);text(labels[i],x0,bottom+17,muted,w<500?9:12);if(!v.hide)text(fmt(x),x0,top-15,c,11);});};
 const scene=(points)=>{const cy=Math.cos(v.yaw),sy=Math.sin(v.yaw),cp=Math.cos(v.pitch),sp=Math.sin(v.pitch),raw=([x,y,z])=>[cy*x-sy*y,sp*(sy*x+cy*y)-cp*z];const coords=points.map(raw),xs=coords.map(q=>q[0]),ys=coords.map(q=>q[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min((w-85)/Math.max(.5,xmax-xmin),(h-105)/Math.max(.5,ymax-ymin));return q=>{const [x,y]=raw(q);return [w/2+(x-(xmin+xmax)/2)*scale,h/2+(y-(ymin+ymax)/2)*scale];};};
 const axes=(P,span=1,labels=['x','y','z'])=>{const O=P([0,0,0]);[[span,0,0],[0,span,0],[0,0,span]].forEach((q,i)=>{arrow(O,P(q),line);const Q=P(q);text(labels[i],Q[0]+10,Q[1]-5,muted,10);});};
 const coil=(a,b,turns=8,color=blue)=>{const pts=[];for(let i=0;i<=turns*24;i++){const u=i/(turns*24);pts.push([a[0]+(b[0]-a[0])*u,a[1]+(b[1]-a[1])*u+Math.sin(u*turns*2*Math.PI)*12]);}path(pts,color,2.5);};
 const resistor=(a,b,color=blue,label='')=>{const dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy),n=[-dy/len,dx/len],pts=[a];for(let j=1;j<10;j++){const u=j/10;pts.push([a[0]+dx*u+n[0]*(j%2?6:-6),a[1]+dy*u+n[1]*(j%2?6:-6)]);}pts.push(b);path(pts,color);if(label)text(label,(a[0]+b[0])/2+15,(a[1]+b[1])/2-15,color,11);};
 const plane=(...args)=>plot(...args,true);
 const q=M.model(id,p);
 const samples=(f,n=100)=>Array.from({length:n+1},(_,i)=>f(i/n));
 const sphere=(R,o=[0,0,0])=>Array.from({length:7},(_,j)=>samples(u=>{const a=u*2*Math.PI,b=(j+1)*Math.PI/8;return [o[0]+R*Math.sin(b)*Math.cos(a),o[1]+R*Math.sin(b)*Math.sin(a),o[2]+R*Math.cos(b)];},64));
 const frame=[[0,0,0],[1.5,0,0],[0,1.5,0],[0,0,1.5]];
 if(id==='frenet-serret-formulas'){
  const pts=samples(u=>M.helix(p,Math.max(0,p.t-8)+16*u).r),dirs=mode===2?[q.dT,q.dN,q.dB]:[q.T,q.N,q.B],ends=dirs.map(a=>q.r.map((x,i)=>x+a[i])),P=scene([...pts,...ends,...frame]);path(pts.map(P),blue);dot(P(q.r),red);dirs.forEach((a,i)=>{const e=P(ends[i]);arrow(P(q.r),e,[blue,red,green][i]);text((mode===2?['T′','N′','B′']:['T','N','B'])[i],e[0]+10,e[1]-5,[blue,red,green][i]);});axes(P);heading(mode===2?'Derivadas de la tríada respecto a s':'Hélice y tríada ortonormal',mode===2?'T′=κN · N′=−κT+τB · B′=−τN':'Radio y avance cambian κ,τ · cámara con ratón, tacto o flechas');return {rotate:true};
 }
 if(id==='geodesic-equation'){
  const mesh=sphere(p.radius),a=M.rad(p.angle),arc=samples(u=>[p.radius*Math.cos(q.theta*u),p.radius*Math.sin(q.theta*u)*Math.cos(a),p.radius*Math.sin(q.theta*u)*Math.sin(a)]),P=scene([...mesh.flat(),...arc,...frame]);mesh.forEach(row=>path(row.map(P),line,1));path(arc.map(P),blue,3);dot(P(arc[0]),green);dot(P(q.r),red);if(mode===2)path([P(arc[0]),P(q.r)],red);axes(P);heading('Una ruta intrínsecamente recta sobre la esfera',mode===2?'Arco Rθ frente a cuerda 2R sin(θ/2)':'Círculo máximo · la aceleración espacial es normal a la esfera');return {rotate:true};
 }
 if(['electromagnetic-wave-equation','maxwell-equations','poynting-vector'].includes(id)){
  if(mode===2){const energy=id==='poynting-vector',g=plot(0,4,energy?0:-1.2,1.2,'x (m)',energy?'S/(E0²/Z0)':'E/E0 = cB/E0');g.curve(x=>{const b=M.model(id,{...p,x});return energy?b.instant/(p.amplitude**2/376.730313668):b.E/p.amplitude;});if(energy)g.curve(()=>.5,green);heading(id==='maxwell-equations'?'Una solución de las cuatro leyes de Maxwell':'Perfil espacial de la onda',energy?'Verde: media 1/2 · el flujo no invierte su dirección':'∇·E=∇·B=0 · rotacionales ligados a variación temporal');return {};}
  const e=samples(u=>[4*u,Math.cos(2*Math.PI*(4*u/p.lambda-p.t/5)),0]),b=samples(u=>[4*u,0,Math.cos(2*Math.PI*(4*u/p.lambda-p.t/5))]),P=scene([...e,...b,...frame,[4,0,0]]);path(e.map(P),blue);path(b.map(P),red);for(let j=0;j<=12;j++){const x=j/3,z=Math.cos(2*Math.PI*(x/p.lambda-p.t/5));arrow(P([x,0,0]),P([x,z,0]),blue);arrow(P([x,0,0]),P([x,0,z]),red);}arrow(P([0,0,0]),P([4,0,0]),green);heading('E ⟂ B ⟂ propagación','Azul E/E0 · coral cB/E0 · amplitudes normalizadas; el reloj visual es fase');return {rotate:true};
 }
 if(id==='stokes-theorem'){
  if(mode===2){bars([q.flux,q.flux],['Borde','Interior']);heading('Circulación = flujo del rotacional','m²/s · las orientaciones del borde y de la normal deben corresponder');return {};}
  const a=M.rad(p.tilt),ring=samples(u=>[p.radius*Math.cos(2*Math.PI*u),p.radius*Math.sin(2*Math.PI*u)*Math.cos(a),p.radius*Math.sin(2*Math.PI*u)*Math.sin(a)]),n=[0,-Math.sin(a),Math.cos(a)],P=scene([...ring,n,...frame,[0,0,p.omega]]);path(ring.map(P),blue,3);for(let j=0;j<8;j++)arrow(P(ring[j*12]),P(ring[j*12+3]),green);arrow(P([0,0,0]),P(n),red);arrow(P([0,0,0]),P([0,0,p.omega]),blue);axes(P);heading('Inclinar el disco cambia el flujo','Coral: normal · azul: rotacional · verde: orientación del borde');return {rotate:true};
 }
 if(id==='ampere-maxwell-law'){
  if(mode===2){const g=plot(.5,10,-3,3,'r (cm)','B (µT)');g.curve(r=>M.model(id,{...p,r}).B);dot(g.point(p.r,q.B),red);heading('Dentro B∝r; fuera B∝1/r','Corriente de desplazamiento encerrada varía con el área del lazo');return {};}
  const R=p.radius/5,r=p.r/5,plates=[-.35,.35].map(z=>samples(u=>[R*Math.cos(2*Math.PI*u),R*Math.sin(2*Math.PI*u),z])),ring=samples(u=>[r*Math.cos(2*Math.PI*u),r*Math.sin(2*Math.PI*u),0]),P=scene([...plates.flat(),...ring,...frame]);plates.forEach(row=>path(row.map(P),line,1));path(ring.map(P),blue);if(p.I!==0)for(let j=0;j<8;j++){const a=j*Math.PI/4,b=a+.2*Math.sign(p.I);arrow(P([r*Math.cos(a),r*Math.sin(a),0]),P([r*Math.cos(b),r*Math.sin(b),0]),blue);}arrow(P([0,0,-.6]),P([0,0,.6]),red);axes(P);heading('Un lazo entre las placas de un condensador','Coral: corriente de referencia · B azimutal por desplazamiento, no conducción');return {rotate:true};
 }
 if(id==='magnetic-gauss-law'){
  if(mode===2){bars([q.top,q.bottom,0,0,0,0],['Superior','Inferior','L1','L2','L3','L4']);heading('Flujos firmados de seis caras','Wb · suma cero aun con campo no nulo');return {};}
  const s=Math.sqrt(p.area)/2,pts=[[-s,-s,-s],[s,-s,-s],[s,s,-s],[-s,s,-s],[-s,-s,s],[s,-s,s],[s,s,s],[-s,s,s]],P=scene([...pts,...frame,[0,0,-1.5]]);for(const [a,b]of[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]])path([P(pts[a]),P(pts[b])],line,1);if(p.B!==0)for(const x of[-.3,.3])for(const y of[-.3,.3])arrow(P([x,y,-1.4*Math.sign(p.B)]),P([x,y,1.4*Math.sign(p.B)]),blue);heading('Campo uniforme sobre una superficie cerrada','Las normales exteriores opuestas explican la cancelación');return {rotate:true};
 }
 if(id==='lorentz-force'){
  if(mode===2){const max=Math.max(1,...samples(u=>M.lorentz(p,20*u).energy)),g=plot(0,20,0,max*1.2,'t (s)','Ec (µJ)');g.curve(t=>M.lorentz(p,t).energy);dot(g.point(p.t,q.energy),red);heading('El campo magnético no realiza trabajo','Con E=0 la energía se conserva; E puede transferir energía');return {};}
  const pts=samples(u=>{const a=M.lorentz(p,20*u);return [a.x,a.y,0];},160),P=scene([...pts,...frame]);path(pts.map(P),line,1);path(pts.slice(0,1+Math.ceil(p.t*8)).map(P),blue,2);dot(P([q.x,q.y,0]),red,6);axes(P);heading('Trayectoria exacta no relativista en campos uniformes','Movimiento en xy · campo B en z · trayectoria completa tenue');return {rotate:true};
 }
 if(id==='lienard-wiechert-potentials'){
  if(q.singular){heading('Observador sobre la carga: singularidad','Mueve x o y; el potencial puntual no es finito');return {};}
  if(mode===2){const o=[q.source,0,0],mesh=sphere(q.delay,o),obs=[p.x,p.y,0],P=scene([...mesh.flat(),obs,[0,0,0],o]);mesh.forEach(row=>path(row.map(P),line,1));path([P(o),P(obs)],green);path([P(o),P([0,0,0])],blue);dot(P(o),green);dot(P([0,0,0]),blue);dot(P(obs),red);heading('La información emitida antes llega ahora','Verde: posición retardada · azul: actual · esfera de radio c·retardo');return {rotate:true};}
  const g=plane(-3,3,-3,3,'x/L','y/L');for(const level of[.4,.6,1,2])path(samples(u=>g.point(Math.cos(u*2*Math.PI)/level,Math.sin(u*2*Math.PI)/(level*Math.sqrt(1-p.beta*p.beta)))),line,1);dot(g.point(0,0),blue);dot(g.point(p.x,p.y),red);heading('Equipotenciales de una carga con velocidad constante','Azul: carga actual · coral: observador · no radiación por aceleración');return {drag:xy=>{const[x,y]=g.unpoint(xy);return {x:Math.max(-2,Math.min(2,x)),y:Math.max(-2,Math.min(2,y))};}};
 }
 if(id==='riemannian-metric'){
  const g=plane(-2.5,2.5,-2.5,2.5,'dx (m)','dy (m)'),a=M.rad(p.angle);path(samples(u=>{const x=Math.cos(2*Math.PI*u)/Math.sqrt(p.a),y=Math.sin(2*Math.PI*u)/Math.sqrt(p.b);return g.point(Math.cos(a)*x-Math.sin(a)*y,Math.sin(a)*x+Math.cos(a)*y);}),blue);if(mode!==2)path(samples(u=>g.point(Math.cos(u*2*Math.PI),Math.sin(u*2*Math.PI))),line,1);arrow(g.point(0,0),g.point(p.dx,p.dy),red);heading('Elipse de longitud métrica unitaria',mode===2?'Puntos azules: dᵀgd=1; coral: desplazamiento':'Tenue: unidad euclídea · arrastra el extremo del vector');return {drag:xy=>{const[dx,dy]=g.unpoint(xy);return {dx:Math.max(-2,Math.min(2,dx)),dy:Math.max(-2,Math.min(2,dy))};}};
 }
 if(['cayley-hamilton-theorem','singular-value-decomposition-svd','spectral-decomposition'].includes(id)){
  if(id==='cayley-hamilton-theorem'&&mode===2){const terms=q.square.flat().map((x,i)=>[x,-q.trace*q.A.flat()[i],i===0||i===3?q.det:0]),span=Math.max(1,...terms.flat().map(Math.abs)),g=plot(0,4,-span*2,span*2,'entrada','suma de términos');terms.forEach((row,i)=>{let total=0;row.forEach((x,j)=>{path([g.point(i+.5,total),g.point(i+.5,total+x)],[blue,red,green][j],5);total+=x;});dot(g.point(i+.5,total),ink,3);});heading('Los términos de cada entrada se cancelan','Azul A² · coral −tr(A)A · verde det(A)I · punto final: cero');return {};}
  const span=1.25*Math.max(1,...q.A.map(row=>Math.hypot(...row))),g=plane(-span,span,-span,span,'x','y'),unit=samples(u=>[Math.cos(2*Math.PI*u),Math.sin(2*Math.PI*u)]);path(unit.map(x=>g.point(...x)),line,1);path(unit.map(x=>g.point(...M.mul(q.A,x))),blue);
  if(id==='singular-value-decomposition-svd'){q.U.forEach((x,i)=>arrow(g.point(0,0),g.point(...x.map(y=>y*q.s[i])),[red,green][i]));if(mode===2)path(unit.map(x=>g.point(...M.mul(q.rank1,x))),red,3);heading(mode===2?'Aproximación óptima de rango 1':'Círculo de entrada, elipse de salida',mode===2?'Coral: rango 1 · error Frobenius = σ2':'Ejes de salida U con longitudes σ1,σ2 · reflexión permitida');}
  else if(id==='spectral-decomposition'){q.vectors.forEach((x,i)=>arrow(g.point(0,0),g.point(...x.map(y=>y*q.values[i])),[red,green][i]));if(mode===2)for(let j=0;j<2;j++)path(unit.map(x=>g.point(...q.vectors[j].map(y=>q.values[j]*M.dot(q.vectors[j],x)*y))),[red,green][j]);heading(mode===2?'Suma de dos proyecciones ortogonales':'Autovectores y escalados firmados','Azul: transformación completa · coral/verde: direcciones propias');}
  else heading('Transformación plana y polinomio característico','Tenue: entrada · azul: imagen · comprueba los términos en el resultado');return {};
 }
 if(id==='mohr-circle-2d-stress-transformation'){
  if(mode===2){const span=1.25*Math.max(1,q.r),g=plane(q.mid-span,q.mid+span,-span,span,'σ (MPa)','τ (MPa)');path(samples(u=>g.point(q.mid+q.r*Math.cos(u*2*Math.PI),q.r*Math.sin(u*2*Math.PI))),blue);dot(g.point(p.sx,p.tau),line);dot(g.point(q.sx,q.tau),red);path([g.point(q.mid,0),g.point(q.sx,q.tau)],red,1);heading('Círculo de Mohr: misma tensión, distinta cara','τ arriba: el punto gira −2θ · arrastra el punto coral');return {drag:xy=>{const[x,y]=g.unpoint(xy);let a=(Math.atan2(p.tau,(p.sx-p.sy)/2)-Math.atan2(y,x-q.mid))*90/Math.PI;while(a>90)a-=180;while(a< -90)a+=180;return {angle:a};}};}
  const a=M.rad(p.angle),c=Math.cos(a),s=Math.sin(a),P=([x,y])=>[w/2+(x*c-y*s)*Math.min(w,h)*.2,h/2-(x*s+y*c)*Math.min(w,h)*.2],pts=[[-1,-1],[1,-1],[1,1],[-1,1]];path([...pts,pts[0]].map(P),blue);arrow(P([1,0]),P([1+q.sx/150,0]),red);arrow(P([1,0]),P([1,q.tau/150]),green);arrow(P([0,1]),P([0,1+q.sy/150]),red);arrow(P([0,1]),P([q.tau/150,1]),green);heading('Elemento orientado y tracciones sobre sus caras','Coral: normal · verde: cortante · 150 MPa por longitud de lado');return {};
 }
 if(id==='cauchy-riemann'){
  if(mode===2){bars([q.ux,q.vy,q.uy,-q.vx],['ux','vy','uy','−vx']);heading('Dos pares que deben coincidir','ux=vy y uy=−vx · residuos no implican holomorfía sin hipótesis');return {};}
  const span=1.15*Math.max(3,Math.abs(q.u),Math.abs(q.v)),g=plane(-span,span,-span,span,'Re f','Im f');ctx.save();ctx.beginPath();ctx.rect(g.layout.l,g.layout.t,g.layout.r-g.layout.l,g.layout.b-g.layout.t);ctx.clip();for(let j=-1.5;j<=1.5;j+=.3)for(const axis of[0,1])path(samples(t=>{const x=axis?j:-1.5+3*t,y=axis?-1.5+3*t:j;return g.point(x*x-y*y+p.alpha*x,2*x*y-p.alpha*y);}),axis?blue+'88':green+'88',1);ctx.restore();dot(g.point(q.u,q.v),red);heading('Imagen de una retícula por z² + αz̄','Azul/verde: familias de líneas · coral: imagen del punto seleccionado');return {};
 }
 if(id==='pearson-correlation'||id==='covariance'){
  if(mode===2&&id==='covariance'){bars(q.x.map((x,i)=>x*(q.y[i]-q.my)),['1','2','3','4','5']);heading('Productos de desviaciones respecto a las medias','Covarianza poblacional: promedio de estas cinco contribuciones');return {};}
  const centered=mode===2,g=plot(-3,3,-13,13,centered?'x−media x':'x',centered?'(y−media y)/desv y':'y');q.x.forEach((x,i)=>dot(g.point(x,centered?(q.vy>0?(q.y[i]-q.my)/Math.sqrt(q.vy):0):q.y[i]),blue,6));if(!centered)g.curve(x=>p.slope*x+p.offset,green);heading(centered?'Centra y normaliza la nube':'Cinco observaciones con patrón de ruido ortogonal',q.r===null?'Varianza y nula: r indefinida':'Correlación no demuestra causalidad · divisor poblacional N=5');return centered?{}:{drag:xy=>{const[,y]=g.unpoint(xy);return {slope:Math.max(-3,Math.min(3,(y-p.offset+p.noise)/2))};}};
 }
 if(id==='boltzmann-entropy'&&mode!==2){path([[w/2,50],[w/2,h-50]],line,1);for(let i=0;i<p.N;i++){const left=i<p.left,x=(left?w*.23:w*.72)+(i%3-1)*18,y=70+Math.floor((left?i:i-p.left)/3)*20;dot([x,y],left?blue:red,7);text(String(i+1),x,y+3,v.background,8);}heading('Una configuración entre W microestados',`Partículas etiquetadas · NL=${p.left} · NR=${p.N-p.left}`);return {};}
 if(['first-law-thermodynamics','helmholtz-free-energy','gibbs-free-energy','gibbs-free-energy-spontaneity'].includes(id)&&mode!==2){const values=id==='first-law-thermodynamics'?[p.Q,-p.W,q.U]:id==='helmholtz-free-energy'?[p.U,-p.T*p.S/1000,q.A]:[p.enthalpy,-p.T*p.entropy/1000,q.value];bars(values,id==='first-law-thermodynamics'?['Q','−W','ΔU']:id==='helmholtz-free-energy'?['U','−TS','A']:['ΔH','−TΔS','ΔG']);heading('Balance energético firmado',id==='gibbs-free-energy-spontaneity'?`ΔG incluye RT lnQ=${fmt(M.R*p.T*Math.log(p.quotient)/1000)} kJ/mol`:'Las cantidades negativas se conservan con su signo');return {};}
 if((id==='chemical-equilibrium-constant-kc'||id==='dynamic-chemical-equilibrium')&&mode!==2){bars([q.A,q.B],['Reactivo A','Producto B']);heading('Dos especies: suma conservada',id==='dynamic-chemical-equilibrium'?'Concentración mol/L · evolución exacta reversible':`Compara Q con K: dirección ${q.direction}`);return {};}
 if(['power-factor-triangle','ac-ohms-law-impedance','complex-ac-impedance','series-rlc-resonance','balanced-three-phase-power'].includes(id)&&mode!==2){const power=id==='power-factor-triangle'||id==='balanced-three-phase-power',x=power?q.P:p.R,y=power?q.Q:id==='ac-ohms-law-impedance'?p.X:q.X,span=Math.max(1,Math.abs(x),Math.abs(y))*1.3,g=plane(-span,span,-span,span,power?'P activa':'R (Ω)',power?'Q reactiva':'X (Ω)');path([g.point(0,0),g.point(x,0),g.point(x,y),g.point(0,0)],blue);arrow(g.point(0,0),g.point(x,y),red);heading(power?'Triángulo de potencia sinusoidal':'Impedancia compleja: suma vectorial',power?'Q firmada · S no negativa · RMS':'La corriente tiene fase opuesta a Z para tensión de referencia real');return {};}
 if(id==='balanced-three-phase-power'){const vp=p.V/Math.sqrt(3),g=plot(0,2*Math.PI,-vp*p.I/1000,6*vp*p.I/1000,'fase (rad)','potencia (kW)');for(let j=0;j<3;j++)g.curve(a=>2*vp*p.I*Math.cos(a-2*Math.PI*j/3)*Math.cos(a-2*Math.PI*j/3-M.rad(p.phi))/1000,[blue,red,green][j]);g.curve(()=>q.P,ink);heading('Tres potencias oscilantes; suma constante','Carga equilibrada equivalente estrella · curva oscura: total');return {};}
 if(id==='beer-lambert-law'&&mode!==2){const l=w*.3,r=w*.7,t=h*.3,b=h*.7;ctx.fillStyle=blue+'22';ctx.fillRect(l,t,r-l,b-t);path([[l,t],[r,t],[r,b],[l,b],[l,t]],blue);for(let i=1;i<7;i++){const y=t+i*(b-t)/7;path([[20,y],[l,y]],green,3);path([[r,y],[w-20,y]],green+Math.max(5,Math.round(q.T*255)).toString(16).padStart(2,'0'),3);}heading('Intensidad luminosa antes y después de la celda',`100 % incidente · ${fmt(q.transmission)} % transmitida · dibujo ilustrativo`);return {};}
 if(id==='shear-stress-cizalladura'&&mode!==2){const l=w*.27,r=w*.7,b=h*.72,t=h*.32,shift=q.gamma*100*(b-t);path([[l,b],[r,b],[r+shift,t],[l+shift,t],[l,b]],blue);path([[l,t],[l,b],[r,b],[r,t]],line,1);arrow([w/2,t-15],[w/2+p.force*2,t-15],red);heading('Cizalla uniforme en pequeñas deformaciones','Deformación amplificada ×100 · γ=2εxy');return {};}
 if(id==='stokes-drag-law'&&mode!==2){circle([w/2,h/2],20+p.radius*12,blue);arrow([w/2+30,h/2-40],[w/2+30+p.speed*20,h/2-40],green);arrow([w/2-30,h/2+40],[w/2-30-p.speed*20,h/2+40],red);heading('Esfera aislada: velocidad y fuerza opuestas',q.Re<.1?'Régimen compatible con Re≪1':'Re no pequeño: el resultado es formal, no predicción fiable');return {};}
 if(['darcy-weisbach-pipe-head-loss','reynolds-number','manning-open-channel-flow'].includes(id)&&mode!==2){if(id==='manning-open-channel-flow'){const l=w*.3,r=w*.7,b=h*.72,t=h*.3;ctx.fillStyle=blue+'22';ctx.fillRect(l,b-(b-t)*p.depth/2,r-l,(b-t)*p.depth/2);path([[l,t],[l,b],[r,b],[r,t]],ink);path([[l,b-(b-t)*p.depth/2],[r,b-(b-t)*p.depth/2]],blue);heading('Canal rectangular con superficie libre','El perímetro mojado excluye la superficie superior');}else{const y=h/2,r=15+p.diameter*.3;path([[25,y-r],[w-25,y-r]],blue);path([[25,y+r],[w-25,y+r]],blue);for(let j=-2;j<=2;j++)arrow([w*.25,y+j*r/3],[w*.25+Math.min(w*.4,p.speed*w*.15),y+j*r/3],green);heading('Transporte en tubo circular',id==='reynolds-number'?`Régimen orientativo: ${q.regime}; flechas de velocidad media`:'Fricción Darcy y caída de presión · sin pérdidas locales');}return {};}

 if(id==='power-factor-triangle'&&mode===2){const g=plot(0,2*Math.PI,-1.2,1.2,'fase (rad)','señales normalizadas');g.curve(a=>Math.cos(a));g.curve(a=>Math.cos(a-M.rad(p.phi)),red);g.curve(a=>Math.cos(a)*Math.cos(a-M.rad(p.phi)),green);heading('El desfase modifica el promedio de v·i','Azul tensión · coral corriente · verde producto / (2VI)');return {};}
 if(id==='ac-ohms-law-impedance'&&mode===2){const g=plot(0,2*Math.PI,-1.2,1.2,'fase (rad)','amplitud normalizada');g.curve(a=>Math.cos(a));g.curve(a=>Math.cos(a-M.rad(q.angle)),red);heading('Tensión de referencia y corriente con fase','Azul v/Vpico · coral i/Ipico · módulos distintos, normalizados por separado');return {};}
 if(['neuronal-nernst-reversal-potential','nernst-equation'].includes(id)&&mode!==2){const neuron=id==='neuronal-nernst-reversal-potential';path([[w/2-5,55],[w/2-5,h-55]],blue,3);path([[w/2+5,55],[w/2+5,h-55]],blue,3);for(let i=0;i<8;i++){dot([w*.25+(i%3)*13,75+Math.floor(i/3)*25],green,5);dot([w*.68+(i%3)*13,75+Math.floor(i/3)*25],red,5);}text(neuron?'Exterior':'Reactivos',w*.25,h-40,green);text(neuron?'Interior':'Productos',w*.73,h-40,red);text(fmt(q.value)+(neuron?' mV':' V'),w/2,43,ink);heading(neuron?'Gradiente químico y equilibrio eléctrico':'Potencial redox de la composición','Partículas ilustrativas; el dibujo no cuantifica concentración ni flujo');return {};}
 // Domain-specific curves keep their own axes, quantities and comparison.
 let g,f,other,point,title,footer;
 switch(id){
 case 'clausius-clapeyron-equation':{const inverse=mode===2;g=plot(inverse?1000/450:300,inverse?1000/300:450,inverse?-1:0,inverse?7:Math.max(700,q.pressure*1.2),inverse?'1000/T (K⁻¹)':'T (K)',inverse?'ln(P / 1 kPa)':'P (kPa)');f=x=>{const pressure=M.model(id,{...p,T:inverse?1000/x:x}).pressure;return inverse?Math.log(pressure):pressure;};const x=inverse?1000/p.T:p.T;point=[x,f(x)];title=inverse?'La pendiente revela el calor latente':'Presión de coexistencia líquido–vapor';footer=inverse?'Recta en 1/T: pendiente −L/(1000R)':'Vapor ideal y calor latente molar constante; Kelvin';break;}
 case 'first-law-thermodynamics':g=plot(-300,500,-800,800,'Q (J)','ΔU (J)');f=Q=>Q-p.W;point=[p.Q,q.U];title='Calor entrante y cambio de energía interna';footer='Pendiente 1; trabajo realizado por el gas fijado';break;
 case 'helmholtz-free-energy':g=plot(200,800,-240,220,'T (K)','A (kJ)');f=T=>p.U-T*p.S/1000;point=[p.T,q.A];title='A=U−TS: evaluación de estados';footer='U y S pueden depender de T en un sistema real';break;
 case 'gibbs-free-energy':g=plot(200,800,-140,140,'T (K)','ΔG (kJ/mol)');f=T=>M.model(id,{...p,T}).value;point=[p.T,q.value];title='Cruce térmico por ΔG=0';footer='ΔH y ΔS aproximadamente constantes en el rango';break;
 case 'gibbs-free-energy-spontaneity':g=plot(.1,5,-140,140,'Q','ΔG (kJ/mol)');f=quotient=>M.model(id,{...p,quotient}).value;point=[p.quotient,q.value];title='La composición modifica la dirección favorecida';footer='Cociente de actividades positivo; ΔG no es rapidez';break;
 case 'shear-stress-cizalladura':g=plot(-.005,.005,-200,200,'γ','τ (MPa)');f=x=>p.G*1000*x;point=[q.gamma,q.stress];title='Elasticidad tangencial: τ=Gγ';footer='Módulo GPa convertido a MPa · γ de ingeniería';break;
 case 'stokes-drag-law':g=plot(0,5,0,M.model(id,{...p,speed:5}).force*1.2+.01,'v (mm/s)','Fd (µN)');f=speed=>M.model(id,{...p,speed}).force;point=[p.speed,q.force];title='Arrastre lineal de Stokes';footer='La curva solo es físicamente válida donde Re≪1';break;
 case 'beer-lambert-law':g=plot(0,10,0,100,'c (mmol/L)','Transmisión (%)');f=concentration=>M.model(id,{...p,concentration}).transmission;point=[p.concentration,q.transmission];title='Absorbancia lineal, transmisión exponencial';footer='A=εcl · T=10^(−A)';break;
 case 'advection-diffusion-equation':if(mode===2){g=plot(0,20,0,p.width**2+40*p.D+1,'t (s)','varianza (m²)');f=t=>p.width**2+2*p.D*t;point=[p.t,q.variance];title='Difusión: la varianza crece en 2Dt';footer='La advección desplaza el centro independientemente';}else{g=plot(-12,12,0,1,'x (m)','densidad (m⁻¹)');f=q.density;other=M.model(id,{...p,t:0}).density;point=[q.center,q.density(q.center)];title='Pulso gaussiano con masa total 1';footer='Verde: inicial · ventana parcial si el pulso sale del dibujo';}break;
 case 'darcy-weisbach-pipe-head-loss':g=plot(0,p.length,0,Math.max(1,q.head*1.2),'x (m)','carga perdida (m)');f=x=>q.head*x/p.length;point=[p.length,q.head];title='Pérdida distribuida acumulada';footer='Pendiente f v²/(2gD) · Δp=ρghf';break;
 case 'reynolds-number':g=plot(0,1,0,M.model(id,{...p,speed:1}).Re*1.1,'v (m/s)','Re');f=speed=>M.model(id,{...p,speed}).Re;point=[p.speed,q.Re];title='Inercia relativa a viscosidad';footer='Umbrales de tubo orientativos; no simula turbulencia';break;
 case 'manning-open-channel-flow':g=plot(.2,2,0,M.model(id,{...p,depth:2}).flow*1.2,'profundidad (m)','Q (m³/s)');f=depth=>M.model(id,{...p,depth}).flow;point=[p.depth,q.flow];title='La profundidad modifica área y radio hidráulico';footer='Caudal Av; canal rectangular uniforme';break;
 case 'riemann-zeta-function':g=plot(1,p.N,0,Math.min(20,q.sum+q.bound+1),'N','suma / producto');f=N=>M.model(id,{...p,N:Math.floor(N)}).sum;other=N=>{const a=M.model(id,{...p,N:Math.floor(N)});return mode===2?a.product:a.sum+a.bound;};point=[p.N,q.sum];title=mode===2?'Primos y términos: dos límites relacionados':'Suma parcial con cota superior del resto';footer=mode===2?'Producto solo sobre primos ≤N; s real >1':'Verde: cota superior · no se confunde S_N con ζ';break;
 case 'maxwell-boltzmann-speed-distribution':g=plot(0,q.rms*2.5,0,q.density(q.peak)*1.25,'v (m/s)','densidad (s/m)');f=q.density;other=mode===2?null:M.model(id,{...p,T:300}).density;point=[q.peak,q.density(q.peak)];title='Pico, media y RMS son diferentes';footer='Área total 1 · consulta tres rapideces en el resultado';break;
 case 'chemical-equilibrium-constant-kc':g=plot(0,p.total-.02,0,Math.max(6,p.K*1.5),'[B] (mol/L)','Q');f=B=>M.model(id,{...p,B}).quotient;other=()=>p.K;point=q.quotient===null?null:[p.B,q.quotient];title='Compara composición con la constante';footer='Verde K · A→0 hace divergir Q, no se asigna un valor finito';break;
 case 'dynamic-chemical-equilibrium':g=plot(0,20,0,p.total*Math.max(p.kf,p.kr)*1.2,'t (s)','velocidad (mol/L/s)');f=t=>M.model(id,{...p,t}).forward;other=t=>M.model(id,{...p,t}).reverse;title='Las velocidades convergen sin desaparecer';footer='Azul: directa · verde: inversa';break;
 case 'wohler-sn-fatigue-curve':g=plot(1,12,50,1600,'log10 N','S (MPa)');f=x=>p.A*10**(p.b*x);other=mode===2?x=>p.A*10**(-.1*x):null;point=[q.logN,p.stress];title='Basquin: amplitud alternante y ciclos';footer='Ventana 10¹…10¹²; el resultado se conserva fuera de la gráfica';break;
 case 'thermodynamic-maxwell-relations':if(mode===2){g=plot(5,30,-10,20,'V (L)','S−Sref (J/K)');f=V=>M.R*Math.log(V/10);point=[p.volume,f(p.volume)];title='Entropía isotérmica: derivada R/V';footer='Referencia 10 L · convertir L a m³ al derivar';}else{g=plot(250,500,0,850,'T (K)','P (kPa)');f=T=>M.R*T/(p.volume*.001)/1000;point=[p.T,q.P];title='Presión isócora: derivada R/V';footer='S_V|T=P_T|V para un potencial diferenciable';}break;
 case 'van-der-waals-equation-of-state':g=plot(.1,3,-10,130,'Vm (L/mol)','P (bar)');f=volume=>M.model(id,{...p,volume}).pressure;other=volume=>M.model(id,{...p,volume,T:mode===2?340:p.T})[mode===2?'pressure':'ideal'];point=[p.volume,q.pressure];title='Atracciones, covolumen y estabilidad';footer=mode===2?'Verde: isoterma 340 K · coexistencia no construida':'Verde: ideal · pendiente positiva implica inestabilidad';break;
 case 'boltzmann-entropy':g=plot(0,p.N,0,Math.log(M.comb(p.N,Math.floor(p.N/2)))*1.2,'NL','S/kB');f=n=>Math.log(M.comb(p.N,Math.round(n)));point=[p.left,q.entropy];title='Macroestados con distinta multiplicidad';footer='Conteo exacto de configuraciones etiquetadas';break;
 case 'stefan-boltzmann-law':{const max=Math.max(1,Math.abs(M.model(id,{...p,T:1000}).net));g=plot(200,1000,-max*.25,max*1.2,'T (K)','P (W)');f=T=>M.model(id,{...p,T}).net;other=mode===2?T=>M.model(id,{...p,T}).emitted:null;point=[p.T,q.net];title='Emisión e intercambio neto son diferentes';footer='Azul: neta · verde: emitida · entorno uniforme, vista 1';break;}
 case 'series-rlc-resonance':case 'complex-ac-impedance':g=plot(20,500,0,p.V/p.R*1.2,'f (Hz)','I RMS (A)');f=f=>M.model(id,{...p,f}).I;point=[p.f,q.I];title='Respuesta de corriente de un circuito RLC serie';footer='Resonancia en f0 · módulos de tensiones no se suman aritméticamente';break;
 case 'neuronal-nernst-reversal-potential':g=plot(1,150,-200,200,'concentración exterior (mmol/L)','Eion (mV)');f=out=>M.model(id,{...p,out}).E;point=[p.out,q.E];title=mode===2?'Gradiente y voltaje de equilibrio':'Potencial de reversión de un solo ion';footer='Signo de valencia importa · interior respecto a exterior';break;
 case 'nernst-equation':g=plot(.1,10,-1,2,'Q','E (V)');f=quotient=>M.model(id,{...p,quotient}).E;point=[p.quotient,q.E];title='Potencial redox y actividades';footer='Q positivo y adimensional · logaritmo natural, T absoluta';break;
 case 'arrhenius-equation':g=mode===2?plot(1/600,1/250,-15,15,'1/T (K⁻¹)','ln(k / 1 s⁻¹)'):plot(250,600,0,M.model(id,{...p,T:600}).rate*1.2,'T (K)','k (s⁻¹)');f=x=>M.model(id,{...p,T:mode===2?1/x:x})[mode===2?'log':'rate'];point=[mode===2?1/p.T:p.T,mode===2?q.log:q.rate];title=mode===2?'Recta de Arrhenius: pendiente −Ea/R':'Velocidad y barrera de activación';footer='Ea en kJ/mol se convierte a J/mol; A constante';break;
 case 'price-elasticity-of-demand':if(mode===2){g=plot(0,Math.min(60,p.a/p.b),0,p.a*p.a/(4*p.b)*1.2,'P','Ingreso');f=P=>P*(p.a-p.b*P);point=[p.price,q.revenue];title='Ingreso máximo: elasticidad de módulo 1';footer='Tramo Q≥0 · no prescribe un precio comercial';}else{g=plot(0,60,-150,200,'P','Q');f=P=>p.a-p.b*P;point=[p.price,q.quantity];title='Pendiente fija, elasticidad variable';footer='Solo Q>0 tiene elasticidad económica definida';}break;
 case 'linear-supply-demand-equilibrium':g=plot(0,60,-150,200,'P','Q');f=P=>p.a-p.b*P;other=P=>mode===2?p.a-p.b*P-p.c-p.d*P:p.c+p.d*P;point=[q.price,q.quantity];title=mode===2?'Exceso de demanda y equilibrio':'Intersección de oferta y demanda';footer=mode===2?'Verde: Qd−Qs; cruce por cero identifica P*':'Azul: demanda · verde: oferta · validar precio y cantidad';break;
 case 'wiens-displacement-law':case 'planck-law':{const peak=2897.771955/p.T;g=plot(.1,6,0,M.radiation(p.T,peak)*1.2,'λ (µm)','Bλ (W/m²/sr/µm)');f=x=>M.radiation(p.T,x);other=mode===2?(id==='planck-law'?x=>2*M.C*M.K*p.T/(x*1e-6)**4*1e-6:x=>M.radiation(p.T/2,x)):null;point=[peak,M.radiation(p.T,peak)];title='Cuerpo negro: espectro por longitud de onda';footer=id==='planck-law'?(mode===2?'Coral: pico · azul: λ elegida · verde: Rayleigh–Jeans, recortada':'Coral: pico · azul: longitud de onda elegida'):'Coral: pico · la variable espectral determina dónde está el máximo';break;}
 case 'z-hypothesis-test':g=plot(-4,4,0,.45,'z bajo H0','densidad estándar');f=x=>Math.exp(-x*x/2)/Math.sqrt(2*Math.PI);for(let j=0;j<160;j++){const x=-4+j*.05;if(mode===2?2*M.normalCDF(-Math.abs(x))<p.alpha/100:Math.abs(x)>=Math.abs(q.z))path([g.point(x,0),g.point(x,f(x))],red+'55',Math.max(1,(w-70)/160));}point=[q.z,f(q.z)];title='Área bilateral más extrema que z observado';footer=mode===2?`Colas de rechazo a α=${p.alpha} %; p observado=${q.p.toPrecision(3)}`:'El área de colas bajo H0 es p; no la probabilidad de H0';break;
 default:throw new Error(`Falta representación específica para ${id}`);
 }
 g.curve(f);if(other)g.curve(other,green);if(id==='planck-law'){const a=g.point(p.lambda,q.radiance);if(a[1]>=g.layout.t&&a[1]<=g.layout.b)dot(a,blue,5);}if(point&&point.every(Number.isFinite)){const a=g.point(...point);if(a[0]>=43&&a[0]<=w-24&&a[1]>=45&&a[1]<=h-60)dot(a,red);}heading(title,footer);return {};
}
