export function studioScene(ctx,w,h,v){
 const rgb=/^#[\da-f]{6}$/i.test(v.background)?[1,3,5].map(i=>parseInt(v.background.slice(i,i+2),16)):(v.background.match(/[\d.]+/g)||[255,255,255]).slice(0,3).map(Number),dark=rgb.reduce((s,x)=>s+x,0)<384;
 const blue=dark?'#78b8cc':v.accent,red=dark?'#e2a58d':'#9c4d37',green=dark?'#87baa0':'#397458',ink=v.ink,line=v.line,muted=v.muted;
 ctx.fillStyle=v.background;ctx.fillRect(0,0,w,h);
 const path=(points,color=blue,width=2,fill=false)=>{ctx.beginPath();points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(fill){ctx.closePath();ctx.fillStyle=color;ctx.fill();}else{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke();}};
 const text=(s,x,y,color=ink,size=12)=>{ctx.fillStyle=color;ctx.font=`${size}px system-ui`;ctx.textAlign='center';ctx.fillText(String(s),x,y,w-18);};
 const dot=(p,color=blue,r=4)=>{ctx.beginPath();ctx.arc(p[0],p[1],r,0,2*Math.PI);ctx.fillStyle=color;ctx.fill();};
 const arrow=(a,b,color=blue)=>{path([a,b],color);const t=Math.atan2(b[1]-a[1],b[0]-a[0]);path([[b[0]-7*Math.cos(t-.4),b[1]-7*Math.sin(t-.4)],b,[b[0]-7*Math.cos(t+.4),b[1]-7*Math.sin(t+.4)]],color);};
 const heading=(title,footer)=>{text(title,w/2,20,blue,w<500?11:14);const limit=Math.max(20,Math.floor(w/5.7));if(footer.length>limit){const at=footer.lastIndexOf(' ',limit);text(footer.slice(0,at),w/2,h-25,muted,w<500?9:11);text(footer.slice(at+1),w/2,h-10,muted,w<500?9:11);}else text(footer,w/2,h-12,muted,w<500?9:11);};
 const fmt=x=>Math.abs(x)>=10000?x.toExponential(1):Number(x.toFixed(3)).toLocaleString('es');
 const plot=(xmin,xmax,ymin,ymax,xlabel='',ylabel='',equal=false)=>{let l=40,r=w-20,t=52,b=h-78;if(equal){const s=Math.min((r-l)/(xmax-xmin),(b-t)/(ymax-ymin)),cx=(l+r)/2,cy=(t+b)/2;l=cx-s*(xmax-xmin)/2;r=cx+s*(xmax-xmin)/2;t=cy-s*(ymax-ymin)/2;b=cy+s*(ymax-ymin)/2;}const point=(x,y)=>[l+(x-xmin)/(xmax-xmin)*(r-l),b-(y-ymin)/(ymax-ymin)*(b-t)];path([[l,t],[l,b],[r,b]],line,1);if(ymin<0&&ymax>0)path([point(xmin,0),point(xmax,0)],line,1);if(xmin<0&&xmax>0)path([point(0,ymin),point(0,ymax)],line,1);text(fmt(xmin),l,b+14,muted,9);text(fmt(xmax),r,b+14,muted,9);text(fmt(ymax),l-4,t+12,muted,9);text(xlabel,(l+r)/2,b+29,muted,10);ctx.save();ctx.translate(l-25,(t+b)/2);ctx.rotate(-Math.PI/2);text(ylabel,0,0,muted,9);ctx.restore();
 const curve=(f,color=blue)=>{let pts=[];for(let i=0;i<=200;i++){const x=xmin+(xmax-xmin)*i/200,y=f(x);if(Number.isFinite(y)&&y>=ymin&&y<=ymax)pts.push(point(x,y));else{if(pts.length>1)path(pts,color);pts=[];}}if(pts.length>1)path(pts,color);};return {point,curve,unpoint:([x,y])=>[xmin+(x-l)/(r-l)*(xmax-xmin),ymin+(b-y)/(b-t)*(ymax-ymin)]};};
 const samples=(f,n=80)=>Array.from({length:n+1},(_,i)=>f(i/n));
 const project=(span=1.3)=>{const c=Math.cos(v.yaw),s=Math.sin(v.yaw),cp=Math.cos(v.pitch),sp=Math.sin(v.pitch),scale=Math.min((w-70)/(2*span),(h-110)/(2*span));return ([x,y,z])=>[w/2+(c*x-s*y)*scale,h/2+(sp*(s*x+c*y)-cp*z)*scale];};
 const sphere=(vectors,labels=[])=>{const P=project(1.25);for(let j=1;j<6;j++){const b=j*Math.PI/6;path(samples(t=>P([Math.sin(b)*Math.cos(t*2*Math.PI),Math.sin(b)*Math.sin(t*2*Math.PI),Math.cos(b)])),line,1);}for(let j=0;j<6;j++){const a=j*Math.PI/3;path(samples(t=>P([Math.sin(t*2*Math.PI)*Math.cos(a),Math.sin(t*2*Math.PI)*Math.sin(a),Math.cos(t*2*Math.PI)])),line,1);}for(const [i,p]of vectors.entries()){const color=[blue,red,green][i%3];arrow(P([0,0,0]),P(p),color);dot(P(p),color);if(labels[i])text(labels[i],P(p)[0]+10,P(p)[1]-8,color,10);}text('+z',...P([0,0,1.18]),muted,10);return {rotate:true};};
 const bars=(values,labels)=>{const top=65,bottom=h-65,max=Math.max(.01,...values.map(Math.abs)),signed=values.some(x=>x<0),zero=signed?(bottom+top)/2:bottom,scale=(bottom-top)/(signed?2:1)/max;path([[18,zero],[w-18,zero]],line,1);values.forEach((x,i)=>{const X=(i+.5)*w/values.length,bw=Math.min(65,w/values.length*.55),Y=zero-x*scale,color=[blue,red,green][i%3];ctx.fillStyle=color+'44';ctx.fillRect(X-bw/2,Math.min(zero,Y),bw,Math.abs(Y-zero));path([[X-bw/2,Y],[X+bw/2,Y]],color);text(labels[i],X,bottom+16,muted,w<500?9:12);if(!v.hide)text(fmt(x),X,top-14,color,10);});};
 return {ctx,w,h,blue,red,green,ink,line,muted,path,text,dot,arrow,heading,plot,samples,project,sphere,bars,fmt};
}
