const ITEMS11=[
{id:'stokes-drag-law',name:'Ley de Stokes de arrastre',formula:'Fd = 6 pi mu r v',field:'Mecánica de fluidos',level:'Universidad inicial',color:'#dc2626',topic:'stokes',summary:'Arrastre viscoso lineal sobre una esfera pequeña en régimen laminar.'},
{id:'euler-fluid-equation',name:'Ecuación de Euler de fluidos',formula:'du/dt + u du/dx = -(1/rho) dP/dx',field:'Mecánica de fluidos',level:'Universidad inicial',color:'#0ea5e9',topic:'euler',summary:'Dinámica de un fluido ideal sin viscosidad impulsado por gradientes de presión.'},
{id:'incompressible-navier-stokes-equation',name:'Ecuación de Navier-Stokes incompresible',formula:'rho Du/Dt = -grad P + mu laplacian u; div u = 0',field:'Mecánica de fluidos',level:'Universidad avanzada',color:'#a855f7',topic:'navier',summary:'Ecuación fundamental de fluidos viscosos incompresibles.'},
{id:'linear-transport-advection-equation',name:'Ecuación de transporte lineal: advección pura',formula:'dphi/dt + c dphi/dx = 0',field:'EDP y transporte',level:'Universidad inicial',color:'#10b981',topic:'transport',summary:'Modelo hiperbólico en el que un perfil se desplaza sin deformarse.'},
{id:'advection-diffusion-equation',name:'Ecuación de advección-difusión',formula:'dphi/dt + c dphi/dx = D d2phi/dx2',field:'EDP y transporte',level:'Universidad inicial',color:'#ea580c',topic:'advectiondiffusion',summary:'Combina transporte por corriente y ensanchamiento difusivo.'}
];
function sec(k,label,content,order,type='markdown'){return{key:k,label,type,order,content,lazy:false}}
function makeEntry(r){const sim='scripts/advanced-fluid-transport-simulations.js?topic='+r.topic;return{...r,year:1800,source:'files',author:'',formula:[r.formula],formulaText:[r.summary],tags:['fluidos','transporte','edp','simulacion'],prerequisites:['calculo','fluidos'],learningPath:['formula','significado','simulacion'],units:'Ver unidades.',dimensions:'Ver unidades.',symbols:[],sections:[sec('formula','Fórmula',r.formula,10,'formula'),sec('significado','Significado','# Significado\n\n'+r.summary,20),sec('historia','Historia','# Historia\n\nConcepto de mecánica de fluidos y transporte continuo.',30),sec('derivacion','Derivación','# Derivación\n\nSurge de balances locales de presión, viscosidad, advección o difusión.',40),sec('usos','Usos','# Usos\n\nSimulación de fluidos, transporte de masa, hidrodinámica y modelos de EDP.',50),sec('ficha','Ficha','# Ficha\n\nÁrea: '+r.field+'. Nivel: '+r.level+'.',60),{key:'simulacion',label:'Simulación',type:'simulation',order:900,path:sim,stylePath:'',content:''}],simulationModule:sim,simulationStylePath:''}}
function register11Fallback(){const atlas=window.FormulasAtlas;if(!atlas||!Array.isArray(atlas.equations))return false;ITEMS11.forEach(item=>{const entry=makeEntry(item);const found=atlas.equations.find(e=>e.id===entry.id);if(found)Object.assign(found,entry);else atlas.equations.push(entry)});window.dispatchEvent(new CustomEvent('formulas:catalog-mutated',{detail:{source:'batch-11-ping'}}));atlas.refresh?.();return true}
function retry11(){let tries=0;const tick=()=>{if(register11Fallback()||tries++>200)return;setTimeout(tick,250)};tick()}
window.addEventListener('formulas:catalog-ready',retry11);document.addEventListener('DOMContentLoaded',retry11);retry11();
