export default function mount({root,canvas,controls,readout}){
root.classList.add('sim-wide','calc-wide','bio-ghk-sim');root.style.setProperty('--equation-color','#2563eb');
const ctx=canvas.getContext('2d');controls.innerHTML='<label><span>permeabilidad PK</span><input id="pk" type="range" min="0" max="1" step="0.05" value="1"><output>1.00</output></label><label><span>permeabilidad PNa</span><input id="pna" type="range" min="0" max="1" step="0.05" value="0.05"><output>0.05</output></label><label><span>permeabilidad PCl</span><input id="pcl" type="range" min="0" max="1" step="0.05" value="0.10"><output>0.10</output></label>';
const pk=controls.querySelector('#pk'),pna=controls.querySelector('#pna'),pcl=controls.querySelector('#pcl'),outs=controls.querySelectorAll('output');
const Kout=5,Kin=140,Naout=145,Nain=15,Clout=110,Clin=10;
function size(){const b=canvas.getBoundingClientRect();canvas.width=Math.max(440,Math.floor(b.width||850));canvas.height=Math.max(380,Math.floor(b.height||530));return[canvas.width,canvas.height]}
function badge(t,x,y,c){ctx.font='12px monospace';ctx.fillStyle='rgba(15,23,42,.9)';ctx.fillRect(x-5,y-15,ctx.measureText(t).width+10,22);ctx.fillStyle=c;ctx.fillText(t,x,y)}
function bar(x,y,w,l,v,c,m){ctx.fillStyle='#1e293b';ctx.fillRect(x,y,w,24);ctx.fillStyle=c;ctx.fillRect(x,y,w*Math.max(0,Math.min(1,v/m)),24);ctx.fillStyle='#e2e8f0';ctx.font='12px monospace';ctx.fillText(l+': '+v.toFixed(2),x+8,y+16)}
function draw(){const PK=+pk.value,PNa=+pna.value,PCl=+pcl.value;outs[0].textContent=PK.toFixed(2);outs[1].textContent=PNa.toFixed(2);outs[2].textContent=PCl.toFixed(2);const num=PK*Kout+PNa*Naout+PCl*Clin,den=PK*Kin+PNa*Nain+PCl*Clout,Vm=61.54*Math.log10(num/den),[W,H]=size();ctx.fillStyle='#020617';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e2e8f0';ctx.font='bold 22px sans-serif';ctx.fillText('Goldman-Hodgkin-Katz: potencial de membrana',24,36);ctx.font='14px monospace';ctx.fillText('Vm = 61.54 log10((PKKo+PNaNao+PClCli)/(PKKi+PNaNai+PClClo))',24,64);const x=70,y=115,w=W*.48,h=H*.48;ctx.fillStyle='rgba(37,99,235,.14)';ctx.fillRect(x,y,w,h*.42);ctx.fillStyle='rgba(15,23,42,.9)';ctx.fillRect(x,y+h*.50,w,h*.42);ctx.strokeStyle=Vm>-30?'#dc2626':'#2563eb';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(x,y+h*.47);ctx.lineTo(x+w,y+h*.47);ctx.stroke();badge('exterior: K/Na/Cl',x+16,y+25,'#bfdbfe');badge('interior',x+16,y+h-20,'#e2e8f0');badge(Vm.toFixed(1)+' mV',x+w*.56,y+h*.47-12,Vm>-30?'#fecaca':'#bfdbfe');bar(W*.65,125,W*.28,'PK',PK,'#22c55e',1);bar(W*.65,163,W*.28,'PNa',PNa,'#ef4444',1);bar(W*.65,201,W*.28,'PCl',PCl,'#60a5fa',1);readout.innerHTML='<b>Vm='+Vm.toFixed(1)+' mV</b><br>GHK combina gradientes y permeabilidades; el ion más permeable arrastra el potencial hacia su reversión.'}
pk.oninput=pna.oninput=pcl.oninput=draw;draw();return()=>{};
}
