export default function mount({root,canvas,controls,readout}){
root.classList.add('sim-wide','calc-wide','finance-npv-sim');root.style.setProperty('--equation-color','#10b981');
const ctx=canvas.getContext('2d');controls.innerHTML='<label><span>inversión I0</span><input id="i0" type="range" min="20000" max="80000" step="5000" value="50000"><output>$50k</output></label><label><span>tasa de corte r</span><input id="r" type="range" min="2" max="25" step="1" value="12"><output>12%</output></label><label><span>escala flujos</span><input id="m" type="range" min="70" max="140" step="5" value="100"><output>100%</output></label>';
const i0I=controls.querySelector('#i0'),rI=controls.querySelector('#r'),mI=controls.querySelector('#m'),outs=controls.querySelectorAll('output');const base=[20000,25000,30000];
function size(){const b=canvas.getBoundingClientRect();canvas.width=Math.max(540,Math.floor(b.width||920));canvas.height=Math.max(430,Math.floor(b.height||560));return[canvas.width,canvas.height]}
function tag(t,x,y,c){ctx.font='12px monospace';ctx.fillStyle='rgba(15,23,42,.92)';ctx.fillRect(x-6,y-16,ctx.measureText(t).width+12,23);ctx.fillStyle=c;ctx.fillText(t,x,y)}
function money(x){return '$'+x.toLocaleString('es-ES',{maximumFractionDigits:0})}
function draw(){const I0=+i0I.value,r=+rI.value/100,m=+mI.value/100,cf=base.map(x=>x*m),pv=cf.map((x,i)=>x/Math.pow(1+r,i+1)),sum=pv.reduce((a,b)=>a+b,0),npv=sum-I0;outs[0].textContent='$'+(I0/1000).toFixed(0)+'k';outs[1].textContent=(r*100).toFixed(0)+'%';outs[2].textContent=(m*100).toFixed(0)+'%';const[W,H]=size(),x0=80,y0=H-90,w=W*.55,h=H*.50,max=Math.max(I0,...cf);ctx.fillStyle='#020617';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e2e8f0';ctx.font='bold 23px sans-serif';ctx.fillText('Valor Actual Neto: descontar flujos futuros',24,36);ctx.font='14px monospace';ctx.fillText('VAN=-I0+Σ CFt/(1+r)^t',24,64);ctx.fillStyle='#dc2626';ctx.fillRect(x0,y0-I0/max*h,44,I0/max*h);tag('-I0',x0+3,y0-I0/max*h-8,'#fecaca');pv.forEach((v,i)=>{const x=x0+90+i*74;ctx.fillStyle='#10b981';ctx.fillRect(x,y0-v/max*h,44,v/max*h);tag('PV'+(i+1),x+3,y0-v/max*h-8,'#bbf7d0')});ctx.strokeStyle='#334155';ctx.beginPath();ctx.moveTo(x0-20,y0);ctx.lineTo(x0+330,y0);ctx.stroke();ctx.fillStyle='rgba(15,23,42,.86)';ctx.fillRect(W*.65,125,W*.30,185);ctx.strokeStyle='#334155';ctx.strokeRect(W*.65,125,W*.30,185);tag('PV flujos='+money(sum),W*.67,162,'#bbf7d0');tag('VAN='+money(npv),W*.67,198,npv>=0?'#bbf7d0':'#fecaca');tag(npv>=0?'crea valor':'destruye valor',W*.67,236,npv>=0?'#bbf7d0':'#fecaca');tag('r='+(r*100).toFixed(0)+'%',W*.67,272,'#e2e8f0');readout.innerHTML='<b>VAN='+money(npv)+' · PV flujos='+money(sum)+'</b><br>El VAN mide valor creado hoy: aceptar proyectos con VAN positivo aumenta riqueza bajo esa tasa de corte.'}
i0I.oninput=rI.oninput=mI.oninput=draw;draw();return()=>{};
}
