export default function mount({root,canvas,controls,readout}){
root.classList.add('sim-wide','calc-wide','finance-irr-sim');root.style.setProperty('--equation-color','#0284c7');
const ctx=canvas.getContext('2d');controls.innerHTML='<label><span>inversión I0</span><input id="i0" type="range" min="30000" max="70000" step="2000" value="45000"><output>$45k</output></label><label><span>escala flujos</span><input id="m" type="range" min="70" max="140" step="5" value="100"><output>100%</output></label><label><span>coste capital</span><input id="wacc" type="range" min="3" max="25" step="1" value="12"><output>12%</output></label>';
const i0I=controls.querySelector('#i0'),mI=controls.querySelector('#m'),wI=controls.querySelector('#wacc'),outs=controls.querySelectorAll('output');const base=[15000,20000,25000];
function npv(rate,I0,cf){return -I0+cf.reduce((s,c,i)=>s+c/Math.pow(1+rate,i+1),0)}function irr(I0,cf){let lo=-.95,hi=4,mid=0;for(let k=0;k<90;k++){mid=(lo+hi)/2;npv(mid,I0,cf)>0?lo=mid:hi=mid}return mid}
function size(){const b=canvas.getBoundingClientRect();canvas.width=Math.max(540,Math.floor(b.width||920));canvas.height=Math.max(430,Math.floor(b.height||560));return[canvas.width,canvas.height]}
function tag(t,x,y,c){ctx.font='12px monospace';ctx.fillStyle='rgba(15,23,42,.92)';ctx.fillRect(x-6,y-16,ctx.measureText(t).width+12,23);ctx.fillStyle=c;ctx.fillText(t,x,y)}
function money(x){return '$'+x.toLocaleString('es-ES',{maximumFractionDigits:0})}
function draw(){const I0=+i0I.value,m=+mI.value/100,wacc=+wI.value/100,cf=base.map(x=>x*m),r=irr(I0,cf),npvW=npv(wacc,I0,cf);outs[0].textContent='$'+(I0/1000).toFixed(0)+'k';outs[1].textContent=(m*100).toFixed(0)+'%';outs[2].textContent=(wacc*100).toFixed(0)+'%';const[W,H]=size(),x0=70,y0=H*.62,w=W*.58,h=H*.44;ctx.fillStyle='#020617';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e2e8f0';ctx.font='bold 23px sans-serif';ctx.fillText('TIR / IRR: tasa que anula el VAN',24,36);ctx.font='14px monospace';ctx.fillText('0=-I0+Σ CFt/(1+TIR)^t',24,64);ctx.strokeStyle='#334155';ctx.beginPath();ctx.moveTo(x0,y0);ctx.lineTo(x0+w,y0);ctx.moveTo(x0,y0-h);ctx.lineTo(x0,y0+h*.45);ctx.stroke();ctx.strokeStyle='#0284c7';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<=220;i++){const rate=i/220*.65,val=npv(rate,I0,cf),px=x0+i/220*w,py=y0-Math.max(-1,Math.min(1,val/30000))*h*.75;if(i)ctx.lineTo(px,py);else ctx.moveTo(px,py)}ctx.stroke();const rx=x0+Math.min(.65,r)/.65*w;ctx.strokeStyle='#f59e0b';ctx.setLineDash([5,5]);ctx.beginPath();ctx.moveTo(rx,y0-h);ctx.lineTo(rx,y0+h*.35);ctx.stroke();ctx.setLineDash([]);tag('TIR '+(r*100).toFixed(2)+'%',rx-35,y0+h*.42,'#bae6fd');ctx.fillStyle='rgba(15,23,42,.86)';ctx.fillRect(W*.66,125,W*.29,175);ctx.strokeStyle='#334155';ctx.strokeRect(W*.66,125,W*.29,175);tag('TIR='+(r*100).toFixed(2)+'%',W*.68,162,'#bae6fd');tag('VAN@WACC='+money(npvW),W*.68,198,npvW>=0?'#bbf7d0':'#fecaca');tag(r>wacc?'aceptable':'rechazar',W*.68,236,r>wacc?'#bbf7d0':'#fecaca');readout.innerHTML='<b>TIR='+(r*100).toFixed(3)+'% · VAN al coste de capital='+money(npvW)+'</b><br>La TIR es intuitiva, pero puede ser ambigua con flujos no convencionales; el VAN sigue siendo el criterio central.'}
i0I.oninput=mI.oninput=wI.oninput=draw;draw();return()=>{};
}
