export default function mount({root,canvas,controls,readout}){
root.classList.add('sim-wide','calc-wide','ml-jsd-sim');root.style.setProperty('--equation-color','#0ea5e9');
const ctx=canvas.getContext('2d');controls.innerHTML='<label><span>P evento A</span><input id="a" type="range" min="1" max="100" step="1" value="33"><output>0.33</output></label><label><span>P evento B</span><input id="b" type="range" min="1" max="100" step="1" value="33"><output>0.33</output></label><label><span>Q sesgo A↔C</span><input id="q" type="range" min="-25" max="25" step="1" value="0"><output>0</output></label>';
const ai=controls.querySelector('#a'),bi=controls.querySelector('#b'),qi=controls.querySelector('#q'),outs=controls.querySelectorAll('output');
function kl(P,Q){let s=0;for(let i=0;i<P.length;i++)if(P[i]>0)s+=P[i]*Math.log2(P[i]/Q[i]);return s}function size(){const b=canvas.getBoundingClientRect();canvas.width=Math.max(520,Math.floor(b.width||900));canvas.height=Math.max(430,Math.floor(b.height||560));return[canvas.width,canvas.height]}
function badge(t,x,y,c){ctx.font='12px monospace';ctx.fillStyle='rgba(15,23,42,.9)';ctx.fillRect(x-5,y-15,ctx.measureText(t).width+10,22);ctx.fillStyle=c;ctx.fillText(t,x,y)}
function bars(x,y,w,label,arr,colors){badge(label,x,y-10,'#e2e8f0');arr.forEach((v,i)=>{ctx.fillStyle='#1e293b';ctx.fillRect(x,y+i*34,w,22);ctx.fillStyle=colors[i];ctx.fillRect(x,y+i*34,w*v,22);badge(v.toFixed(3),x+w*v+8,y+16+i*34,'#cbd5e1')})}
function draw(){let A=+ai.value,B=+bi.value,C=50,sum=A+B+C,P=[A/sum,B/sum,C/sum],q=+qi.value/100,Q=[1/3+q,1/3,1/3-q];Q=Q.map(x=>Math.max(.01,x));let qs=Q.reduce((a,c)=>a+c,0);Q=Q.map(x=>x/qs);const M=P.map((p,i)=>(p+Q[i])/2),J=.5*kl(P,M)+.5*kl(Q,M),dist=Math.sqrt(J);outs[0].textContent=P[0].toFixed(2);outs[1].textContent=P[1].toFixed(2);outs[2].textContent=(q*100).toFixed(0);const[W,H]=size();ctx.fillStyle='#020617';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e2e8f0';ctx.font='bold 23px sans-serif';ctx.fillText('Jensen-Shannon: divergencia simétrica y acotada',24,36);ctx.font='14px monospace';ctx.fillText('JSD(P||Q)=½KL(P||M)+½KL(Q||M),  M=(P+Q)/2',24,64);const colors=['#0ea5e9','#38bdf8','#7dd3fc'];bars(70,125,W*.35,'P variable',P,colors);bars(70,255,W*.35,'Q referencia',Q,colors);ctx.fillStyle='rgba(15,23,42,.86)';ctx.fillRect(W*.56,130,W*.36,175);ctx.strokeStyle='#334155';ctx.strokeRect(W*.56,130,W*.36,175);badge('M=['+M.map(x=>x.toFixed(2)).join(', ')+']',W*.58,165,'#bae6fd');badge('JSD='+J.toFixed(4)+' bits',W*.58,205,'#7dd3fc');badge('√JSD='+dist.toFixed(4),W*.58,245,'#e0f2fe');badge(J<.01?'casi idénticas':'separación informativa',W*.58,282,J<.01?'#bbf7d0':'#fde68a');readout.innerHTML='<b>JSD='+J.toFixed(4)+' bits · distancia √JSD='+dist.toFixed(4)+'</b><br>JSD compara distribuciones sin la asimetría dura de KL y permite usar √JSD como distancia métrica.'}
ai.oninput=bi.oninput=qi.oninput=draw;draw();return()=>{};
}
