export default function mount({root,canvas,controls,readout}){
root.classList.add('sim-wide','calc-wide','ml-pca-sim');root.style.setProperty('--equation-color','#10b981');
const ctx=canvas.getContext('2d');controls.innerHTML='<label><span>ángulo eje candidato</span><input id="a" type="range" min="0" max="180" step="5" value="35"><output>35°</output></label><label><span>mostrar proyección</span><input id="p" type="range" min="0" max="1" step="1" value="1"><output>sí</output></label>';
const ai=controls.querySelector('#a'),pi=controls.querySelector('#p'),outs=controls.querySelectorAll('output');
const data=[[-80,-50],[-55,-28],[-30,-20],[-5,5],[25,18],[50,38],[82,55],[-20,5],[35,28]];
function size(){const b=canvas.getBoundingClientRect();canvas.width=Math.max(520,Math.floor(b.width||900));canvas.height=Math.max(430,Math.floor(b.height||560));return[canvas.width,canvas.height]}
function badge(t,x,y,c){ctx.font='12px monospace';ctx.fillStyle='rgba(15,23,42,.9)';ctx.fillRect(x-5,y-15,ctx.measureText(t).width+10,22);ctx.fillStyle=c;ctx.fillText(t,x,y)}
function draw(){const deg=+ai.value,show=+pi.value>0,th=deg*Math.PI/180,c=Math.cos(th),s=Math.sin(th);outs[0].textContent=deg+'°';outs[1].textContent=show?'sí':'no';let varp=0;data.forEach(p=>{const z=p[0]*c+p[1]*s;varp+=z*z});varp/=data.length;const[W,H]=size(),cx=W*.42,cy=H*.55;ctx.fillStyle='#020617';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e2e8f0';ctx.font='bold 23px sans-serif';ctx.fillText('PCA: buscar el eje que captura máxima varianza',24,36);ctx.font='14px monospace';ctx.fillText('Z=XW,  w₁=max Var(Xw) sujeto a ||w||=1',24,64);ctx.strokeStyle='#334155';ctx.beginPath();ctx.moveTo(cx-190,cy);ctx.lineTo(cx+190,cy);ctx.moveTo(cx,cy-150);ctx.lineTo(cx,cy+150);ctx.stroke();ctx.strokeStyle='#10b981';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(cx-185*c,cy+185*s);ctx.lineTo(cx+185*c,cy-185*s);ctx.stroke();data.forEach(p=>{const z=p[0]*c+p[1]*s,px=cx+p[0],py=cy-p[1],qx=cx+z*c,qy=cy-z*s;if(show){ctx.strokeStyle='rgba(203,213,225,.65)';ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(qx,qy);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#22c55e';ctx.beginPath();ctx.arc(qx,qy,3,0,7);ctx.fill()}ctx.fillStyle='#94a3b8';ctx.beginPath();ctx.arc(px,py,5,0,7);ctx.fill()});ctx.fillStyle='rgba(15,23,42,.86)';ctx.fillRect(W*.67,120,W*.28,160);ctx.strokeStyle='#334155';ctx.strokeRect(W*.67,120,W*.28,160);badge('var proyectada='+varp.toFixed(1),W*.69,160,'#bbf7d0');badge(Math.abs(deg-35)<15?'cerca de PC1':'dirección subóptima',W*.69,198,Math.abs(deg-35)<15?'#bbf7d0':'#fecaca');badge('PC1 ≈ 35°',W*.69,236,'#86efac');readout.innerHTML='<b>Varianza proyectada='+varp.toFixed(2)+'</b><br>PCA rota los ejes para que el primer componente conserve la mayor dispersión posible de la nube centrada.'}
ai.oninput=pi.oninput=draw;draw();return()=>{};
}
