export default function mount({root,canvas,controls,readout}){
root.classList.add('sim-wide','calc-wide','transformer-mha-sim');root.style.setProperty('--equation-color','#2563eb');
const ctx=canvas.getContext('2d');controls.innerHTML='<label><span>cabeza</span><select id="head"><option value="0">Head 1: local</option><option value="1">Head 2: largo alcance</option><option value="2">Head 3: sujeto-verbo</option></select></label><label><span>temperatura softmax</span><input id="temp" type="range" min="50" max="200" step="10" value="100"><output>1.00</output></label>';
const head=controls.querySelector('#head'),tempI=controls.querySelector('#temp'),out=controls.querySelector('output');const tokens=['El','gato','duerme','plácido'];const raw=[[[2,.7,.2,0],[.2,2,.9,0],[0,.7,2,.3],[0,0,.7,2]],[[.6,1.5,.2,.8],[.2,.6,.4,1.7],[.7,1.4,.3,.6],[.2,1.8,.2,.5]],[[.2,1.5,.3,.2],[.5,.4,1.7,.2],[.2,1.2,.6,.5],[.1,1.0,.2,.7]]];
function soft(row,T){const ex=row.map(x=>Math.exp(x/T)),s=ex.reduce((a,c)=>a+c,0);return ex.map(x=>x/s)}function size(){const b=canvas.getBoundingClientRect();canvas.width=Math.max(520,Math.floor(b.width||900));canvas.height=Math.max(430,Math.floor(b.height||560));return[canvas.width,canvas.height]}
function badge(t,x,y,c){ctx.font='12px monospace';ctx.fillStyle='rgba(15,23,42,.9)';ctx.fillRect(x-5,y-15,ctx.measureText(t).width+10,22);ctx.fillStyle=c;ctx.fillText(t,x,y)}
function draw(){const h=+head.value,T=+tempI.value/100;out.textContent=T.toFixed(2);const M=raw[h].map(r=>soft(r,T));const[W,H]=size();ctx.fillStyle='#020617';ctx.fillRect(0,0,W,H);ctx.fillStyle='#e2e8f0';ctx.font='bold 23px sans-serif';ctx.fillText('Multi-Head Attention: varias matrices de atención en paralelo',24,36);ctx.font='14px monospace';ctx.fillText('Attention(Q,K,V)=softmax(QKᵀ/√d_k)V; heads=Concat(head_i)Wᴼ',24,64);const ox=W*.28,oy=130,s=48;for(let i=0;i<4;i++){ctx.fillStyle='#cbd5e1';ctx.font='12px monospace';ctx.textAlign='right';ctx.fillText(tokens[i],ox-12,oy+i*s+29);ctx.save();ctx.translate(ox+i*s+24,oy-12);ctx.rotate(-.55);ctx.textAlign='left';ctx.fillText(tokens[i],0,0);ctx.restore();for(let j=0;j<4;j++){const w=M[i][j];ctx.fillStyle='rgba(37,99,235,'+(.12+w*.9)+')';ctx.fillRect(ox+j*s,oy+i*s,s,s);ctx.strokeStyle='#1e293b';ctx.strokeRect(ox+j*s,oy+i*s,s,s)}}ctx.textAlign='left';ctx.fillStyle='rgba(15,23,42,.86)';ctx.fillRect(W*.65,130,W*.30,170);ctx.strokeStyle='#334155';ctx.strokeRect(W*.65,130,W*.30,170);badge('head '+(h+1),W*.67,165,'#bfdbfe');badge('cada fila suma 1',W*.67,198,'#bbf7d0');badge('T='+T.toFixed(2),W*.67,232,'#e2e8f0');badge(T<1?'atención aguda':'atención suave',W*.67,268,T<1?'#fde68a':'#cbd5e1');readout.innerHTML='<b>Cabeza '+(h+1)+' · temperatura '+T.toFixed(2)+'</b><br>Cada cabeza aprende una relación distinta: cercanía local, dependencia remota o patrón sintáctico especializado.'}
head.onchange=draw;tempI.oninput=draw;draw();return()=>{};
}
